import type { RawFormat } from "@/lib/types";

/**
 * CORE FORMAT KNOWLEDGE BASE
 * One line per format. `sig` = magic bytes (hex, "??" wildcard).
 * The large expansion lives in `extra-formats.ts` (subagent 2-a).
 */
export const CORE_FORMATS: RawFormat[] = [
  // ============ IMAGES ============
  { ext: ["png", "apng"], name: "Portable Network Graphics", cat: "image", viewer: "image", mime: "image/png", sig: "89 50 4E 47 0D 0A 1A 0A", desc: "Lossless raster image with alpha channel. Animated variant (APNG) supported." },
  { ext: ["jpg", "jpeg", "jpe", "jfif", "pjpeg", "pjp"], name: "JPEG Image", cat: "image", viewer: "image", mime: "image/jpeg", sig: "FF D8 FF", desc: "Lossy DCT-compressed still image (ISO 10918)." },
  { ext: ["gif"], name: "Graphics Interchange Format", cat: "image", viewer: "image", mime: "image/gif", sig: "47 49 46 38 ?? ?? 61", desc: "8-bit indexed animation-capable image (87a/89a)." },
  { ext: ["webp"], name: "WebP Image", cat: "image", viewer: "image", mime: "image/webp", sig: "52 49 46 46 ?? ?? ?? ?? 57 45 42 50", desc: "Google image format, lossy & lossless, animated." },
  { ext: ["bmp", "dib", "rle"], name: "Windows Bitmap", cat: "image", viewer: "image", mime: "image/bmp", sig: "42 4D", desc: "Uncompressed or RLE DIB raster." },
  { ext: ["tiff", "tif"], name: "Tagged Image File Format", cat: "image", viewer: "image", mime: "image/tiff", sig: "49 49 2A 00", desc: "Flexible multi-page raster; decoded in-browser via UTIF." },
  { ext: ["avif"], name: "AV1 Image File Format", cat: "image", viewer: "image", mime: "image/avif", sig: "66 74 79 70 61 76 69 66", sigOffset: 4, desc: "AV1 intra-frame coded still/animated image." },
  { ext: ["heic", "heif"], name: "High Efficiency Image File", cat: "image", viewer: "image", mime: "image/heic", sig: "66 74 79 70 68 65 69 63", sigOffset: 4, desc: "HEVC-coded image (Apple); converted to PNG in-browser." },
  { ext: ["svg"], name: "Scalable Vector Graphics", cat: "image", viewer: "svg", mime: "image/svg+xml", sig: "3C 3F 78 6D 6C ?? ?? ?? 3C 73 76 67", desc: "XML vector graphics; sandboxed render + code view." },
  { ext: ["ico", "icon"], name: "Windows Icon", cat: "image", viewer: "ico", mime: "image/x-icon", sig: "00 00 01 00", desc: "Multi-resolution icon resource." },
  { ext: ["cur"], name: "Windows Cursor", cat: "image", viewer: "ico", mime: "application/octet-stream", sig: "00 00 02 00", desc: "Cursor resource with hotspot." },
  { ext: ["psd"], name: "Photoshop Document", cat: "image", viewer: "image", mime: "image/vnd.adobe.photoshop", sig: "38 42 50 53", desc: "Layered image; flattened composite rendered." },
  { ext: ["psb"], name: "Photoshop Large Document", cat: "image", viewer: "image", mime: "image/vnd.adobe.photoshop", sig: "38 42 50 53", desc: "PSD for >30k pixel canvases." },
  { ext: ["jp2", "j2k", "jpf", "jpx"], name: "JPEG 2000", cat: "image", viewer: "image", mime: "image/jp2", sig: "00 00 00 0C 6A 50 20 20 0D 0A 87 0A", desc: "Wavelet-based JPEG successor." },
  { ext: ["tga"], name: "Truevision TARGA", cat: "image", viewer: "image", mime: "image/x-tga", desc: "Classic CG raster; header parsed, raw decode for common types." },
  { ext: ["dds"], name: "DirectDraw Surface", cat: "image", viewer: "image", mime: "image/vnd-ms.dds", sig: "44 44 53 20", desc: "GPU texture container (DXT/BC compressed)." },
  { ext: ["exr"], name: "OpenEXR", cat: "image", viewer: "image", mime: "image/aces", sig: "76 2F 31 01", desc: "HDR float image; header + channel info." },
  { ext: ["hdr", "pic"], name: "Radiance HDR", cat: "image", viewer: "image", mime: "image/vnd.radiance", sig: "23 3F 52 41 44 49 41 4E 43 45", desc: "RGBE high dynamic range." },
  { ext: ["pcx"], name: "ZSoft PC Paintbrush", cat: "image", viewer: "image", mime: "image/x-pcx", sig: "0A", desc: "DOS-era RLE raster." },
  { ext: ["pnm", "ppm", "pgm", "pbm", "pam", "pfm"], name: "Portable Any Map", cat: "image", viewer: "image", mime: "image/x-portable-anymap", desc: "Netpbm plain/RAW family." },
  { ext: ["xpm"], name: "X PixMap", cat: "image", viewer: "image", mime: "image/x-xpixmap", desc: "C-source text pixmap." },
  { ext: ["xcf"], name: "GIMP Image", cat: "image", viewer: "image", mime: "image/x-xcf", sig: "67 69 6D 70 20 78 63 66 20 76", desc: "GIMP layered native." },
  { ext: ["ora"], name: "OpenRaster", cat: "image", viewer: "image", mime: "image/openraster", desc: "ZIP-based layered interchange." },
  { ext: ["dng"], name: "Digital Negative", cat: "image", viewer: "image", mime: "image/x-adobe-dng", desc: "TIFF-based RAW photo." },
  { ext: ["crw", "cr2", "cr3", "nef", "nrw", "arw", "srf", "sr2", "dcr", "kdc", "raw", "rw2", "pef", "ptx", "raf", "3fr", "erf", "mef", "mos", "iiq", "x3f"], name: "Camera RAW Image", cat: "image", viewer: "image", mime: "image/x-raw", desc: "Vendor camera sensor dump (TIFF-based containers identified)." },
  { ext: ["icns"], name: "Apple Icon Image", cat: "image", viewer: "image", mime: "image/x-icns", sig: "69 63 6E 73", desc: "macOS icon resource." },
  { ext: ["ani"], name: "Windows Animated Cursor", cat: "image", viewer: "ico", sig: "52 49 46 46 ?? ?? ?? ?? 41 43 4F 4E", desc: "RIFF ANI animation." },
  { ext: ["wmf"], name: "Windows Metafile", cat: "image", viewer: "image", mime: "image/wmf", sig: "D7 CD C6 9A", desc: "Vector GDI records." },
  { ext: ["emf"], name: "Enhanced Metafile", cat: "image", viewer: "image", mime: "image/emf", sig: "01 00 00 00", desc: "32-bit GDI vector records." },

  // ============ VIDEO ============
  { ext: ["mp4", "m4v", "mp4v"], name: "MPEG-4 Video", cat: "video", viewer: "video", mime: "video/mp4", sig: "66 74 79 70", sigOffset: 4, desc: "ISO BMFF container; atoms parsed for codecs/duration." },
  { ext: ["webm"], name: "WebM Video", cat: "video", viewer: "video", mime: "video/webm", sig: "1A 45 DF A3", desc: "Matroska profile with VP8/VP9/AV1." },
  { ext: ["mkv", "mk3d", "mka"], name: "Matroska Video", cat: "video", viewer: "video", mime: "video/x-matroska", sig: "1A 45 DF A3", desc: "Open multimedia container; EBML header parsed." },
  { ext: ["mov", "qt"], name: "QuickTime Movie", cat: "video", viewer: "video", mime: "video/quicktime", sig: "66 74 79 70 71 74 20 20", sigOffset: 4, desc: "Apple QuickTime BMFF-style container." },
  { ext: ["avi", "vfw"], name: "Audio Video Interleave", cat: "video", viewer: "video", mime: "video/x-msvideo", sig: "52 49 46 46 ?? ?? ?? ?? 41 56 49 20", desc: "RIFF video; streams parsed from hdrl." },
  { ext: ["wmv"], name: "Windows Media Video", cat: "video", viewer: "video", mime: "video/x-ms-wmv", sig: "30 26 B2 75 8E 66 CF 11", desc: "ASF container video." },
  { ext: ["flv", "f4v"], name: "Flash Video", cat: "video", viewer: "video", mime: "video/x-flv", sig: "46 4C 56", desc: "Adobe Flash video." },
  { ext: ["3gp", "3g2", "3gpp"], name: "3GPP Mobile Video", cat: "video", viewer: "video", mime: "video/3gpp", sig: "66 74 79 70 33 67 70", sigOffset: 4, desc: "Mobile-oriented MP4 subset." },
  { ext: ["mpg", "mpeg", "m2v", "mp2", "mpe", "vob", "svcd"], name: "MPEG Program Stream", cat: "video", viewer: "video", mime: "video/mpeg", sig: "00 00 01 BA", desc: "MPEG-1/2 multiplexed stream." },
  { ext: ["ts", "m2ts", "mts", "m2t"], name: "MPEG Transport Stream", cat: "video", viewer: "video", mime: "video/mp2t", sig: "47", desc: "Broadcast packetized stream." },
  { ext: ["ogv"], name: "Ogg Video", cat: "video", viewer: "video", mime: "video/ogg", sig: "4F 67 67 53", desc: "Ogg Theora/Dirac video." },
  { ext: ["mxf"], name: "Material Exchange Format", cat: "video", viewer: "video", mime: "application/mxf", sig: "06 0E 2B 34", desc: "SMPTE professional media." },
  { ext: ["divx", "dvx"], name: "DivX Video", cat: "video", viewer: "video", mime: "video/x-divx", desc: "MPEG-4 Part 2 in AVI." },
  { ext: ["asf", "nsv"], name: "Advanced Streaming Format", cat: "video", viewer: "video", mime: "video/x-ms-asf", sig: "30 26 B2 75 8E 66 CF 11", desc: "Microsoft streaming." },

  // ============ AUDIO ============
  { ext: ["mp3"], name: "MPEG Audio Layer III", cat: "audio", viewer: "audio", mime: "audio/mpeg", sig: "49 44 33", desc: "Psychoacoustic lossy audio; ID3 tags & frames parsed." },
  { ext: ["wav", "wave"], name: "Waveform Audio", cat: "audio", viewer: "audio", mime: "audio/wav", sig: "52 49 46 46 ?? ?? ?? ?? 57 41 56 45", desc: "RIFF PCM/LPCM audio; fmt chunk fully decoded." },
  { ext: ["flac"], name: "Free Lossless Audio Codec", cat: "audio", viewer: "audio", mime: "audio/flac", sig: "66 4C 61 43", desc: "Lossless audio; STREAMINFO + Vorbis comments parsed." },
  { ext: ["ogg", "oga", "opus", "oggx"], name: "Ogg Vorbis/Opus", cat: "audio", viewer: "audio", mime: "audio/ogg", sig: "4F 67 67 53", desc: "Xiph container; codec & comments extracted." },
  { ext: ["m4a", "m4b", "m4p", "m4r", "mp4a"], name: "MPEG-4 Audio", cat: "audio", viewer: "audio", mime: "audio/mp4", sig: "66 74 79 70 4D 34 41 20", sigOffset: 4, desc: "AAC/ALAC in MP4; atom tree parsed." },
  { ext: ["aac", "adts", "aacp"], name: "Advanced Audio Coding", cat: "audio", viewer: "audio", mime: "audio/aac", sig: "FF F1", desc: "ADTS-framed AAC." },
  { ext: ["wma"], name: "Windows Media Audio", cat: "audio", viewer: "audio", mime: "audio/x-ms-wma", sig: "30 26 B2 75 8E 66 CF 11", desc: "ASF audio." },
  { ext: ["aiff", "aif", "aifc"], name: "Audio Interchange File Format", cat: "audio", viewer: "audio", mime: "audio/aiff", sig: "46 4F 52 4D ?? ?? ?? ?? 41 49 46 46", desc: "Apple PCM audio." },
  { ext: ["mid", "midi", "smf", "rmi"], name: "Musical Instrument Digital Interface", cat: "audio", viewer: "midi", mime: "audio/midi", sig: "4D 54 68 64", desc: "Standard MIDI file; tracks rendered as piano roll + playback." },
  { ext: ["mod", "ult", "wow", "m15", "mtm"], name: "Amiga Sound Tracker Module", cat: "audio", viewer: "midi", mime: "audio/x-mod", sig: "4D 4B 2E", desc: "4-channel sample tracker; pattern overview." },
  { ext: ["xm"], name: "FastTracker II Extended Module", cat: "audio", viewer: "midi", sig: "45 78 74 65 6E 64 65 64 20 4D 6F 64 75 6C 65", desc: "Multichannel module with envelopes." },
  { ext: ["s3m"], name: "Scream Tracker 3 Module", cat: "audio", viewer: "midi", sig: "53 43 52 4D", sigOffset: 44, desc: "16-channel PC tracker module." },
  { ext: ["it"], name: "Impulse Tracker Module", cat: "audio", viewer: "midi", sig: "49 4D 50 4D", desc: "Advanced tracker with filters." },
  { ext: ["ape", "apl"], name: "Monkey's Audio", cat: "audio", viewer: "audio", mime: "audio/x-ape", sig: "4D 41 43 20", desc: "Lossless codec; header parsed." },
  { ext: ["wv"], name: "WavPack Audio", cat: "audio", viewer: "audio", mime: "audio/x-wavpack", sig: "77 76 70 6B", desc: "Hybrid lossless/lossy." },
  { ext: ["opus"], name: "Opus Audio", cat: "audio", viewer: "audio", mime: "audio/opus", desc: "IETF low-latency codec in Ogg." },
  { ext: ["amr", "awb"], name: "Adaptive Multi-Rate Audio", cat: "audio", viewer: "audio", mime: "audio/amr", sig: "23 21 41 4D 52", desc: "Speech codec (3GPP)." },
  { ext: ["au", "snd"], name: "NeXT/Sun Audio", cat: "audio", viewer: "audio", mime: "audio/basic", sig: "2E 73 6E 64", desc: "µ-law classic audio." },
  { ext: ["caf"], name: "Core Audio Format", cat: "audio", viewer: "audio", mime: "audio/x-caf", sig: "63 61 66 66", desc: "Apple high-capacity audio." },
  { ext: ["dsf", "dff"], name: "DSD Stream File", cat: "audio", viewer: "audio", mime: "audio/x-dsf", sig: "44 53 44 20", desc: "1-bit Direct Stream Digital." },
  { ext: ["wma", "wax"], name: "Windows Media Audio (link)", cat: "audio", viewer: "audio", mime: "audio/x-ms-wax" },
  { ext: ["mka"], name: "Matroska Audio", cat: "audio", viewer: "audio", mime: "audio/x-matroska", sig: "1A 45 DF A3", desc: "Audio-only Matroska." },
  { ext: ["m3u", "m3u8"], name: "MP3 Playlist", cat: "audio", viewer: "text", mime: "audio/x-mpegurl", desc: "HLS or simple media playlist." },
  { ext: ["pls"], name: "Shoutcast Playlist", cat: "audio", viewer: "text", mime: "application/pls+xml" },
  { ext: ["cue", "toc"], name: "Cue Sheet", cat: "audio", viewer: "text", mime: "text/x-cue", desc: "CD track layout sheet." },
  { ext: ["sid", "psid"], name: "Commodore SID Tune", cat: "audio", viewer: "midi", mime: "audio/prs.sid", sig: "50 53 49 44", desc: "C64 MOS6581 chiptune; header info." },
  { ext: ["nsf", "nsfe"], name: "NES Sound Format", cat: "audio", viewer: "midi", sig: "4E 45 53 4D 1A", desc: "NES chiptune; expansion chips listed." },
  { ext: ["spc"], name: "SNES SPC700 Sound", cat: "audio", viewer: "midi", sig: "53 4E 45 53 53 4E 45 53", desc: "Super Famicom rip." },
  { ext: ["vgm", "vgz"], name: "Video Game Music", cat: "audio", viewer: "midi", sig: "56 67 6D 20", desc: "Sega systems command log." },
  { ext: ["ay"], name: "AY Chiptune", cat: "audio", viewer: "midi", sig: "5A 58 54 61 79 21", desc: "ZX Spectrum/Amstrad AY-3-8910." },

  // ============ DOCUMENTS ============
  { ext: ["pdf"], name: "Portable Document Format", cat: "document", viewer: "pdf", mime: "application/pdf", sig: "25 50 44 46 2D", desc: "Adobe fixed-layout document; full text search & page thumbnails." },
  { ext: ["ps"], name: "PostScript", cat: "document", viewer: "text", mime: "application/postscript", sig: "25 21 50 53", desc: "Adobe page description language (source)." },
  { ext: ["eps", "epsf", "epsi"], name: "Encapsulated PostScript", cat: "image", viewer: "text", mime: "application/postscript", sig: "25 21 50 53 2D 41 64 6F 62 65", desc: "PostScript single-page with preview." },
  { ext: ["docx"], name: "Word Open XML Document", cat: "document", viewer: "docx", mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", sig: "50 4B 03 04", desc: "OOXML; rendered via mammoth with styles." },
  { ext: ["docm"], name: "Word Macro Document", cat: "document", viewer: "docx", mime: "application/vnd.ms-word.document.macroEnabled.12", desc: "OOXML with VBA macros." },
  { ext: ["doc", "dot", "w6w", "docx Legacy"], name: "Word 97-2003 Document", cat: "document", viewer: "docx", mime: "application/msword", sig: "D0 CF 11 E0 A1 B1 1A E1", desc: "CFB-based legacy Word; text extracted." },
  { ext: ["rtf"], name: "Rich Text Format", cat: "document", viewer: "rtf", mime: "application/rtf", sig: "7B 5C 72 74 66 31", desc: "Tagged text; custom parser to styled HTML." },
  { ext: ["odt", "fodt", "odm", "ott"], name: "OpenDocument Text", cat: "document", viewer: "odf", mime: "application/vnd.oasis.opendocument.text", sig: "50 4B 03 04", desc: "OASIS zip XML word processing." },
  { ext: ["pages"], name: "Apple Pages Document", cat: "document", viewer: "odf", mime: "application/x-iwork-pages-sffpages", sig: "50 4B 03 04", desc: "iWork zip-based document." },
  { ext: ["abw", "awt"], name: "AbiWord Document", cat: "document", viewer: "xml", mime: "application/x-abiword", sig: "3C 3F 78 6D 6C", desc: "XML word processing." },
  { ext: ["wps"], name: "WPS Office Writer", cat: "document", viewer: "docx", mime: "application/vnd.ms-works", desc: "Kingsoft/MS Works word processor." },
  { ext: ["wpd"], name: "WordPerfect Document", cat: "document", viewer: "text", mime: "application/wordperfect", sig: "FF 57 50 43", desc: "Corel word processor format." },
  { ext: ["hwp", "hwpx", "hwt"], name: "Hangul Word Processor", cat: "document", viewer: "docx", mime: "application/x-hwp", desc: "Korean word processor (legacy binary + OOHWPOF)." },
  { ext: ["lrf", "lrx"], name: "BroadBand eBook", cat: "ebook", viewer: "text", mime: "application/x-sony-bbeb", sig: "4C 52 46", desc: "Sony Librié/PRS eBook." },

  // ============ SPREADSHEETS ============
  { ext: ["xlsx", "xlsm", "xltx", "xltm"], name: "Excel Open XML Workbook", cat: "spreadsheet", viewer: "xlsx", mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sig: "50 4B 03 04", desc: "OOXML workbook; all sheets, formulas & shared strings decoded." },
  { ext: ["xls", "xlm", "xla", "xlt", "xlw"], name: "Excel 97-2003 Workbook", cat: "spreadsheet", viewer: "xlsx", mime: "application/vnd.ms-excel", sig: "D0 CF 11 E0 A1 B1 1A E1", desc: "BIFF CFB workbook (SheetJS engine)." },
  { ext: ["ods", "fods", "ots"], name: "OpenDocument Spreadsheet", cat: "spreadsheet", viewer: "xlsx", mime: "application/vnd.oasis.opendocument.spreadsheet", sig: "50 4B 03 04", desc: "OASIS tabular data." },
  { ext: ["numbers"], name: "Apple Numbers Spreadsheet", cat: "spreadsheet", viewer: "xlsx", mime: "application/x-iwork-numbers-sffnumbers", desc: "iWork tabular format." },
  { ext: ["gnumeric", "gnm"], name: "Gnumeric Spreadsheet", cat: "spreadsheet", viewer: "xml", mime: "application/x-gnumeric", desc: "GNOME XML spreadsheet." },
  { ext: ["csv", "tsv", "psv", "ssv", "dsv"], name: "Delimited Text", cat: "data", viewer: "csv", mime: "text/csv", desc: "Auto-detects delimiter; sort/filter/chart tools." },
  { ext: ["dif"], name: "Data Interchange Format", cat: "spreadsheet", viewer: "text", mime: "application/x-dif", desc: "VisiCalc symmetric export." },
  { ext: ["prn", "rpt"], name: "Space-delimited Report", cat: "data", viewer: "text", mime: "text/plain", desc: "Column-aligned report output." },
  { ext: ["et", "ett"], name: "WPS Spreadsheet", cat: "spreadsheet", viewer: "xlsx", desc: "Kingsoft sheets." },

  // ============ PRESENTATIONS ============
  { ext: ["pptx", "pptm", "ppsx", "ppsm", "potx"], name: "PowerPoint Open XML", cat: "presentation", viewer: "pptx", mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation", sig: "50 4B 03 04", desc: "OOXML slide deck; slides extracted to styled pages." },
  { ext: ["ppt", "pps", "pot", "ppz"], name: "PowerPoint 97-2003", cat: "presentation", viewer: "pptx", mime: "application/vnd.ms-powerpoint", sig: "D0 CF 11 E0 A1 B1 1A E1", desc: "CFB binary slide deck (text recovered)." },
  { ext: ["odp", "fodp", "otp"], name: "OpenDocument Presentation", cat: "presentation", viewer: "pptx", mime: "application/vnd.oasis.opendocument.presentation", sig: "50 4B 03 04", desc: "OASIS slides." },
  { ext: ["key"], name: "Apple Keynote", cat: "presentation", viewer: "pptx", mime: "application/x-iwork-keynote-sffkey", desc: "iWork presentation." },
  { ext: ["sxi", "sti"], name: "OpenOffice Impress", cat: "presentation", viewer: "pptx", mime: "application/vnd.sun.xml.impress", sig: "50 4B 03 04" },
  { ext: ["pez"], name: "Prezi Desktop", cat: "presentation", viewer: "archive", mime: "application/x-prezi", sig: "50 4B 03 04" },

  // ============ EBOOKS ============
  { ext: ["epub", "epub3"], name: "Electronic Publication", cat: "ebook", viewer: "epub", mime: "application/epub+zip", sig: "50 4B 03 04", desc: "Zip-packaged XHTML book; custom reader with chapters & styling." },
  { ext: ["mobi", "prc", "azw", "azw3", "azw4", "kf8", "tpz"], name: "Mobipocket eBook", cat: "ebook", viewer: "mobi", mime: "application/x-mobipocket-ebook", sig: "42 4F 4F 6B 4D 4F 42 49", desc: "PalmDOC-based eBook; header + text extraction." },
  { ext: ["chm"], name: "Compiled HTML Help", cat: "ebook", viewer: "archive", mime: "application/vnd.ms-htmlhelp", sig: "49 54 53 46", desc: "Microsoft help (LZX compressed)." },
  { ext: ["lit"], name: "Microsoft Reader eBook", cat: "ebook", viewer: "text", mime: "application/x-ms-reader", sig: "49 54 4F 4C 49 54 4C 53", desc: "DRM-capable old MS eBook." },
  { ext: ["pdf"], name: "PDF eBook", cat: "ebook", viewer: "pdf", mime: "application/pdf" },
  { ext: ["xhtml", "xht", "html", "htm", "hta"], name: "HTML Document", cat: "document", viewer: "code", mime: "text/html", desc: "Web markup; source-highlighted + sandboxed render." },
  { ext: ["md", "markdown", "mdown", "mkd", "mkdn", "mdx", "rmd", "livemd", "mdoc"], name: "Markdown", cat: "document", viewer: "markdown", mime: "text/markdown", desc: "Lightweight markup; live render with TOC." },
  { ext: ["rst"], name: "reStructuredText", cat: "document", viewer: "markdown", mime: "text/x-rst", desc: "Docutils markup (source with highlighting)." },
  { ext: ["adoc", "asciidoc", "asc"], name: "AsciiDoc", cat: "document", viewer: "markdown", mime: "text/x-asciidoc", desc: "Technical documentation markup." },
  { ext: ["org"], name: "Org Mode", cat: "document", viewer: "code", mime: "text/x-org", desc: "Emacs Org-mode outline." },
  { ext: ["tex", "latex", "ltx", "sty", "cls", "dtx"], name: "LaTeX Source", cat: "document", viewer: "code", mime: "application/x-tex", desc: "TeX typesetting source." },
  { ext: ["dvi"], name: "Device Independent File", cat: "document", viewer: "text", mime: "application/x-dvi", sig: "F7 02", desc: "TeX compiled output." },
  { ext: ["log"], name: "Log File", cat: "text", viewer: "text", mime: "text/x-log", desc: "Timestamped application log." },
  { ext: ["nfo"], name: "Release Info (NFO)", cat: "text", viewer: "nfo", mime: "text/x-nfo", desc: "CP437-encoded ASCII-art scene release notes." },
  { ext: ["texi", "texinfo"], name: "Texinfo", cat: "document", viewer: "code", mime: "application/x-texinfo" },

  // ============ ARCHIVES ============
  { ext: ["zip", "z", "zipx", "j2ezip"], name: "ZIP Archive", cat: "archive", viewer: "archive", mime: "application/zip", sig: "50 4B 03 04", desc: "Central-directory parsed; entries previewed/extracted; nested open." },
  { ext: ["jar", "apk", "aab", "xapk", "apks", "ipa", "war", "ear", "sar", "msix", "appx", "appxbundle", "xpi", "crx", "zpk", "whl", "egg", "nupkg", "smpkg", "nupk"], name: "Packaged Application Archive", cat: "archive", viewer: "archive", sig: "50 4B 03 04", desc: "ZIP-based app package (manifests recognized)." },
  { ext: ["cbz", "cbr", "cba", "cb7", "cbt"], name: "Comic Book Archive", cat: "ebook", viewer: "archive", desc: "Paged image archive." },
  { ext: ["docx", "xlsx", "pptx", "odt", "ods", "odp", "epub", "3mf", "usdz", "globe", "ora", "kmz", "vsix", "vsix"], name: "Zip-based Compound Document", cat: "archive", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["gz", "gzip"], name: "Gzip Stream", cat: "archive", viewer: "archive", mime: "application/gzip", sig: "1F 8B 08", desc: "DEFLATE stream with original filename in header." },
  { ext: ["tar"], name: "Tape Archive", cat: "archive", viewer: "archive", mime: "application/x-tar", sig: "75 73 74 61 72", sigOffset: 257, desc: "USTAR/PAX entries listed and extractable." },
  { ext: ["tgz", "taz"], name: "Compressed Tarball (gzip)", cat: "archive", viewer: "archive", mime: "application/x-tar+gzip", sig: "1F 8B 08", desc: "gzipped tar; decompressed then listed." },
  { ext: ["tbz2", "tbz"], name: "Compressed Tarball (bzip2)", cat: "archive", viewer: "archive", mime: "application/x-tar+bzip2", sig: "42 5A 68" },
  { ext: ["txz"], name: "Compressed Tarball (xz)", cat: "archive", viewer: "archive", mime: "application/x-tar+xz", sig: "FD 37 7A 58 5A 00" },
  { ext: ["bz2", "bzip2"], name: "Bzip2 Archive", cat: "archive", viewer: "archive", mime: "application/x-bzip2", sig: "42 5A 68", desc: "BWT-compressed stream." },
  { ext: ["xz"], name: "XZ Archive", cat: "archive", viewer: "archive", mime: "application/x-xz", sig: "FD 37 7A 58 5A 00", desc: "LZMA2 stream." },
  { ext: ["zst", "zstd"], name: "Zstandard Frame", cat: "archive", viewer: "archive", mime: "application/zstd", sig: "28 B5 2F FD", desc: "Modern high-speed entropy coder." },
  { ext: ["lz4", "mlz4"], name: "LZ4 Frame", cat: "archive", viewer: "archive", mime: "application/x-lz4", sig: "04 22 4D 18", desc: "Ultra-fast block compression." },
  { ext: ["7z"], name: "7-Zip Archive", cat: "archive", viewer: "archive", mime: "application/x-7z-compressed", sig: "37 7B BC AF 27 1C", desc: "LZMA container; header parsed." },
  { ext: ["rar", "rar5"], name: "Roshal Archive", cat: "archive", viewer: "archive", mime: "application/vnd.rar", sig: "52 61 72 21 1A 07", desc: "RAR4/5 volumes; header info." },
  { ext: ["cab"], name: "Microsoft Cabinet", cat: "archive", viewer: "archive", mime: "application/vnd.ms-cab-compressed", sig: "4D 53 43 46", desc: "MS compression cabinet." },
  { ext: ["iso", "iso9660"], name: "ISO 9660 Disc Image", cat: "disk", viewer: "archive", mime: "application/x-iso9660-image", sig: "43 44 30 30 31", sigOffset: 32769, desc: "Volume descriptors parsed; file tree listed." },
  { ext: ["ar", "a"], name: "Unix ar Archive", cat: "archive", viewer: "archive", mime: "application/x-archive", sig: "21 3C 61 72 63 68 3E", desc: "Static library member listing." },
  { ext: ["deb"], name: "Debian Package", cat: "archive", viewer: "archive", mime: "application/vnd.debian.binary-package", sig: "21 3C 61 72 63 68 3E", desc: "ar archive with control.tar + data.tar." },
  { ext: ["rpm"], name: "RPM Package", cat: "archive", viewer: "archive", mime: "application/x-rpm", sig: "ED AB EE DB", desc: "Header tags parsed." },
  { ext: ["cpio"], name: "Copy In/Out Archive", cat: "archive", viewer: "archive", mime: "application/x-cpio", sig: "30 37 30 37 30 31", desc: "Cpio newc listing." },
  { ext: ["lz", "lzip"], name: "LZIP", cat: "archive", viewer: "archive", mime: "application/lzip", sig: "4C 5A 49 50", desc: "LZMA with integrity trailer." },
  { ext: ["dmg"], name: "Apple Disk Image", cat: "disk", viewer: "archive", mime: "application/x-apple-diskimage", sig: "78 01 73 0D 62 62 60", desc: "UDIF image (koly trailer detected)." },
  { ext: ["wim", "swm", "esd"], name: "Windows Imaging Format", cat: "disk", viewer: "archive", mime: "application/x-ms-wim", sig: "4D 53 57 49 4D 20 20 00", desc: "WIM volume image." },
  { ext: ["xar", "pkg"], name: "eXtensible ARchive", cat: "archive", viewer: "archive", mime: "application/x-xar", sig: "78 61 72 21", desc: "TOC-first macOS pkg container." },
  { ext: ["sit", "sitx"], name: "StuffIt Archive", cat: "archive", viewer: "archive", mime: "application/x-stuffit", sig: "53 54 55 46 46" },
  { ext: ["lzh", "lha"], name: "LHA Archive", cat: "archive", viewer: "archive", mime: "application/x-lzh", sig: "2D 6C 68 30 2D" },
  { ext: ["arc"], name: "ARC Archive", cat: "archive", viewer: "archive", sig: "1A 08" },
  { ext: ["zoo"], name: "ZOO Archive", cat: "archive", viewer: "archive", sig: "5A 4F 4F 20" },
  { ext: ["uu", "uue", "xx", "xxe", "b64", "hqx", "mime"], name: "Encoded File (UUE/xxHash/Base64)", cat: "code", viewer: "text", mime: "text/x-uuencode", desc: "Ascii-armored binary." },

  // ============ DATA ============
  { ext: ["json", "jsonc"], name: "JSON Data", cat: "data", viewer: "json", mime: "application/json", desc: "Interactive tree with search, paths & stats." },
  { ext: ["json5", "jsonl", "ndjson", "jsona"], name: "JSON Variant", cat: "data", viewer: "json", mime: "application/json5", desc: "Relaxed/newline-delimited JSON." },
  { ext: ["geojson", "topojson", "mapbox", "ndgeojson"], name: "GeoJSON", cat: "geo", viewer: "json", mime: "application/geo+json", desc: "Geographic JSON (also plotted)." },
  { ext: ["xml"], name: "XML Document", cat: "data", viewer: "xml", mime: "application/xml", sig: "3C 3F 78 6D 6C", desc: "Collapsible DOM tree view." },
  { ext: ["yaml", "yml", "yarml"], name: "YAML", cat: "data", viewer: "code", mime: "application/yaml", desc: "Human-friendly config (syntax highlighted)." },
  { ext: ["toml"], name: "TOML", cat: "config", viewer: "code", mime: "application/toml", desc: "Tom's Obvious config language." },
  { ext: ["ini", "cfg", "conf", "config", "properties", "props", "env", "dotenv", "cnf", "inf", "pref"], name: "INI-style Config", cat: "config", viewer: "code", mime: "text/plain", desc: "Key/value configuration with sections." },
  { ext: ["plist"], name: "Apple Property List", cat: "config", viewer: "xml", mime: "application/x-plist", desc: "XML or binary plist (bplist00 detected)." },
  { ext: ["sql"], name: "SQL Script", cat: "database", viewer: "code", mime: "application/sql", desc: "DDL/DML dump with highlighting." },
  { ext: ["db", "sqlite", "sqlite3", "db3", "s3db", "sl3", "sqlitedb"], name: "SQLite Database", cat: "database", viewer: "sqlite", mime: "application/x-sqlite3", sig: "53 51 4C 69 74 65 20 66 6F 72 6D 61 74 20 33 00", desc: "Full browser: tables, rows, SQL console (WASM)." },
  { ext: ["dbf"], name: "dBase Table", cat: "database", viewer: "dbf", mime: "application/x-dbf", desc: "xBase table; fields & records decoded." },
  { ext: ["mdb", "accdb", "mda", "mde"], name: "Microsoft Access Database", cat: "database", viewer: "fallback", mime: "application/x-msaccess", sig: "D0 CF 11 E0 A1 B1 1A E1", desc: "Jet/ACE database (structure info)." },
  { ext: ["parquet", "pq"], name: "Apache Parquet", cat: "data", viewer: "fallback", mime: "application/x-parquet", sig: "50 41 52 31", desc: "Columnar storage (footer parsed for schema)." },
  { ext: ["avro"], name: "Apache Avro", cat: "data", viewer: "json", mime: "avro/binary", sig: "4F 62 6A 01", desc: "Schemaful row storage (header parsed)." },
  { ext: ["bson", "bsn"], name: "Binary JSON", cat: "data", viewer: "hex", mime: "application/bson", desc: "MongoDB wire format." },
  { ext: ["msgpack", "mp", "mpe", "mshow"], name: "MessagePack", cat: "data", viewer: "hex", mime: "application/x-msgpack", desc: "Compact binary serialization." },
  { ext: ["cbor"], name: "Concise Binary Object Representation", cat: "data", viewer: "hex", mime: "application/cbor", desc: "IETF binary JSON." },
  { ext: ["hdf", "h4", "hdf4", "h5", "hdf5", "he5", "h5e", "nc", "nc4", "cdf"], name: "Scientific Data Format", cat: "scientific", viewer: "fallback", desc: "HDF5/NetCDF self-describing arrays (header info)." },
  { ext: ["fits", "fit", "fts", "fits.gz"], name: "Flexible Image Transport System", cat: "scientific", viewer: "text", sig: "53 49 4D 50 4C 45 20 20 3D 20 20 20 20 20 20 20 20 20 20 20 20 54", desc: "Astronomy standard; header cards parsed." },
  { ext: ["torrent"], name: "BitTorrent Metainfo", cat: "data", viewer: "torrent", mime: "application/x-bittorrent", sig: "64 34 3A 69 6E 66 6F 64 36 3A 6C 65 6E 67 74 68 69", desc: "Bencode dictionary decoded: trackers, files, piece info." },
  { ext: ["har"], name: "HTTP Archive", cat: "data", viewer: "json", mime: "application/json", desc: "Network request log (JSON)." },
  { ext: ["proto", "prototxt"], name: "Protocol Buffer Definition", cat: "code", viewer: "code", mime: "text/x-proto", desc: "gRPC schema source." },
  { ext: ["cap", "pcap", "pcapng", "dmpcap", "bfr", "pcapdump", "acp", "erf", "snoop", "snoopy"], name: "Packet Capture", cat: "network", viewer: "fallback", sig: "D4 C3 B2 A1", desc: "Link-layer frame dump; global header decoded." },
  { ext: ["gedcom", "ged", "gedx"], name: "Genealogy Data", cat: "data", viewer: "text", mime: "text/x-gedcom", desc: "Family tree exchange." },

  // ============ FONTS ============
  { ext: ["ttf"], name: "TrueType Font", cat: "font", viewer: "font", mime: "font/ttf", sig: "00 01 00 00 00", desc: "Quadratic-outline scalable font; glyph map & sample preview." },
  { ext: ["otf", "cff"], name: "OpenType Font", cat: "font", viewer: "font", mime: "font/otf", sig: "4F 54 54 4F", desc: "CFF cubic-outline font." },
  { ext: ["ttc"], name: "TrueType Collection", cat: "font", viewer: "font", mime: "font/collection", sig: "74 74 63 66", desc: "Multiple fonts sharing glyphs." },
  { ext: ["woff"], name: "Web Open Font Format", cat: "font", viewer: "font", mime: "font/woff", sig: "77 4F 46 46", desc: "Zlib-wrapped web font." },
  { ext: ["woff2"], name: "Web Open Font Format 2", cat: "font", viewer: "font", mime: "font/woff2", sig: "77 4F 46 32", desc: "Brotli-wrapped web font (info if undecodable)." },
  { ext: ["eot"], name: "Embedded OpenType", cat: "font", viewer: "font", mime: "application/vnd.ms-fontobject", sig: "00 01 00 00 00", desc: "Legacy IE web font." },
  { ext: ["pfb", "pfa"], name: "PostScript Type 1 Font", cat: "font", viewer: "font", mime: "application/x-font-type1", sig: "80 01", desc: "Outlines in PS code." },
  { ext: ["bdf", "pcf", "snf", "fnt", "fon"], name: "Bitmap Font", cat: "font", viewer: "font", mime: "application/x-font-bdf", sig: "53 54 41 52 54 46 4F 4E 54", desc: "Raster glyph font." },
  { ext: ["sfd"], name: "FontForge Source", cat: "font", viewer: "code", mime: "text/x-sfd", sig: "53 70 6C 69 6E 65 46 6F 6E 74 20 53 46 44" },
  { ext: ["ufo", "ufoz"], name: "Unified Font Object", cat: "font", viewer: "archive", mime: "font/ufo", desc: "XML font source bundle." },

  // ============ 3D / CAD ============
  { ext: ["obj"], name: "Wavefront OBJ", cat: "3d", viewer: "three3d", mime: "model/obj", desc: "Text mesh; interactive 3D viewport." },
  { ext: ["stl"], name: "Stereolithography Model", cat: "3d", viewer: "three3d", mime: "model/stl", desc: "Binary/ASCII triangle mesh (3D printable)." },
  { ext: ["glb"], name: "glTF Binary", cat: "3d", viewer: "three3d", mime: "model/gltf-binary", sig: "67 6C 54 46", sigOffset: 4, desc: "Binary glTF with embedded buffers." },
  { ext: ["gltf"], name: "glTF JSON", cat: "3d", viewer: "three3d", mime: "model/gltf+json", desc: "JSON 3D scene graph." },
  { ext: ["3mf", "model"], name: "3D Manufacturing Format", cat: "3d", viewer: "three3d", mime: "model/3mf", sig: "50 4B 03 04", desc: "ZIP-based 3D printing standard." },
  { ext: ["ply"], name: "Stanford PLY", cat: "3d", viewer: "three3d", mime: "model/ply", sig: "70 6C 79 0A", desc: "Polygon/point cloud format." },
  { ext: ["fbx"], name: "Autodesk FBX", cat: "3d", viewer: "three3d", mime: "application/octet-stream", sig: "4B 61 79 64 61 72 61 20 46 42 58", desc: "Proprietary interchange 3D (ASCII/binary)." },
  { ext: ["dae"], name: "COLLADA Digital Asset", cat: "3d", viewer: "three3d", mime: "model/vnd.collada+xml", sig: "3C 3F 78 6D 6C", desc: "XML 3D interchange." },
  { ext: ["blend", "blend1"], name: "Blender Scene", cat: "3d", viewer: "fallback", mime: "application/x-blender", sig: "42 4C 45 4E 44 45 52", desc: "Blender DNA blocks (header info)." },
  { ext: ["3ds", "max"], name: "3D Studio / 3ds Max", cat: "3d", viewer: "three3d", mime: "application/x-3ds", sig: "4D 4D 44 4D", desc: "Autodesk chunks." },
  { ext: ["dxf", "dwf"], name: "Drawing Exchange Format", cat: "3d", viewer: "code", mime: "image/vnd.dxf", desc: "CAD text exchange." },
  { ext: ["dwg"], name: "AutoCAD Drawing", cat: "3d", viewer: "fallback", mime: "image/vnd.dwg", sig: "41 43 31 30", desc: "Binary CAD (version detected)." },
  { ext: ["step", "stp", "p21"], name: "STEP Product Data", cat: "3d", viewer: "code", mime: "application/step", desc: "ISO 10303-21 CAD exchange." },
  { ext: ["iges", "igs"], name: "IGES Drawing", cat: "3d", viewer: "code", mime: "model/iges" },
  { ext: ["gcode", "gco", "g", "nc", "tap", "mpf", "apt"], name: "G-code Toolpath", cat: "3d", viewer: "gcode", mime: "text/x-gcode", desc: "CNC/additive toolpath; 3D path render + stats." },
  { ext: ["s3g", "x3g"], name: "x3g Machine Binary", cat: "3d", viewer: "fallback", mime: "application/x-x3g" },
  { ext: ["wrl", "wrz", "x3d", "x3db", "x3dv"], name: "VRML / X3D World", cat: "3d", viewer: "three3d", mime: "model/vrml", sig: "23 56 52 4D 4C", desc: "ISO 3D web scene." },
  { ext: ["usdz", "usd", "usda", "usdc", "usdz"], name: "Universal Scene Description", cat: "3d", viewer: "archive", mime: "model/vnd.usdz+zip", sig: "50 4B 03 04", desc: "Pixar USD (zip crate)." },
  { ext: ["lwo", "lws", "lwb"], name: "LightWave 3D", cat: "3d", viewer: "fallback", sig: "46 4F 52 4D ?? ?? ?? ?? 4C 57 4F 42" },
  { ext: ["c4d"], name: "Cinema 4D Project", cat: "3d", viewer: "fallback" },
  { ext: ["ma", "mb"], name: "Maya Scene", cat: "3d", viewer: "code" },
  { ext: ["x3d"], name: "X3D", cat: "3d", viewer: "three3d" },

  // ============ GAME / EMULATION ============
  { ext: ["sav"], name: "Game Save / Battery", cat: "game", viewer: "hex", mime: "application/x-sav" },
  { ext: ["nes", "nez", "unf", "unif"], name: "NES ROM", cat: "game", viewer: "fallback", sig: "4E 45 53 1A", desc: "iNES header: PRG/CHR banks, mapper." },
  { ext: ["sfc", "smc", "fig", "swc"], name: "SNES ROM", cat: "game", viewer: "fallback", desc: "LoROM/HiROM cartridge image." },
  { ext: ["gb", "sgb"], name: "Game Boy ROM", cat: "game", viewer: "fallback", sig: "CE ED 66 66", sigOffset: 308, desc: "Cartridge header with Nintendo logo." },
  { ext: ["gbc"], name: "Game Boy Color ROM", cat: "game", viewer: "fallback", sig: "CE ED 66 66", sigOffset: 308 },
  { ext: ["gba", "agb"], name: "Game Boy Advance ROM", cat: "game", viewer: "fallback", sig: "CE ED 66 66", sigOffset: 308 },
  { ext: ["nds", "dsi"], name: "Nintendo DS ROM", cat: "game", viewer: "fallback", desc: "NDS cartridge with decryptable header." },
  { ext: ["n64", "z64", "v64", "u3"], name: "Nintendo 64 ROM", cat: "game", viewer: "fallback", sig: "80 37 12 40", desc: "Big/little-swapped N64 cart." },
  { ext: ["wii", "wad", "wbfs", "rvz", "wux"], name: "Wii Disc / Channel", cat: "game", viewer: "fallback", desc: "Wii images (DOL/IOS info)." },
  { ext: ["iso", "ciso", "cso", "dax", "jsl", "pbp", "chd", "gcm", "rvz"], name: "Game Disc Image", cat: "game", viewer: "archive", desc: "Compressed/raw game dumps (ISO base preferred)." },
  { ext: ["ipsw", "flex"], name: "Firmware Bundle", cat: "system", viewer: "archive", sig: "50 4B 03 04", desc: "Device firmware zip." },
  { ext: ["nbt", "dat (NBT)", "mclevel"], name: "Named Binary Tag (Minecraft)", cat: "game", viewer: "nbt", mime: "application/octet-stream", sig: "0A 00 00", desc: "Gzip'd or raw NBT tree — worlds, players, structures." },
  { ext: ["mca", "mcr", "mca region"], name: "Minecraft Region File", cat: "game", viewer: "fallback", sig: "1F 8B 08", desc: "Chunk region container (32×32 chunks)." },
  { ext: ["mcworld", "mcpack", "mctemplate"], name: "Minecraft Pack", cat: "game", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["level", "level.dat", "players"], name: "Minecraft Data", cat: "game", viewer: "nbt", sig: "1F 8B 08" },
  { ext: ["iwd", "pk3", "pk4", "vpk", "pak", "pak0"], name: "Game Asset Archive", cat: "game", viewer: "archive", desc: "Id/Valve/Quake asset packages." },
  { ext: ["bsp", "map", "lin", "shader", "vmt", "vtf", "mdl", "md2", "md3", "md5mesh", "md5anim", "mdl", "spr", "smd", "vvd", "phy"], name: "Game Engine Asset", cat: "game", viewer: "fallback", desc: "Level/model/texture assets (headers detected)." },
  { ext: ["unity3d", "asset", "assets", "bundle", "u3d", "resource"], name: "Unity Asset", cat: "game", viewer: "fallback", sig: "55 6E 69 74 79 46 53", desc: "Unity serialized bundle." },
  { ext: ["umap", "upk", "udk", "uasset", "upk"], name: "Unreal Engine Asset", cat: "game", viewer: "fallback", sig: "C1 83 2A 9E", desc: "UE package (signature detected)." },
  { ext: ["w3mod"], name: "Witcher Mod", cat: "game", viewer: "archive" },
  { ext: ["ess", "vsave", "sav"], name: "Emulator Save State", cat: "game", viewer: "fallback" },
  { ext: ["mcr", "gme", "mem", "vms"], name: "Memory Card Image", cat: "game", viewer: "fallback" },
  { ext: ["ips", "bps", "ups", "vcdiff", "xdelta", "patch"], name: "Binary Patch", cat: "game", viewer: "fallback", sig: "50 41 54 43 48", desc: "ROM patch delta." },
  { ext: ["dsk", "ima", "img", "360", "720", "1200", "1440", "2880", "hd0", "hd1", "td0", "imd", "xdf", "d88", "88d", "hdi", "dup", "dfi", "f7", "fdd"], name: "Diskette Image", cat: "disk", viewer: "fallback", desc: "Floppy sector dumps." },

  // ============ EMAIL / PIM ============
  { ext: ["eml", "mht", "mhtml", "mbox", "mbx", "nws"], name: "Email Message", cat: "email", viewer: "eml", mime: "message/rfc822", desc: "RFC-822: headers, MIME parts, attachments extracted." },
  { ext: ["msg"], name: "Outlook Message", cat: "email", viewer: "fallback", sig: "D0 CF 11 E0 A1 B1 1A E1", desc: "CFB-stored Outlook item (text recovered)." },
  { ext: ["ics", "ical", "icalendar", "ifb", "vcs"], name: "iCalendar", cat: "other", viewer: "ical", mime: "text/calendar", desc: "VCALENDAR events parsed to schedule view." },
  { ext: ["vcf", "vcard", "vct", "gcrd", "vcard"], name: "vCard Contact", cat: "other", viewer: "ical", mime: "text/vcard", desc: "Contact cards parsed to address list." },
  { ext: ["ldif"], name: "LDAP Data Interchange", cat: "other", viewer: "code", mime: "text/x-ldif" },

  // ============ GEO ============
  { ext: ["gpx"], name: "GPS Exchange Format", cat: "geo", viewer: "map", mime: "application/gpx+xml", sig: "3C 3F 78 6D 6C", desc: "Trackpoints/waypoints plotted with elevation profile." },
  { ext: ["kml", "kmz"], name: "Keyhole Markup Language", cat: "geo", viewer: "map", mime: "application/vnd.google-earth.kml+xml", desc: "Earth placemarks & paths." },
  { ext: ["tcx"], name: "Training Center XML", cat: "geo", viewer: "map", mime: "application/vnd.garmin.tcx+xml", desc: "Garmin workouts." },
  { ext: ["fit", "fitx"], name: "Flexible & Interoperable Data Transfer", cat: "geo", viewer: "fallback", sig: "2E 46 49 54", sigOffset: 8, desc: "Garmin binary FIT (header parsed)." },
  { ext: ["shp", "shx"], name: "ESRI Shapefile", cat: "geo", viewer: "fallback", sig: "00 00 27 0A", desc: "Geospatial vector (shape types decoded)." },
  { ext: ["gdb"], name: "ESRI Geodatabase", cat: "geo", viewer: "fallback" },
  { ext: ["osm", "osmxml", "osm.pbf", "osm2"], name: "OpenStreetMap Extract", cat: "geo", viewer: "xml", mime: "application/vnd.openstreetmap.data+xml" },
  { ext: ["gml"], name: "Geography Markup Language", cat: "geo", viewer: "xml", mime: "application/gml+xml" },
  { ext: ["dgn", "dem", "asc (gis)"], name: "GIS Raster/Grid", cat: "geo", viewer: "fallback" },
  { ext: ["ov2"], name: "TomTom POI", cat: "geo", viewer: "fallback" },
  { ext: ["ovf"], name: "Guitar Pro Overflow", cat: "other", viewer: "text" },

  // ============ SCIENTIFIC ============
  { ext: ["fasta", "fa", "fna", "faa", "ffn", "frn", "fsa", "mpfa", "fst"], name: "FASTA Sequence", cat: "scientific", viewer: "text", mime: "text/x-fasta", desc: "DNA/protein sequences; stats & GC content." },
  { ext: ["fastq", "fq"], name: "FASTQ Reads", cat: "scientific", viewer: "text", mime: "text/x-fastq" },
  { ext: ["pdb", "ent", "xyz", "pqr", "cif", "mmcif", "mmtf"], name: "Protein Structure", cat: "scientific", viewer: "three3d", mime: "chemical/x-pdb", desc: "3D molecular coordinates; space-filling render." },
  { ext: ["mol", "sdf", "mdl", "sd", "mol2", "smi", "smiles", "inchi"], name: "Molecular Data", cat: "scientific", viewer: "text", mime: "chemical/x-mdl-molfile", desc: "Connection tables & line notations." },
  { ext: ["genbank", "gb", "gbk", "gbff", "gbs"], name: "GenBank Flat File", cat: "scientific", viewer: "text", mime: "text/x-genbank" },
  { ext: ["clustal", "aln", "aln"], name: "Multiple Alignment", cat: "scientific", viewer: "text", mime: "text/x-clustalw" },
  { ext: ["nii", "nii.gz", "nii", "hdr", "img"], name: "NIfTI Neuroimaging", cat: "scientific", viewer: "fallback", sig: "5C 01 00 00", desc: "Brain imaging volumes (header parsed)." },
  { ext: ["dcm", "dicom", "dic", "dicm", "dcm30", "acr", "ima", "mrc", "v2"], name: "DICOM Medical Image", cat: "scientific", viewer: "dicom", mime: "application/dicom", sig: "44 49 43 4D", sigOffset: 128, desc: "Patient/study tags parsed + pixel render." },
  { ext: ["nrrd", "nhdr"], name: "NRRD Tensor Image", cat: "scientific", viewer: "fallback", sig: "4E 52 52 44 30 30 30 35", desc: "Nearly Raw Raster Data." },
  { ext: ["vsi", "svs", "ndpi", "scn", "mrxs", "bif", "tif3"], name: "Whole Slide Image", cat: "scientific", viewer: "fallback", desc: "Pyramidal pathology scans." },
  { ext: ["mzml", "mzxml", "mzdata", "mgf", "mzid"], name: "Mass Spectrometry", cat: "scientific", viewer: "xml", desc: "Proteomics spectra formats." },
  { ext: ["vasp", "poscar", "contcar", "chg", "chgcar", "doscar", "eigenval"], name: "VASP Material Data", cat: "scientific", viewer: "text" },
  { ext: ["gro", "trr", "xtc", "pdb.gz", "dcd", "lammps", "dump", "lmp", "data.lmp"], name: "Molecular Dynamics", cat: "scientific", viewer: "fallback" },

  // ============ SYSTEM / BINARY ============
  { ext: ["exe", "com", "sys", "msi", "msp", "mst", "dll", "drv", "efi", "scr", "cpl", "ocx", "ax", "mui", "rll", "sys", "vxd", "386", "vmm", "le", "lx", "ne", "fx"], name: "Windows Executable", cat: "system", viewer: "exe", mime: "application/x-msdownload", sig: "4D 5A", desc: "PE header: sections, imports, timestamps, ASLR/DEP flags." },
  { ext: ["so", "o", "so.0", "elf", "bin (elf)", "ko", "axf", "out", "prx", "puff", "ko.xz", "dSYM"], name: "ELF Object", cat: "system", viewer: "exe", mime: "application/x-executable", sig: "7F 45 4C 46", desc: "Architecture, sections, dynamic libs, symbols." },
  { ext: ["dylib", "bundle", "kext", "app", "deb (mach)", "macho"], name: "Mach-O Binary", cat: "system", viewer: "exe", sig: "CF FA ED FE", desc: "Load commands & architectures." },
  { ext: ["class", "jar", "jmod", "jimage"], name: "Java Class", cat: "code", viewer: "fallback", sig: "CA FE BA BE", desc: "Java 8 magic: version, constant pool count." },
  { ext: ["wasm"], name: "WebAssembly Module", cat: "system", viewer: "wasm", mime: "application/wasm", sig: "00 61 73 6D", desc: "Section table, imports/exports, name section decoded." },
  { ext: ["swf", "swc"], name: "Adobe Flash Movie", cat: "video", viewer: "fallback", sig: "46 57 53", desc: "Stage size, frame rate, version." },
  { ext: ["ko", "mod", "sys", "vxd", "drv (nt)"], name: "Kernel Module", cat: "system", viewer: "exe" },
  { ext: ["appimage", "snap", "flatpak", "app", "snap", "appimage"], name: "Linux App Bundle", cat: "system", viewer: "fallback" },
  { ext: ["msi"], name: "Windows Installer", cat: "system", viewer: "exe", sig: "D0 CF 11 E0 A1 B1 1A E1", desc: "CFB database with tables." },
  { ext: ["hex", "s19", "srec", "mot", "s28", "s37"], name: "Intel HEX / SREC", cat: "system", viewer: "text", mime: "text/x-hex", desc: "ASCII-encoded ROM images." },
  { ext: ["bin", "rom", "img", "dump", "flash", "eprom"], name: "Raw Binary Dump", cat: "binary", viewer: "hex", mime: "application/octet-stream", desc: "Byte-level forensic view." },
  { ext: ["img", "ima", "vhd", "vhdx", "vmdk", "vdi", "qcow", "qcow2", "hdd", "hds", "sparsebundle", "dmg", "toast", "vfd", "vhd", "avhd", "vsv", "mbr", "gpt"], name: "Disk Image", cat: "disk", viewer: "fallback", desc: "Virtual disk containers (descriptor parsed)." },
  { ext: ["vbox", "ovf", "ova", "vmx", "vmxf", "vmsd", "nvram", "vmem", "vmsn", "vmss"], name: "VM Configuration", cat: "system", viewer: "text", desc: "Hypervisor definitions & snapshots." },
  { ext: ["reg"], name: "Windows Registry Text", cat: "system", viewer: "code", mime: "text/x-reg" },
  { ext: ["pf", "prefetch"], name: "Windows Prefetch", cat: "system", viewer: "fallback", sig: "53 43 43 41", desc: "Executable access traces." },
  { ext: ["evtx"], name: "Windows Event Log (Vista+)", cat: "system", viewer: "fallback", sig: "45 6C 66 46 69 6C 65 00" },
  { ext: ["dmp", "mdmp", "dump", "hdmp"], name: "Memory Dump", cat: "system", viewer: "fallback", sig: "4D 44 4D 50", desc: "Minidump process memory." },
  { ext: ["pcap", "pcapng", "cstream"], name: "Packet Capture", cat: "system", viewer: "fallback" },
  { ext: ["der", "cer", "crt", "ca-bundle", "p7b", "p7c", "p7r", "p7s", "p7m", "spc", "stl"], name: "X.509 Certificate", cat: "system", viewer: "hex", mime: "application/pkix-cert", sig: "30 82", desc: "ASN.1 DER (browser-parsed where possible)." },
  { ext: ["pem", "key", "pub", "crl", "gpg", "asc", "p12", "pfx", "jks", "keystore", "kdb", "kdbx", "pup", "ppk"], name: "Key / Keystore", cat: "system", viewer: "code", mime: "application/x-pem-file", desc: "Armored keys & encrypted stores (headers only)." },
  { ext: ["luac", "lub"], name: "Lua Bytecode", cat: "code", viewer: "fallback", sig: "1B 4C 75 61", desc: "Compiled Lua chunk header." },
  { ext: ["pyc", "pyo"], name: "Python Bytecode", cat: "code", viewer: "fallback", sig: "4F 0D 0D 0A", desc: "Marshalled module (versioned magic)." },
  { ext: ["rbc", "rubybc"], name: "Ruby Compiled", cat: "code", viewer: "fallback" },
  { ext: ["dll"], name: "Dynamic Library", cat: "system", viewer: "exe", sig: "4D 5A" },
  { ext: ["lnk"], name: "Windows Shortcut", cat: "system", viewer: "fallback", sig: "4C 00 00 00 01 14 02 00", desc: "Shell link target parsing." },
  { ext: ["xapk"], name: "Android Split Bundle", cat: "system", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["bak", "bk", "bkp", "old", "orig", "save", "tmp", "temp", "~", "swp", "swo", "swn", "asv", "b00", "bup", "gzip"], name: "Backup / Temp File", cat: "other", viewer: "fallback", desc: "Timestamped or partial backup — inner type re-detected." },

  // ============ CODE (major languages) ============
  { ext: ["js", "mjs", "cjs", "jsx"], name: "JavaScript", cat: "code", viewer: "code", mime: "text/javascript", desc: "ECMAScript source with full syntax highlighting." },
  { ext: ["ts", "tsx", "mts", "cts"], name: "TypeScript", cat: "code", viewer: "code", mime: "text/typescript" },
  { ext: ["jsx", "tsx"], name: "React JSX/TSX", cat: "code", viewer: "code" },
  { ext: ["py", "pyw", "pyi", "rpy", "pyde", "pyp", "talc"], name: "Python", cat: "code", viewer: "code", mime: "text/x-python" },
  { ext: ["java", "jav"], name: "Java", cat: "code", viewer: "code", mime: "text/x-java-source" },
  { ext: ["c", "h"], name: "C Source", cat: "code", viewer: "code", mime: "text/x-c" },
  { ext: ["cpp", "cc", "cxx", "hpp", "hh", "hxx", "c++", "h++", "ipp", "tpp", "inl"], name: "C++ Source", cat: "code", viewer: "code", mime: "text/x-c++" },
  { ext: ["cs", "csx", "csproj"], name: "C#", cat: "code", viewer: "code", mime: "text/x-csharp" },
  { ext: ["go", "mod (go)"], name: "Go", cat: "code", viewer: "code", mime: "text/x-go" },
  { ext: ["rs", "rlib"], name: "Rust", cat: "code", viewer: "code", mime: "text/x-rust" },
  { ext: ["rb", "rbw", "rake", "gemspec", "ru", "erb", "haml", "slim"], name: "Ruby", cat: "code", viewer: "code", mime: "text/x-ruby" },
  { ext: ["php", "php3", "php4", "php5", "php7", "phps", "phtml", "pht", "inc (php)"], name: "PHP", cat: "code", viewer: "code", mime: "application/x-httpd-php" },
  { ext: ["swift", "swiftmodule"], name: "Swift", cat: "code", viewer: "code", mime: "text/x-swift" },
  { ext: ["kt", "kts", "ktm"], name: "Kotlin", cat: "code", viewer: "code", mime: "text/x-kotlin" },
  { ext: ["scala", "sc"], name: "Scala", cat: "code", viewer: "code", mime: "text/x-scala" },
  { ext: ["sh", "bash", "zsh", "ksh", "bashrc", "zshrc", "profile", "bash_profile", "bash_login", "bash_logout", "command"], name: "Shell Script", cat: "code", viewer: "code", mime: "text/x-shellscript", desc: "POSIX shell with shebang detection." },
  { ext: ["ps1", "psm1", "psd1", "psc1"], name: "PowerShell", cat: "code", viewer: "code", mime: "text/x-powershell" },
  { ext: ["bat", "cmd", "btm", "com", "nwscript"], name: "DOS Batch", cat: "code", viewer: "code", mime: "application/bat" },
  { ext: ["pl", "pm", "pod", "t", "tcl", "tk", "raku", "rakumod", "p6", "pl6", "nqp"], name: "Perl / Tcl", cat: "code", viewer: "code", mime: "text/x-perl" },
  { ext: ["lua"], name: "Lua", cat: "code", viewer: "code", mime: "text/x-lua" },
  { ext: ["r", "rmd", "rnw", "rd", "rsx", "rdata", "rds", "rda"], name: "R Statistics", cat: "code", viewer: "code", mime: "text/x-r" },
  { ext: ["jl"], name: "Julia", cat: "code", viewer: "code", mime: "text/x-julia" },
  { ext: ["m", "mm", "M"], name: "Objective-C", cat: "code", viewer: "code", mime: "text/x-objective-c" },
  { ext: ["dart", "drt"], name: "Dart", cat: "code", viewer: "code", mime: "text/x-dart" },
  { ext: ["groovy", "gvy", "gy", "gsh"], name: "Groovy", cat: "code", viewer: "code" },
  { ext: ["asm", "s", "S", "nasm", "masm", "s69", "z80", "6502", "asm65"], name: "Assembly", cat: "code", viewer: "code", mime: "text/x-asm" },
  { ext: ["f", "f90", "f95", "f03", "f08", "for", "f77", "fpp", "f15"], name: "Fortran", cat: "code", viewer: "code", mime: "text/x-fortran" },
  { ext: ["cob", "cbl", "ccp", "cobol", "cpy"], name: "COBOL", cat: "code", viewer: "code" },
  { ext: ["pas", "pp", "dpr", "lpr", "inc", "dfm"], name: "Pascal / Delphi", cat: "code", viewer: "code" },
  { ext: ["adb", "ads", "ada", "pad"], name: "Ada", cat: "code", viewer: "code" },
  { ext: ["d", "di"], name: "D Language", cat: "code", viewer: "code", mime: "text/x-d" },
  { ext: ["zig", "zon"], name: "Zig", cat: "code", viewer: "code" },
  { ext: ["nim", "nims", "nimble"], name: "Nim", cat: "code", viewer: "code" },
  { ext: ["hs", "lhs", "hs-boot"], name: "Haskell", cat: "code", viewer: "code" },
  { ext: ["ml", "mli", "mll", "mly", "fs", "fsi", "fsx", "fsscript"], name: "OCaml / F#", cat: "code", viewer: "code" },
  { ext: ["erl", "hrl", "ex", "exs", "eex", "leex", "heex", "beam", "escript"], name: "Erlang / Elixir", cat: "code", viewer: "code" },
  { ext: ["clj", "cljs", "cljc", "edn", "cljd", "hy", "rkt", "scm", "ss", "lisp", "lsp", "l", "el", "elc", "sc", "vau", "sld"], name: "Lisp Family", cat: "code", viewer: "code" },
  { ext: ["vb", "vbs", "vba", "bas", "frm", "vbproj"], name: "Visual Basic", cat: "code", viewer: "code" },
  { ext: ["v", "vh", "sv", "svh", "vhd", "vhdl", "udo", "qsf"], name: "Verilog / VHDL", cat: "code", viewer: "code", desc: "HDL RTL sources." },
  { ext: ["sol"], name: "Solidity Contract", cat: "code", viewer: "code" },
  { ext: ["sql", "ddl", "dml"], name: "SQL Query", cat: "code", viewer: "code" },
  { ext: ["graphql", "gql", "prisma"], name: "GraphQL Schema", cat: "code", viewer: "code" },
  { ext: ["scss", "sass", "css", "less", "styl", "stylus", "pcss", "postcss", "sss", "css.map", "act"], name: "Stylesheet", cat: "code", viewer: "code", mime: "text/css", desc: "Cascading style sources." },
  { ext: ["phps", "phtml", "tpl", "mustache", "hbs", "handlebars", "ejs", "jinja", "jinja2", "j2", "twig", "liquid", "njk", "nunjucks", "dust", "eco", "hamlet", "blade.php", "vlt", "vm"], name: "Template", cat: "code", viewer: "code", desc: "Logic-embedded HTML templates." },
  { ext: ["vue", "svelte", "astro", "marko", "riot"], name: "Component Framework File", cat: "code", viewer: "code" },
  { ext: ["gradle", "groovy", "kts"], name: "Gradle Build Script", cat: "code", viewer: "code" },
  { ext: ["cmake", "CMakeLists.txt", "mk", "makefile", "Makefile", "make", "mak", "ninja", "ninja", "meson", "sconstruct", "sconstruct", "waf", "premake", "bazel", "bzl", "tiltfile"], name: "Build Script", cat: "code", viewer: "code" },
  { ext: ["dockerfile", "docker", "containerfile", "podfile", "jenkinsfile", "justfile", "vagrantfile", "berksfile", "gemfile", "rakefile", "brewfile", "guardfile", "capfile", "thorfile", "puppetfile", "fastfile", "appfile", "deliverfile", "snapfile", "matchfile", "scanfile", "gymfile", "dangerfile", "cartfile", "podfile", "mix.exs"], name: "Devflow Recipe", cat: "config", viewer: "code", desc: "Automation DSL (Dockerfiles, Jenkinsfiles etc.)." },
  { ext: ["patch", "diff", "rej"], name: "Unified Diff", cat: "code", viewer: "code", mime: "text/x-diff", desc: "Change hunks with +/- coloring." },
  { ext: ["cfg.ini", "conf", "editorconfig", "gitconfig", "gitignore", "gitattributes", "npmrc", "yarnrc", "babelrc", "eslintrc", "prettierrc", "terminator", "condarc", "condarc", "flake8", "pylintrc", "coveragerc", "buck", "hocon"], name: "Dotfile Config", cat: "config", viewer: "code" },
  { ext: ["cson", "coffee", "litcoffee", "iced"], name: "CoffeeScript", cat: "code", viewer: "code" },
  { ext: ["textile", "creole", "twiki", "pmwiki", "dokuwiki", "mediawiki", "wiki", "wikitext"], name: "Wiki Markup", cat: "text", viewer: "markdown" },
  { ext: ["po", "pot", "mo", "strings", "xliff", "xlf", "lrc", "srt.props"], name: "Localization", cat: "text", viewer: "code", desc: "Gettext & XLIFF translations." },

  // ============ SUBTITLES ============
  { ext: ["srt", "subrip"], name: "SubRip Subtitles", cat: "subtitle", viewer: "subtitle", mime: "application/x-subrip", desc: "Numbered blocks with timestamps → timeline view." },
  { ext: ["vtt", "webvtt"], name: "WebVTT Subtitles", cat: "subtitle", viewer: "subtitle", mime: "text/vtt", desc: "HTML5 tracks with styling cues." },
  { ext: ["ass", "ssa", "aqt", "jss", "rt", "rsdf", "sub (text)"], name: "Advanced SubStation Alpha", cat: "subtitle", viewer: "subtitle", desc: "Styled karaoke-capable script." },
  { ext: ["sub", "idx", "sub-idx"], name: "VobSub / MicroDVD", cat: "subtitle", viewer: "fallback", desc: "Bitmap subtitles (idx info) or text timing." },
  { ext: ["lrc", "elrc", "lrc2", "smlrc"], name: "Lyrics File", cat: "subtitle", viewer: "subtitle", mime: "text/x-lrc", desc: "Time-tagged song lyrics." },
  { ext: ["ttml", "dfxp", "xml (ttml)"], name: "TTML Timed Text", cat: "subtitle", viewer: "subtitle" },
  { ext: ["sbv", "sb", "cap", "scc", "sami", "smi", "kate"], name: "Caption Format", cat: "subtitle", viewer: "subtitle" },

  // ============ CHESS / BOARD ============
  { ext: ["pgn", "chess"], name: "Portable Game Notation", cat: "other", viewer: "chess", mime: "application/x-chess-pgn", desc: "Annotated chess games with move-by-move board replay." },
  { ext: ["fen"], name: "Forsyth–Edwards Notation", cat: "other", viewer: "chess", mime: "application/x-chess-fen", desc: "Position snapshot rendered on board." },
  { ext: ["sgf"], name: "Smart Game Format", cat: "other", viewer: "chess", desc: "Go/Reversi game records." },
  { ext: ["cbv", "cbh", "cbf", "pgn.gz"], name: "ChessBase Database", cat: "other", viewer: "fallback" },

  // ============ TEXT ============
  { ext: ["txt", "text", "tx", "txx", "cc", "cnt", "asc", "ascii", "note", "notes", "list", "lst", "readme", "todo", "changelog", "chgs", "changes", "authors", "contributors", "copying", "copyright", "license", "licence", "manifest", "deps", "diz", "me", "1st", "faq", "desc", "description", "tip", "tips", "hint", "hints", "announce", "news", "history", "install", "uninstall", "maintainers", "thanks", "version"], name: "Plain Text", cat: "text", viewer: "text", mime: "text/plain", desc: "Any encoding: UTF-8/16/32, Shift-JIS, GBK, Big5, EUC, KOI8, CP-125x…" },
  { ext: ["tsv", "tab", "tab-separated"], name: "Tab-Separated Values", cat: "data", viewer: "csv", mime: "text/tab-separated-values" },
  { ext: ["url", "website", "webloc", "desktop", "urlshort"], name: "Web Shortcut", cat: "config", viewer: "code" },
  { ext: ["mdwn", "mkdn", "mkd"], name: "Markdown variant", cat: "document", viewer: "markdown" },
  { ext: ["part", "partial", "crdownload", "download", "opdownload", "partial!ff"], name: "Partial Download", cat: "binary", viewer: "fallback", desc: "In-flight download segment — inner type detected from bytes." },
  { ext: ["asc", "gpg", "sig", "b64", "p7s"], name: "Ascii Armor", cat: "code", viewer: "text", desc: "PGP signatures & base64 blocks." },
  { ext: ["strings", "str", "mo (gmo)"], name: "String Resource", cat: "text", viewer: "text" },
  { ext: ["tt", "tea", "i18n", "arb", "ftl"], name: "App Localization", cat: "text", viewer: "code" },

  // ============ OTHER / CONTAINERS ============
  { ext: ["aiff", "aif", "aifc"], name: "AIFF", cat: "audio", viewer: "audio" },
  { ext: ["dat"], name: "Generic Data File", cat: "binary", viewer: "fallback", desc: "Extension used by countless apps; content-based re-detection." },
  { ext: ["part", "filepart"], name: "Partial File", cat: "binary", viewer: "fallback" },
  { ext: ["package", "bundle", "framework", "app", "plugin", "pluginz", "kext", "widgets", "wdgt", "xpc"], name: "Bundle Directory Artifact", cat: "system", viewer: "fallback" },
  { ext: ["msix", "msixbundle", "appinstaller"], name: "MSIX Package", cat: "system", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["timezone", "tzif", "zoneinfo"], name: "Timezone Database", cat: "system", viewer: "fallback", sig: "54 5A 69 66" },
  { ext: ["ttf"], name: "TrueType", cat: "font", viewer: "font" },
  { ext: ["prisma", "dbml", "syntax"], name: "Data Schema", cat: "code", viewer: "code" },
  { ext: ["bplist", "plist-binary"], name: "Binary Property List", cat: "config", viewer: "fallback", sig: "62 70 6C 69 73 74 30 30", desc: "Apple binary plist (bplist00; detected)." },
  { ext: ["dxf"], name: "DXF Drawing", cat: "3d", viewer: "code" },
  { ext: ["search", "search-ms"], name: "Saved Search", cat: "system", viewer: "xml" },
  { ext: ["contact"], name: "Windows Contact", cat: "other", viewer: "xml" },
  { ext: ["matrix", "graffle", "kmz"], name: "Document Bundle", cat: "other", viewer: "archive" },
];
