import type { RawFormat } from "@/lib/types";

// Part B of the extended format knowledge base (subagent 2-a-1).
// All extensions are disjoint from CORE_FORMATS (database.ts) and
// EXTRA_FORMATS_A (extra-formats.ts).

export const EXTRA_FORMATS_B: RawFormat[] = [
  // ---------- Images ----------
  { ext: ["qoi"], name: "Quite OK Image", cat: "image", viewer: "image", mime: "image/x-qoi", sig: "71 6F 69 66", desc: "Lossless image format (2021)." },
  { ext: ["flif"], name: "Free Lossless Image Format", cat: "image", viewer: "fallback", mime: "image/x-flif", sig: "46 4C 49 46", desc: "Lossless animated stills." },
  { ext: ["avifs"], name: "AVIF Sequence", cat: "image", viewer: "image", mime: "image/avif-sequence", desc: "Animated AVIF." },
  { ext: ["qtif"], name: "QuickTime Image File", cat: "image", viewer: "image", mime: "image/x-quicktime", desc: "QuickTime still image." },
  { ext: ["mng"], name: "Multiple-image Network Graphics", cat: "image", viewer: "fallback", mime: "video/x-mng", sig: "8A 4D 4E 47 0D 0A 1A 0A", desc: "PNG-style animation." },
  { ext: ["jng"], name: "JPEG Network Graphics", cat: "image", viewer: "fallback", mime: "image/x-jng", sig: "8B 4A 4E 47 0D 0A 1A 0A", desc: "JPEG-in-PNG wrapper." },
  { ext: ["jxr", "wdp", "hdp"], name: "JPEG XR / HD Photo", cat: "image", viewer: "fallback", mime: "image/jxr", sig: "49 49 BC", desc: "Microsoft JPEG XR." },
  { ext: ["jpc", "j2c"], name: "JPEG 2000 Codestream", cat: "image", viewer: "fallback", desc: "Raw J2K codestream." },
  { ext: ["ktx", "ktx2"], name: "Khronos Texture", cat: "image", viewer: "fallback", mime: "image/ktx", sig: "AB 4B 54 58 20 ?? ?? BB 0D 0A 1A 0A", desc: "GPU texture container." },
  { ext: ["astc"], name: "ASTC Compressed Texture", cat: "image", viewer: "fallback", sig: "13 AB A1 5C", desc: "Adaptive scalable texture." },
  { ext: ["pkm"], name: "ETC Compressed Texture (PKM)", cat: "image", viewer: "fallback", sig: "50 4B 4D 20", desc: "Ericsson texture container." },
  { ext: ["pvr"], name: "PowerVR Texture", cat: "image", viewer: "fallback", desc: "Imagination GPU texture." },
  { ext: ["basis"], name: "Basis Universal Texture", cat: "image", viewer: "fallback", desc: "Supercompressed GPU texture." },
  { ext: ["blp"], name: "Blizzard Texture", cat: "image", viewer: "fallback", desc: "Warcraft texture format." },
  { ext: ["aseprite"], name: "Aseprite Sprite", cat: "image", viewer: "fallback", desc: "Animated pixel-art file." },
  { ext: ["ilbm"], name: "IFF ILBM Bitmap", cat: "image", viewer: "fallback", sig: "46 4F 52 4D ?? ?? ?? ?? 49 4C 42 4D", desc: "Amiga interleaved bitmap." },
  { ext: ["sgi", "rgb", "rgba", "bw", "int", "inta"], name: "Silicon Graphics Image", cat: "image", viewer: "image", mime: "image/sgi", sig: "01 DA", desc: "SGI raster format." },
  { ext: ["rla"], name: "Wavefront RLA Image", cat: "image", viewer: "fallback", desc: "Rendered image with channels." },
  { ext: ["pxr"], name: "Pixar Picture", cat: "image", viewer: "fallback", desc: "Pixar raster format." },
  { ext: ["dcx"], name: "Multi-Page PCX", cat: "image", viewer: "fallback", sig: "B1 68 DE 3A", desc: "ZSoft multi-page image." },
  { ext: ["djvu", "djv"], name: "DjVu Document", cat: "image", viewer: "fallback", mime: "image/vnd.djvu", sig: "41 54 26 54 46 4F 52 4D", desc: "Scanned-document format." },
  { ext: ["viff"], name: "Khoros VIFF Image", cat: "image", viewer: "fallback", desc: "Visualization image format." },
  { ext: ["xbm"], name: "X Bitmap", cat: "image", viewer: "code", mime: "image/x-xbitmap", desc: "C-source bitmap." },
  { ext: ["sct"], name: "Scitex Continuous Tone", cat: "image", viewer: "fallback", desc: "Prepress raster format." },
  { ext: ["cal", "cals"], name: "CALS Raster", cat: "image", viewer: "fallback", desc: "Government document raster." },
  { ext: ["orf"], name: "Olympus RAW", cat: "image", viewer: "image", desc: "Olympus camera raw." },
  { ext: ["fff"], name: "Hasselblad RAW", cat: "image", viewer: "image", desc: "Hasselblad/Imacon raw." },
  { ext: ["rwl"], name: "Leica RAW", cat: "image", viewer: "image", desc: "Leica/Panasonic raw." },
  { ext: ["srw"], name: "Samsung RAW", cat: "image", viewer: "image", desc: "Samsung camera raw." },
  { ext: ["k25"], name: "Kodak RAW (K25)", cat: "image", viewer: "image", desc: "Kodak DC25 raw." },
  { ext: ["mrw"], name: "Minolta RAW", cat: "image", viewer: "image", desc: "Minolta camera raw." },
  { ext: ["gpr"], name: "GoPro RAW", cat: "image", viewer: "image", desc: "GoPro DNG-based raw." },
  { ext: ["ari"], name: "ARRIRAW", cat: "image", viewer: "fallback", desc: "Arri digital camera raw." },
  { ext: ["cos"], name: "Capture One Image", cat: "image", viewer: "fallback", desc: "Phase One raw." },
  { ext: ["thm"], name: "Thumbnail Image", cat: "image", viewer: "image", desc: "Camera/camcorder JPEG thumb." },
  { ext: ["abr"], name: "Photoshop Brush", cat: "image", viewer: "fallback", desc: "Adobe brush presets." },
  { ext: ["atn"], name: "Photoshop Action", cat: "image", viewer: "fallback", desc: "Adobe automation steps." },
  { ext: ["cdr", "cdt"], name: "CorelDRAW Drawing", cat: "image", viewer: "fallback", desc: "Corel vector document." },
  { ext: ["cmx"], name: "Corel Presentation Exchange", cat: "image", viewer: "fallback", desc: "Corel interchange vector." },
  { ext: ["cpt"], name: "Corel PHOTO-PAINT Image", cat: "image", viewer: "fallback", desc: "Corel raster editor file." },
  { ext: ["wpg"], name: "WordPerfect Graphic", cat: "image", viewer: "fallback", desc: "WP office vector format." },
  { ext: ["drw"], name: "Micrografx Designer Drawing", cat: "image", viewer: "fallback", desc: "Legacy vector drawing." },
  { ext: ["gpl"], name: "GIMP Palette", cat: "image", viewer: "text", desc: "Text color palette." },
  { ext: ["sketch"], name: "Sketch Drawing", cat: "image", viewer: "fallback", desc: "Sketch app design (zip)." },
  { ext: ["xd"], name: "Adobe XD Design", cat: "image", viewer: "fallback", desc: "UI/UX design document." },
  { ext: ["sxd"], name: "OpenOffice 1.x Draw", cat: "image", viewer: "fallback", desc: "StarOffice vector drawing." },
  { ext: ["odg", "otg"], name: "OpenDocument Drawing", cat: "image", viewer: "fallback", mime: "application/vnd.oasis.opendocument.graphics", desc: "ODF vector drawing." },
  { ext: ["odi", "oti"], name: "OpenDocument Image", cat: "image", viewer: "fallback", desc: "ODF embedded image." },
  { ext: ["odc"], name: "OpenDocument Chart", cat: "spreadsheet", viewer: "fallback", desc: "ODF chart part." },
  { ext: ["oth"], name: "OpenDocument Web Template", cat: "document", viewer: "fallback", desc: "ODF HTML template." },

  // ---------- Audio ----------
  { ext: ["voc"], name: "Creative Voice File", cat: "audio", viewer: "audio", mime: "audio/x-voc", sig: "43 72 65 61 74 69 76 65 20 56 6F 69 63 65 1A 1A", desc: "Sound Blaster voice audio." },
  { ext: ["ra"], name: "RealAudio", cat: "audio", viewer: "audio", mime: "audio/x-pn-realaudio", sig: "2E 72 61 FD", desc: "RealNetworks stream audio." },
  { ext: ["vqf"], name: "TwinVQ Audio", cat: "audio", viewer: "fallback", mime: "audio/x-twinvq", desc: "NTT transform codec." },
  { ext: ["tak"], name: "TAK Lossless Audio", cat: "audio", viewer: "fallback", desc: "Tom's Audio Kompressor." },
  { ext: ["wve"], name: "Psion Wave Audio", cat: "audio", viewer: "fallback", desc: "Psion PDA recording." },
  { ext: ["cda"], name: "CD Audio Shortcut", cat: "audio", viewer: "fallback", desc: "CD track pointer." },
  { ext: ["cdda"], name: "CD Digital Audio", cat: "audio", viewer: "audio", mime: "audio/x-cdda", desc: "Raw Red Book PCM." },
  { ext: ["pcm"], name: "Raw PCM Audio", cat: "audio", viewer: "audio", desc: "Headerless samples." },
  { ext: ["ec3"], name: "Dolby Digital Plus", cat: "audio", viewer: "audio", desc: "E-AC-3 elementary stream." },
  { ext: ["aa3"], name: "ATRAC3 Audio", cat: "audio", viewer: "fallback", desc: "Sony ATRAC3 codec." },
  { ext: ["swa"], name: "Shockwave Audio", cat: "audio", viewer: "fallback", desc: "Macromedia compressed audio." },
  { ext: ["sfark"], name: "sfArk SoundFont", cat: "audio", viewer: "fallback", desc: "Compressed SoundFont." },
  { ext: ["krz"], name: "Kurzweil Sample", cat: "audio", viewer: "fallback", desc: "Kurzweil K2000 sample." },
  { ext: ["syx"], name: "MIDI System Exclusive", cat: "audio", viewer: "midi", desc: "Raw SysEx dump." },
  { ext: ["cmf"], name: "Creative Music File", cat: "audio", viewer: "midi", desc: "Sound Blaster FM music." },
  { ext: ["kss"], name: "MSX Sound Format", cat: "audio", viewer: "midi", desc: "MSX chip music." },
  { ext: ["gsf"], name: "Game Boy Advance Sound", cat: "audio", viewer: "midi", desc: "GBA chiptune rip." },
  { ext: ["2sf"], name: "Nintendo DS Sound", cat: "audio", viewer: "midi", desc: "NDS chiptune rip." },
  { ext: ["ssf"], name: "Sega Saturn Sound", cat: "audio", viewer: "midi", desc: "Saturn chiptune rip." },
  { ext: ["rsn"], name: "RAR SPC Set", cat: "audio", viewer: "fallback", desc: "Archived SNES music." },
  { ext: ["hvl"], name: "Hively Tracker Module", cat: "audio", viewer: "midi", desc: "Amiga AHX successor." },
  { ext: ["ahx"], name: "CRI AHX Audio", cat: "audio", viewer: "fallback", desc: "CRI MPEG-derived audio." },
  { ext: ["sc68"], name: "Atari ST Music (SC68)", cat: "audio", viewer: "midi", desc: "Atari STE music rip." },
  { ext: ["ym"], name: "Atari YM Music", cat: "audio", viewer: "midi", desc: "YM2149 chip dump." },
  { ext: ["sap"], name: "Atari SAP Music", cat: "audio", viewer: "midi", desc: "Pokey chip music." },
  { ext: ["sndh"], name: "Atari SNDH Music", cat: "audio", viewer: "midi", desc: "Atari chip tunes." },
  { ext: ["v2m"], name: "V2 Synth Module", cat: "audio", viewer: "midi", desc: "Farbrausch chiptune." },
  { ext: ["ftm"], name: "FamiTracker Module", cat: "audio", viewer: "midi", desc: "NES tracker song." },
  { ext: ["mptm"], name: "OpenMPT Extended Module", cat: "audio", viewer: "midi", desc: "OpenMPT native song." },
  { ext: ["xi"], name: "FastTracker II Instrument", cat: "audio", viewer: "fallback", desc: "XM instrument." },
  { ext: ["iti"], name: "Impulse Tracker Instrument", cat: "audio", viewer: "fallback", desc: "IT instrument." },
  { ext: ["its"], name: "Impulse Tracker Sample", cat: "audio", viewer: "fallback", desc: "Compressed IT sample." },
  { ext: ["sng"], name: "Tracker Song (SNG)", cat: "audio", viewer: "midi", desc: "Generic tracker song." },
  { ext: ["8svx"], name: "Amiga 8SVX Audio", cat: "audio", viewer: "fallback", sig: "46 4F 52 4D ?? ?? ?? ?? 38 53 56 58", desc: "IFF 8-bit sampled voice." },
  { ext: ["brr"], name: "SNES BRR Sample", cat: "audio", viewer: "fallback", desc: "S-DSP compressed sample." },
  { ext: ["aud"], name: "Westwood Audio", cat: "audio", viewer: "fallback", desc: "Westwood games audio." },
  { ext: ["adp"], name: "GameCube ADP Audio", cat: "audio", viewer: "fallback", desc: "GC DSP audio track." },
  { ext: ["adx"], name: "CRI ADX Audio", cat: "audio", viewer: "fallback", desc: "Sega/cri ADPCM audio." },
  { ext: ["hca"], name: "CRI HCA Audio", cat: "audio", viewer: "fallback", desc: "CRI high-compress audio." },
  { ext: ["aix"], name: "CRI AIX Audio", cat: "audio", viewer: "fallback", desc: "CRI interleaved stream." },
  { ext: ["acb"], name: "CRI ACB Cue Sheet", cat: "audio", viewer: "fallback", desc: "CRI cue metadata." },
  { ext: ["cdg"], name: "CD+G Karaoke", cat: "audio", viewer: "fallback", desc: "Graphics subcode data." },
  { ext: ["nki", "nkm"], name: "Kontakt Instrument", cat: "audio", viewer: "fallback", desc: "Native Instruments sampler." },
  { ext: ["fxb", "fxp"], name: "VST Preset", cat: "audio", viewer: "fallback", desc: "Steinberg plugin bank." },
  { ext: ["sunvox"], name: "SunVox Project", cat: "audio", viewer: "fallback", desc: "Modular tracker project." },
  { ext: ["ptf"], name: "Pro Tools Session", cat: "audio", viewer: "fallback", desc: "Avid session file." },
  { ext: ["omf"], name: "Open Media Framework", cat: "audio", viewer: "fallback", desc: "Avid interchange media." },
  { ext: ["gp3", "gp4", "gp5"], name: "Guitar Pro Tab", cat: "audio", viewer: "fallback", desc: "Tablature document." },
  { ext: ["mscz", "mscx"], name: "MuseScore Score", cat: "audio", viewer: "fallback", desc: "Open notation editor." },
  { ext: ["sib"], name: "Sibelius Score", cat: "audio", viewer: "fallback", desc: "Sibelius notation." },
  { ext: ["musx"], name: "Finale Score", cat: "audio", viewer: "fallback", desc: "MakeMusic Finale doc." },
  { ext: ["etf"], name: "Finale ETF", cat: "audio", viewer: "text", desc: "Enigma transport file." },
  { ext: ["nwc"], name: "NoteWorthy Composer File", cat: "audio", viewer: "fallback", desc: "Windows notation song." },
  { ext: ["ove"], name: "Overture Score", cat: "audio", viewer: "fallback", desc: "Overture notation." },
  { ext: ["ptb"], name: "Power Tab", cat: "audio", viewer: "fallback", desc: "Guitar tablature." },
  { ext: ["tef"], name: "TablEdit Tab", cat: "audio", viewer: "fallback", desc: "Multi-instrument tab." },
  { ext: ["krn"], name: "Humdrum Kern Score", cat: "audio", viewer: "text", desc: "Text music notation." },
  { ext: ["cho", "chopro"], name: "ChordPro", cat: "audio", viewer: "text", desc: "Lyrics with chords." },
  { ext: ["alda"], name: "Alda Score", cat: "audio", viewer: "text", desc: "Text music language." },
  { ext: ["csd"], name: "Csound Document", cat: "code", viewer: "code", desc: "Unified csound file." },
  { ext: ["sco"], name: "Csound Score File", cat: "code", viewer: "code", desc: "Csound DSP score." },
  { ext: ["scl", "kbm"], name: "Scala Scale / Keyboard Map", cat: "audio", viewer: "text", desc: "Microtuning definitions." },
  { ext: ["tun"], name: "AnaMark Tuning", cat: "audio", viewer: "text", desc: "Scale tuning file." },
  { ext: ["f4a"], name: "Adobe HTTP Streaming Audio", cat: "audio", viewer: "fallback", desc: "F4A audio fragment." },
  { ext: ["fsb"], name: "FMOD Sound Bank", cat: "game", viewer: "fallback", sig: "46 53 42", desc: "FMOD audio container." },
  { ext: ["fev"], name: "FMOD Event Data", cat: "game", viewer: "fallback", desc: "FMOD event metadata." },
  { ext: ["bnk"], name: "Wwise SoundBank", cat: "game", viewer: "fallback", sig: "42 4B 48 44", desc: "Audiokinetic bank." },
  { ext: ["wem"], name: "Wwise Encoded Media", cat: "game", viewer: "fallback", desc: "Wwise audio asset." },
  { ext: ["waa", "wac", "wam", "waj", "was"], name: "Wwise Bank (typed)", cat: "game", viewer: "fallback", desc: "Wwise per-type bank." },
  { ext: ["xwb", "xsb", "xgs"], name: "XACT Audio Bank", cat: "game", viewer: "fallback", desc: "Microsoft cross-platform audio." },
  { ext: ["dsp"], name: "Nintendo DSP ADPCM", cat: "game", viewer: "fallback", desc: "GC/Wii DSP headers." },
  { ext: ["ast"], name: "Nintendo AST Audio", cat: "game", viewer: "fallback", desc: "GameCube stream audio." },
  { ext: ["brstm"], name: "Nintendo BRSTM Stream", cat: "game", viewer: "fallback", sig: "52 53 54 4D", desc: "Wii/GameCube music." },
  { ext: ["bcstm"], name: "3DS BCSTM Stream", cat: "game", viewer: "fallback", sig: "43 53 54 4D", desc: "3DS music stream." },
  { ext: ["bwav"], name: "Wii U BWAV Stream", cat: "game", viewer: "fallback", desc: "Wii U music stream." },
  { ext: ["brsar"], name: "Wii Sound Archive", cat: "game", viewer: "fallback", desc: "Wii system sounds." },
  { ext: ["scd"], name: "Square Enix Sound Container", cat: "game", viewer: "fallback", desc: "FF/XIV audio archive." },

  // ---------- Video ----------
  { ext: ["braw"], name: "Blackmagic RAW", cat: "video", viewer: "fallback", desc: "BRAW camera footage." },
  { ext: ["r3d"], name: "RED RAW Video", cat: "video", viewer: "fallback", desc: "RED camera footage." },
  { ext: ["gxf"], name: "SMPTE General Exchange Format", cat: "video", viewer: "fallback", desc: "Broadcast interchange." },
  { ext: ["aaf"], name: "Advanced Authoring Format", cat: "video", viewer: "fallback", desc: "Pro editing interchange." },
  { ext: ["edl"], name: "Edit Decision List", cat: "video", viewer: "text", desc: "CMX/Grass Valley EDL." },
  { ext: ["ale"], name: "Avid Log Exchange", cat: "video", viewer: "text", desc: "Avid tabbed log." },
  { ext: ["vro"], name: "DVD Video Recording", cat: "video", viewer: "fallback", desc: "DVD VR camcorder title." },
  { ext: ["m4s"], name: "DASH Segment", cat: "video", viewer: "fallback", desc: "fMP4 media segment." },
  { ext: ["mj2", "mjp2"], name: "Motion JPEG 2000", cat: "video", viewer: "fallback", desc: "MJ2 frame sequence." },
  { ext: ["y4m"], name: "YUV4MPEG2 Raw Video", cat: "video", viewer: "video", sig: "59 55 56 34 6D 70 65 67 32", desc: "Uncompressed pipe format." },
  { ext: ["yuv"], name: "Raw YUV Planes", cat: "video", viewer: "fallback", desc: "Headerless YUV frames." },
  { ext: ["nut"], name: "NUT Multimedia Container", cat: "video", viewer: "fallback", desc: "FFmpeg experimental mux." },
  { ext: ["mjpg", "mjpeg"], name: "Motion JPEG Stream", cat: "video", viewer: "video", desc: "MJPEG frame stream." },
  { ext: ["avs"], name: "AviSynth Script", cat: "video", viewer: "code", desc: "Frameserver script." },
  { ext: ["vpy"], name: "VapourSynth Script", cat: "video", viewer: "code", desc: "Python frameserver." },
  { ext: ["kdenlive"], name: "Kdenlive Project", cat: "video", viewer: "xml", desc: "KDE video editor MLT." },
  { ext: ["mlt"], name: "MLT Video Project", cat: "video", viewer: "xml", desc: "Media Lovin Toolkit." },
  { ext: ["veg"], name: "Vegas Project", cat: "video", viewer: "fallback", desc: "Magix/Sony Vegas edit." },
  { ext: ["prproj"], name: "Premiere Pro Project", cat: "video", viewer: "fallback", desc: "Adobe NLE project." },
  { ext: ["aep"], name: "After Effects Project", cat: "video", viewer: "fallback", desc: "Adobe motion project." },
  { ext: ["fcpxml"], name: "Final Cut Pro XML", cat: "video", viewer: "xml", desc: "FCP interchange XML." },
  { ext: ["drp"], name: "DaVinci Resolve Project", cat: "video", viewer: "fallback", desc: "Resolve editorial DB." },
  { ext: ["vc1"], name: "VC-1 Elementary Stream", cat: "video", viewer: "fallback", desc: "SMPTE 421M video." },
  { ext: ["rv"], name: "RealVideo", cat: "video", viewer: "fallback", desc: "RealNetworks video." },
  { ext: ["usm"], name: "CRI USM Video", cat: "video", viewer: "fallback", desc: "Sofdec 2 movie." },
  { ext: ["bink"], name: "Bink Video", cat: "video", viewer: "fallback", desc: "RAD Game Tools video." },
  { ext: ["smk"], name: "Smacker Video", cat: "video", viewer: "fallback", sig: "53 4D 4B 32", desc: "RAD old-school video." },
  { ext: ["thp"], name: "Wii THP Video", cat: "video", viewer: "fallback", desc: "Nintendo FMV format." },
  { ext: ["vqa"], name: "Westwood VQA Video", cat: "video", viewer: "fallback", desc: "Westwood games FMV." },
  { ext: ["cdxl"], name: "Amiga CDXL Video", cat: "video", viewer: "fallback", desc: "CD32 full-motion video." },
  { ext: ["anim"], name: "IFF ANIM Animation", cat: "video", viewer: "fallback", sig: "46 4F 52 4D ?? ?? ?? ?? 41 4E 49 4D", desc: "Amiga animation." },
  { ext: ["dav"], name: "Dahua DVR Video", cat: "video", viewer: "fallback", desc: "CCTV surveillance." },
  { ext: ["vp6"], name: "VP6 Video", cat: "video", viewer: "fallback", desc: "On2 codec (FLV era)." },
  { ext: ["tp"], name: "MPEG Transport (TP)", cat: "video", viewer: "video", desc: "HDV broadcast stream." },
  { ext: ["ism", "ismv", "isma", "ismc"], name: "Smooth Streaming File", cat: "video", viewer: "fallback", desc: "IIS adaptive streaming." },
  { ext: ["mpd"], name: "MPEG-DASH Manifest", cat: "video", viewer: "xml", desc: "Adaptive streaming index." },
  { ext: ["ifo"], name: "DVD IFO File", cat: "video", viewer: "fallback", desc: "DVD navigation data." },
  { ext: ["clpi", "mpls"], name: "Blu-ray Clip/Playlist", cat: "video", viewer: "fallback", desc: "BD structure files." },
  { ext: ["bdmv"], name: "Blu-ray Movie", cat: "video", viewer: "fallback", desc: "BD index data." },

  // ---------- Fonts ----------
  { ext: ["pfr"], name: "Bitstream TrueDoc Font", cat: "font", viewer: "font", desc: "Portable font resource." },
  { ext: ["glyphs"], name: "Glyphs Font Source", cat: "font", viewer: "text", desc: "Glyphs app source." },
  { ext: ["glyphspackage"], name: "Glyphs Package", cat: "font", viewer: "fallback", desc: "Glyphs bundled project." },
  { ext: ["vfb"], name: "FontLab Font", cat: "font", viewer: "fallback", desc: "FontLab workshop file." },
  { ext: ["mf"], name: "METAFONT Source", cat: "font", viewer: "code", desc: "Knuth font programs." },
  { ext: ["fea"], name: "AFDKO Feature File", cat: "font", viewer: "code", desc: "OpenType feature source." },
  { ext: ["gf"], name: "TeX Generic Font", cat: "font", viewer: "fallback", desc: "METAFONT output bitmap." },
  { ext: ["pk"], name: "TeX Packed Bitmap Font", cat: "font", viewer: "fallback", desc: "Packed GF font." },
  { ext: ["tfm"], name: "TeX Font Metrics", cat: "font", viewer: "fallback", desc: "TFM metrics data." },
  { ext: ["vf"], name: "TeX Virtual Font", cat: "font", viewer: "fallback", desc: "Virtual font reference." },
  { ext: ["ofm"], name: "Omega Font Metrics", cat: "font", viewer: "fallback", desc: "Extended TFM." },
  { ext: ["fond"], name: "Mac FOND Resource", cat: "font", viewer: "fallback", desc: "Classic font family data." },
  { ext: ["suit"], name: "Mac Font Suitcase", cat: "font", viewer: "fallback", desc: "Classic Mac font container." },
  { ext: ["otc"], name: "OpenType Collection", cat: "font", viewer: "font", mime: "font/collection", desc: "Multi-face OTF." },

  // ---------- Archives & packages ----------
  { ext: ["arj"], name: "ARJ Archive", cat: "archive", viewer: "archive", mime: "application/x-arj", sig: "60 EA", desc: "DOS-era archiver." },
  { ext: ["ha"], name: "HA Archive", cat: "archive", viewer: "fallback", desc: "HA file archiver." },
  { ext: ["pma"], name: "PMarc Archive", cat: "archive", viewer: "fallback", desc: "Japanese PMarc packer." },
  { ext: ["lzx"], name: "LZX Archive", cat: "archive", viewer: "fallback", sig: "4C 5A 58", desc: "Amiga archiver." },
  { ext: ["mou"], name: "WinMount Compressed", cat: "archive", viewer: "fallback", desc: "MOU compressed disk." },
  { ext: ["shar"], name: "Shell Archive", cat: "archive", viewer: "text", desc: "Self-extracting script." },
  { ext: ["tlz"], name: "LZMA Tarball", cat: "archive", viewer: "archive", desc: "tar + lzip family." },
  { ext: ["tzo"], name: "LZO Tarball", cat: "archive", viewer: "archive", desc: "tar + lzip." },
  { ext: ["tzst"], name: "Zstd Tarball", cat: "archive", viewer: "archive", desc: "tar + zstd." },
  { ext: ["sqfs", "sfs"], name: "SquashFS Image", cat: "archive", viewer: "fallback", sig: "68 73 71 73", desc: "Compressed FS image." },
  { ext: ["pax"], name: "PAX Archive", cat: "archive", viewer: "archive", desc: "POSIX tar extension." },
  { ext: ["dar"], name: "Disk ARchive", cat: "archive", viewer: "fallback", desc: "DAR backup format." },
  { ext: ["aar"], name: "Android AAR Library", cat: "archive", viewer: "archive", desc: "Android repository bundle." },
  { ext: ["asar"], name: "Electron Archive", cat: "archive", viewer: "fallback", desc: "Chromium app packaging." },
  { ext: ["gem"], name: "Ruby Gem Package", cat: "archive", viewer: "archive", desc: "RubyGems tarball." },
  { ext: ["pet"], name: "Puppy Linux Package", cat: "archive", viewer: "archive", desc: "Puppy pet package." },
  { ext: ["ipk"], name: "Itsypkg (IPK)", cat: "archive", viewer: "archive", desc: "Embedded package." },
  { ext: ["box"], name: "Vagrant Box", cat: "archive", viewer: "archive", desc: "Packaged VM image." },
  { ext: ["phar"], name: "PHP Archive", cat: "archive", viewer: "archive", desc: "PHP executable archive." },
  { ext: ["hpkg"], name: "Haiku Package", cat: "archive", viewer: "fallback", desc: "Haiku OS package." },
  { ext: ["bar"], name: "BlackBerry 10 Package", cat: "archive", viewer: "fallback", desc: "BB10 app package." },
  { ext: ["br"], name: "Brotli Data", cat: "archive", viewer: "fallback", mime: "application/br", desc: "Compressed stream." },
  { ext: ["sis", "sisx"], name: "Symbian Package", cat: "archive", viewer: "fallback", desc: "Symbian installer." },
  { ext: ["jad"], name: "J2ME Descriptor", cat: "config", viewer: "text", desc: "MIDlet manifest." },
  { ext: ["zim"], name: "Kiwix ZIM", cat: "archive", viewer: "fallback", desc: "Offline wiki content." },
  { ext: ["xp3"], name: "KiriKiri XP3 Archive", cat: "game", viewer: "fallback", sig: "58 50 33", desc: "VN engine package." },
  { ext: ["nsa", "ns2"], name: "NScripter Archive", cat: "game", viewer: "fallback", desc: "VN engine package." },
  { ext: ["mpq"], name: "Blizzard MPQ Archive", cat: "game", viewer: "fallback", desc: "Blizzard game data." },
  { ext: ["bsa", "ba2"], name: "Bethesda Archive", cat: "game", viewer: "fallback", desc: "Elder Scrolls package." },
  { ext: ["esp", "esm"], name: "Elder Scrolls Plugin", cat: "game", viewer: "fallback", desc: "Game plugin/master." },
  { ext: ["rpf"], name: "GTA RPF Archive", cat: "game", viewer: "fallback", desc: "Rockstar package." },
  { ext: ["gob"], name: "LucasArts GOB Archive", cat: "game", viewer: "fallback", desc: "Star Wars game data." },
  { ext: ["lab"], name: "LucasArts LAB Archive", cat: "game", viewer: "fallback", desc: "LucasArts bundle." },
  { ext: ["big", "viv"], name: "EA BIG/VIV Archive", cat: "game", viewer: "fallback", desc: "Electronic Arts bundle." },
  { ext: ["crf"], name: "Dark Engine CRF Archive", cat: "game", viewer: "fallback", desc: "Thief/System Shock." },
  { ext: ["hak"], name: "NWN Hak Pack", cat: "game", viewer: "fallback", desc: "Neverwinter Nights data." },
  { ext: ["ttarch"], name: "Telltale Archive", cat: "game", viewer: "fallback", desc: "Telltale game bundle." },
  { ext: ["bdt", "bhd"], name: "Dark Souls Archive", cat: "game", viewer: "fallback", desc: "FromSoftware data." },
  { ext: ["rpak"], name: "Respawn RPak", cat: "game", viewer: "fallback", desc: "Apex asset package." },
  { ext: ["pac"], name: "Namco PAC Archive", cat: "game", viewer: "fallback", desc: "Arcade asset bundle." },
  { ext: ["grp"], name: "Duke Nukem 3D GRP", cat: "game", viewer: "fallback", desc: "Build engine bundle." },
  { ext: ["psarc"], name: "PlayStation PSARC", cat: "game", viewer: "fallback", sig: "50 53 41 52", desc: "PS3/PS4 archive." },
  { ext: ["yaz0"], name: "Yaz0 Compressed Data", cat: "game", viewer: "fallback", sig: "59 61 7A 30", desc: "Nintendo LZ container." },
  { ext: ["szs"], name: "Wii SZS Archive", cat: "game", viewer: "fallback", sig: "59 61 7A 30", desc: "Yaz0 game package." },
  { ext: ["gho", "ghs"], name: "Norton Ghost Image", cat: "disk", viewer: "archive", desc: "Ghost disk backup." },
  { ext: ["v2i"], name: "Symantec Ghost Image", cat: "disk", viewer: "archive", desc: "Drive snapshot." },
  { ext: ["tib", "tibk"], name: "Acronis True Image", cat: "disk", viewer: "archive", desc: "Acronis disk backup." },
  { ext: ["mrimg"], name: "Macrium Reflect Image", cat: "disk", viewer: "archive", desc: "Macrium disk image." },
  { ext: ["adi"], name: "Active@ Disk Image", cat: "disk", viewer: "archive", desc: "Backup archive." },
  { ext: ["bkf"], name: "Windows NTBackup File", cat: "system", viewer: "fallback", desc: "NTBackup archive." },
  { ext: ["qic"], name: "QIC Backup", cat: "system", viewer: "fallback", desc: "Tape backup file." },
  { ext: ["vbk"], name: "Veeam Backup", cat: "archive", viewer: "fallback", desc: "Veeam VM backup." },

  // ---------- Disk & forensic images ----------
  { ext: ["dd"], name: "Raw Disk Image", cat: "disk", viewer: "archive", desc: "Byte-for-byte dump." },
  { ext: ["adf"], name: "Amiga Disk File", cat: "disk", viewer: "archive", sig: "44 4F 53 00", desc: "Amiga floppy image." },
  { ext: ["stx"], name: "Pasti Atari ST Image", cat: "disk", viewer: "archive", desc: "Copy-accurate ST disk." },
  { ext: ["trd"], name: "TR-DOS Disk Image", cat: "disk", viewer: "archive", desc: "ZX Spectrum disk." },
  { ext: ["ssd", "dsd"], name: "BBC DFS Disk Image", cat: "disk", viewer: "archive", desc: "BBC Micro floppy." },
  { ext: ["uef"], name: "Unified Emulator Format", cat: "disk", viewer: "archive", desc: "Tape/disk container." },
  { ext: ["atr", "atx"], name: "Atari 8-bit Disk Image", cat: "disk", viewer: "archive", desc: "SIO disk image." },
  { ext: ["cas"], name: "Cassette Image", cat: "disk", viewer: "archive", desc: "MSX/Atari tape file." },
  { ext: ["2mg"], name: "Apple IIgs Disk Image", cat: "disk", viewer: "archive", desc: "Apple II 2mg image." },
  { ext: ["woz"], name: "Apple II WOZ Image", cat: "disk", viewer: "archive", sig: "57 4F 5A", desc: "Preserved II floppy." },
  { ext: ["fdi"], name: "FDI Floppy Image", cat: "disk", viewer: "archive", desc: "Universal floppy image." },
  { ext: ["cloop"], name: "Compressed Loop Device", cat: "disk", viewer: "archive", desc: "Knoppix cloop image." },
  { ext: ["tc"], name: "TrueCrypt Volume", cat: "disk", viewer: "fallback", desc: "Encrypted container." },
  { ext: ["hc"], name: "VeraCrypt Container", cat: "disk", viewer: "fallback", desc: "Encrypted container." },
  { ext: ["sparseimage"], name: "Apple Sparse Disk Image", cat: "disk", viewer: "fallback", desc: "Expandable image." },
  { ext: ["e01", "ex01"], name: "EnCase Evidence File", cat: "disk", viewer: "fallback", sig: "45 56 46 09 0D 0A FF 00", desc: "Forensic disk image." },
  { ext: ["l01", "lx01"], name: "EnCase Logical Evidence", cat: "disk", viewer: "fallback", desc: "Logical file evidence." },
  { ext: ["s01"], name: "SMART Evidence File", cat: "disk", viewer: "fallback", desc: "ASR Data image." },
  { ext: ["ad1"], name: "AccessData FTK Image", cat: "disk", viewer: "fallback", desc: "FTK custom image." },
  { ext: ["scap"], name: "UEFI Firmware Capsule", cat: "system", viewer: "fallback", desc: "BIOS update capsule." },

  // ---------- System / OS / forensics ----------
  { ext: ["ds_store"], name: "macOS .DS_Store", cat: "system", viewer: "fallback", sig: "00 00 00 01 42 75 64 64 79", desc: "Finder metadata." },
  { ext: ["journal"], name: "systemd Journal", cat: "system", viewer: "fallback", sig: "4C 50 4B 53 48 48 52 48", desc: "Binary journal log." },
  { ext: ["crash"], name: "Apple Crash Report", cat: "system", viewer: "text", desc: "Crash log bundle." },
  { ext: ["dtb", "dtbo"], name: "Device Tree Blob", cat: "system", viewer: "fallback", sig: "D0 0D FE ED", desc: "Compiled FDT." },
  { ext: ["dtsi"], name: "Device Tree Include", cat: "code", viewer: "code", desc: "Device tree source." },
  { ext: ["uimg"], name: "U-Boot Image", cat: "system", viewer: "fallback", sig: "27 05 19 56", desc: "Bootable legacy image." },
  { ext: ["uf2"], name: "UF2 Firmware", cat: "system", viewer: "fallback", sig: "55 46 32 0A", desc: "USB flashing format." },
  { ext: ["nbh"], name: "HTC ROM Header", cat: "system", viewer: "fallback", desc: "Windows Mobile flasher." },
  { ext: ["rbf"], name: "Raw FPGA Bitstream", cat: "system", viewer: "fallback", desc: "Cyclone raw binary." },
  { ext: ["bit"], name: "Xilinx FPGA Bitstream", cat: "system", viewer: "fallback", desc: "Vivado/ISE bitfile." },
  { ext: ["mcs"], name: "FPGA PROM Image", cat: "system", viewer: "fallback", desc: "Intel HEX program data." },
  { ext: ["svf"], name: "JTAG SVF Vector", cat: "system", viewer: "text", desc: "Serial vector format." },
  { ext: ["jed"], name: "JEDEC Fuse Map", cat: "other", viewer: "text", desc: "PLD programmer data." },
  { ext: ["dex"], name: "Android DEX Bytecode", cat: "system", viewer: "fallback", sig: "64 65 78 0A ?? ?? ?? 00", desc: "Dalvik executable." },
  { ext: ["vdex"], name: "Android VDEX", cat: "system", viewer: "fallback", sig: "76 64 65 78", desc: "Verified dex cache." },
  { ext: ["arsc"], name: "Android Compiled Resources", cat: "system", viewer: "fallback", desc: "Binary resource table." },
  { ext: ["smali"], name: "Smali Assembly", cat: "code", viewer: "code", desc: "Dalvik disassembly." },
  { ext: ["aidl"], name: "Android IDL", cat: "code", viewer: "code", desc: "Binder interface def." },
  { ext: ["tlb"], name: "COM Type Library", cat: "system", viewer: "fallback", desc: "OLE automation types." },
  { ext: ["olb"], name: "Object Library", cat: "system", viewer: "fallback", desc: "VBA/COM type library." },
  { ext: ["rc", "rc2"], name: "Windows Resource Script", cat: "code", viewer: "code", desc: "Resource compiler source." },
  { ext: ["idb"], name: "IDA Database", cat: "binary", viewer: "fallback", desc: "IDA/MSVC database." },
  { ext: ["i64"], name: "IDA 64-bit Database", cat: "binary", viewer: "fallback", desc: "IDA Pro database." },
  { ext: ["hprof"], name: "Java Heap Dump", cat: "system", viewer: "fallback", desc: "JVM HPROF snapshot." },
  { ext: ["evt"], name: "NT Event Log (Legacy)", cat: "system", viewer: "fallback", desc: "Pre-Vista event log." },
  { ext: ["cat"], name: "Windows Security Catalog", cat: "system", viewer: "fallback", desc: "Signed file catalog." },
  { ext: ["pol"], name: "Group Policy Registry", cat: "system", viewer: "fallback", desc: "Registry policy file." },
  { ext: ["spl", "shd"], name: "Windows Print Spool File", cat: "system", viewer: "fallback", desc: "Spool and shadow data." },
  { ext: ["admx", "adml"], name: "Group Policy Template", cat: "config", viewer: "xml", desc: "Administrative template." },
  { ext: ["msc"], name: "MMC Console", cat: "config", viewer: "xml", desc: "Saved management console." },
  { ext: ["pif"], name: "Program Information File", cat: "system", viewer: "fallback", desc: "DOS program shortcut." },
  { ext: ["ovl"], name: "DOS Overlay Module", cat: "system", viewer: "fallback", desc: "Executable overlay." },
  { ext: ["bgi"], name: "Borland Graphics Interface", cat: "system", viewer: "fallback", desc: "BGI display driver." },
  { ext: ["rsrc"], name: "Mac Resource Fork", cat: "system", viewer: "fallback", desc: "Classic resource data." },
  { ext: ["bom"], name: "macOS Bill of Materials", cat: "system", viewer: "fallback", desc: "Installer receipt data." },
  { ext: ["kbx"], name: "GnuPG Keybox", cat: "system", viewer: "fallback", desc: "Public key storage." },
  { ext: ["network", "netdev", "link", "swap", "path", "slice", "target", "automount"], name: "systemd Unit", cat: "config", viewer: "text", desc: "systemd unit type." },
  { ext: ["directory"], name: "KDE Directory Config", cat: "config", viewer: "text", desc: "Folder settings." },
  { ext: ["menu"], name: "KDE Menu Layout", cat: "config", viewer: "xml", desc: "Application menu XML." },
  { ext: ["policy"], name: "Polkit Policy", cat: "config", viewer: "xml", desc: "Authorization policy." },
  { ext: ["acf"], name: "Steam App Manifest", cat: "config", viewer: "text", desc: "Installed game info." },
  { ext: ["crontab"], name: "Crontab", cat: "config", viewer: "text", desc: "Cron job list." },
  { ext: ["ovpn"], name: "OpenVPN Config", cat: "config", viewer: "text", desc: "VPN client profile." },
  { ext: ["dproj"], name: "Delphi MSBuild Project", cat: "config", viewer: "xml", desc: "RAD Studio project." },
  { ext: ["sln"], name: "Visual Studio Solution", cat: "config", viewer: "text", desc: "Solution definition." },
  { ext: ["suo"], name: "VS Solution Options", cat: "config", viewer: "fallback", desc: "IDE user options." },
  { ext: ["vcxproj", "vcproj"], name: "MSBuild C++ Project", cat: "config", viewer: "xml", desc: "Visual Studio project." },
  { ext: ["targets"], name: "MSBuild Targets", cat: "config", viewer: "xml", desc: "Build targets file." },
  { ext: ["gyp", "gypi"], name: "Chromium Build File", cat: "config", viewer: "code", desc: "Generate-your-project." },
  { ext: ["resx"], name: ".NET Resources", cat: "data", viewer: "xml", desc: "Managed resources." },
  { ext: ["resources"], name: "Java Compiled Resources", cat: "data", viewer: "fallback", desc: "Bundled .NET/Java strings." },
  { ext: ["appxmanifest"], name: "Appx Manifest", cat: "config", viewer: "xml", desc: "UWP package manifest." },
  { ext: ["pbxproj"], name: "Xcode Project", cat: "config", viewer: "text", desc: "Project object graph." },
  { ext: ["xcconfig"], name: "Xcode Build Config", cat: "config", viewer: "text", desc: "Build setting file." },
  { ext: ["xcscheme"], name: "Xcode Scheme", cat: "config", viewer: "xml", desc: "Build/run scheme." },
  { ext: ["xcarchive"], name: "Xcode Archive", cat: "archive", viewer: "fallback", desc: "Release archive." },
  { ext: ["hlp"], name: "WinHelp File", cat: "document", viewer: "fallback", desc: "Classic Windows help." },

  // ---------- Game ROMs & engines ----------
  { ext: ["a26"], name: "Atari 2600 ROM", cat: "game", viewer: "fallback", desc: "VCS cartridge dump." },
  { ext: ["a52"], name: "Atari 5200 ROM", cat: "game", viewer: "fallback", desc: "5200 cartridge dump." },
  { ext: ["a78"], name: "Atari 7800 ROM", cat: "game", viewer: "fallback", desc: "ProSystem dump." },
  { ext: ["lnx"], name: "Atari Lynx ROM", cat: "game", viewer: "fallback", desc: "Lynx cartridge dump." },
  { ext: ["sgx"], name: "SuperGrafx ROM", cat: "game", viewer: "fallback", desc: "PC Engine SGX dump." },
  { ext: ["bs"], name: "BS-X Satellaview ROM", cat: "game", viewer: "fallback", desc: "SNES satellite dump." },
  { ext: ["mx1", "mx2"], name: "MSX ROM Image", cat: "game", viewer: "fallback", desc: "Mapped MSX cartridge." },
  { ext: ["cia", "cci"], name: "Nintendo 3DS Package", cat: "game", viewer: "fallback", desc: "Installable/cartridge image." },
  { ext: ["cxi"], name: "3DS Executable", cat: "game", viewer: "fallback", desc: "CTR main binary." },
  { ext: ["3dsx"], name: "3DSX Homebrew Executable", cat: "game", viewer: "fallback", sig: "33 44 53 58", desc: "Homebrew loader app." },
  { ext: ["rpl", "rpx"], name: "Wii U Executable", cat: "game", viewer: "fallback", desc: "Cafe OS binary." },
  { ext: ["nro"], name: "Switch NRO Executable", cat: "game", viewer: "fallback", sig: "4E 52 4F 30", desc: "Homebrew executable." },
  { ext: ["nso"], name: "Switch NSO Executable", cat: "game", viewer: "fallback", sig: "4E 53 4F 30", desc: "System module binary." },
  { ext: ["gcz"], name: "GameCube GCZ Image", cat: "game", viewer: "fallback", desc: "Dolphin compressed disc." },
  { ext: ["wia"], name: "Wii WIA Image", cat: "game", viewer: "fallback", desc: "Compressed Wii disc." },
  { ext: ["ndd"], name: "64DD Disk Image", cat: "game", viewer: "fallback", desc: "N64 disk dump." },
  { ext: ["xex"], name: "Atari 8-bit Executable", cat: "game", viewer: "fallback", desc: "XEX program file." },
  { ext: ["z1", "z2", "z3", "z4", "z5", "z7", "z8"], name: "Z-machine Story File", cat: "game", viewer: "fallback", desc: "Infocom interactive fiction." },
  { ext: ["blb", "blorb", "zlb"], name: "Blorb Resource Bundle", cat: "game", viewer: "fallback", desc: "IF resources package." },
  { ext: ["ulx"], name: "Glulx Story File", cat: "game", viewer: "fallback", desc: "Modern IF virtual machine." },
  { ext: ["gam", "t3"], name: "TADS Story File", cat: "game", viewer: "fallback", desc: "Text adventure game." },
  { ext: ["taf"], name: "ADRIFT Game", cat: "game", viewer: "fallback", desc: "Adventuron ADRIFT file." },
  { ext: ["zil"], name: "ZIL Source", cat: "code", viewer: "code", desc: "Zork implementation language." },
  { ext: ["p8"], name: "PICO-8 Cartridge", cat: "game", viewer: "code", desc: "Fantasy console program." },
  { ext: ["tic"], name: "TIC-80 Cartridge", cat: "game", viewer: "fallback", desc: "Fantasy console cart." },
  { ext: ["sb2", "sb3"], name: "Scratch Project", cat: "game", viewer: "fallback", desc: "MIT blocks project." },
  { ext: ["sprite", "sprite2"], name: "Scratch Sprite", cat: "game", viewer: "fallback", desc: "Scratch sprite object." },
  { ext: ["capx"], name: "Construct Project", cat: "game", viewer: "fallback", desc: "Construct game bundle." },
  { ext: ["mfa"], name: "Clickteam Fusion App", cat: "game", viewer: "fallback", desc: "MMF application." },
  { ext: ["osu", "osr", "osk", "osb"], name: "osu! File", cat: "game", viewer: "text", desc: "Beatmap/replay/skin." },
  { ext: ["bms", "bme", "bml"], name: "Be-Music Script", cat: "game", viewer: "text", desc: "Rhythm game notation." },
  { ext: ["sm", "ssc", "dwi"], name: "StepMania Chart", cat: "game", viewer: "text", desc: "Dance chart file." },
  { ext: ["ldr"], name: "LDraw Model", cat: "3d", viewer: "three3d", desc: "LEGO brick model." },
  { ext: ["lxf", "lxfml"], name: "LEGO Digital Designer Model", cat: "3d", viewer: "fallback", desc: "LDD construction." },
  { ext: ["h3m", "h3c"], name: "Heroes III Map/Campaign", cat: "game", viewer: "fallback", desc: "HoMM3 scenario." },
  { ext: ["scx"], name: "StarCraft Map", cat: "game", viewer: "fallback", desc: "Brood War scenario." },
  { ext: ["d2s"], name: "Diablo II Save", cat: "game", viewer: "fallback", desc: "Character save." },
  { ext: ["rel"], name: "Wii REL Module", cat: "game", viewer: "fallback", desc: "Relocatable module." },
  { ext: ["unr", "utx", "uax", "usx", "ukx"], name: "Unreal Engine 1 Package", cat: "game", viewer: "fallback", desc: "UE map/texture/audio mesh." },
  { ext: ["deh", "bex"], name: "Doom DeHackEd Patch", cat: "game", viewer: "text", desc: "Gameplay patch." },
  { ext: ["rxdata"], name: "RPG Maker XP Data", cat: "game", viewer: "fallback", desc: "Marshalled game data." },
  { ext: ["cns", "air"], name: "MUGEN Character Data", cat: "game", viewer: "text", desc: "Fighter definition." },
  { ext: ["tlk"], name: "Infinity Engine Dialog", cat: "game", viewer: "fallback", desc: "Baldur's Gate text." },
  { ext: ["ppf"], name: "PlayStation Patch", cat: "game", viewer: "fallback", sig: "50 50 46 33 30", desc: "Disc image patch." },
  { ext: ["dir", "dxr", "cst"], name: "Macromedia Director Movie", cat: "game", viewer: "fallback", desc: "Shockwave multimedia." },
  { ext: ["fla"], name: "Flash FLA Source", cat: "code", viewer: "fallback", desc: "Flash authoring file." },
  { ext: ["tjs"], name: "TJS Script", cat: "code", viewer: "code", desc: "Kirikiri VN language." },
  { ext: ["8xp", "8xk", "8xg"], name: "TI-83 Plus File", cat: "code", viewer: "fallback", sig: "2A 2A 54 49 38 33 46 2A", desc: "Calculator program." },
  { ext: ["gci"], name: "GameCube Memory Card Image", cat: "game", viewer: "fallback", desc: "GC save block." },
  { ext: ["vmc"], name: "PS2 Memory Card Image", cat: "game", viewer: "fallback", desc: "Virtual memory card." },
  { ext: ["srm"], name: "Emulator SRAM Save", cat: "game", viewer: "fallback", desc: "Cartridge RAM dump." },
  { ext: ["dbc"], name: "CAN Database (DBC)", cat: "other", viewer: "text", desc: "Vector CAN bus network." },
  { ext: ["arxml"], name: "AUTOSAR XML", cat: "data", viewer: "xml", desc: "Automotive system description." },
  { ext: ["odx"], name: "AUTOSAR Diagnostics (ODX)", cat: "data", viewer: "xml", desc: "Vehicle diagnostic data." },

  // ---------- Scientific: chem / bio / physics / astro / geo ----------
  { ext: ["asdf"], name: "Advanced Scientific Data Format", cat: "scientific", viewer: "fallback", sig: "23 41 53 44 46", desc: "Astronomy replacement for FITS." },
  { ext: ["imh"], name: "IRAF Image", cat: "scientific", viewer: "fallback", desc: "NOAO astronomy image." },
  { ext: ["fz"], name: "Fpack Compressed FITS", cat: "scientific", viewer: "fallback", desc: "Rice-compressed FITS." },
  { ext: ["root"], name: "CERN ROOT File", cat: "scientific", viewer: "fallback", sig: "72 6F 6F 74", desc: "High-energy physics data." },
  { ext: ["hbook"], name: "CERNLIB HBOOK", cat: "scientific", viewer: "fallback", desc: "Legacy CERN ntuple." },
  { ext: ["v5d"], name: "Vis5D Dataset", cat: "scientific", viewer: "fallback", desc: "3D weather grid." },
  { ext: ["silo"], name: "Silo Mesh Database", cat: "scientific", viewer: "fallback", desc: "LLNL mesh format." },
  { ext: ["exo"], name: "Exodus II Mesh", cat: "scientific", viewer: "fallback", desc: "Finite element mesh." },
  { ext: ["tec"], name: "Tecplot Data", cat: "scientific", viewer: "text", desc: "CFE visualization data." },
  { ext: ["nas"], name: "Nastran Bulk Data", cat: "scientific", viewer: "text", desc: "FEA input deck." },
  { ext: ["k"], name: "LS-DYNA Input", cat: "scientific", viewer: "text", desc: "Crash simulation keyword deck." },
  { ext: ["d3plot"], name: "LS-DYNA Plot", cat: "scientific", viewer: "fallback", desc: "Simulation result state." },
  { ext: ["crd"], name: "CHARMM Coordinates", cat: "scientific", viewer: "text", desc: "Card-format coordinates." },
  { ext: ["top"], name: "AMBER Topology", cat: "scientific", viewer: "text", desc: "Molecular topology." },
  { ext: ["car"], name: "Biosym Coordinate File", cat: "scientific", viewer: "text", desc: "Insight II coordinates." },
  { ext: ["txyz"], name: "TINKER XYZ", cat: "scientific", viewer: "text", desc: "Molecular coordinates." },
  { ext: ["mrv"], name: "ChemAxon MRV", cat: "scientific", viewer: "xml", desc: "Chemical structure XML." },
  { ext: ["wfx"], name: "AIM Wavefunction", cat: "scientific", viewer: "text", desc: "Aimpac wavefunction." },
  { ext: ["wiff"], name: "AB Sciex WIFF", cat: "scientific", viewer: "fallback", desc: "Mass spectrometry data." },
  { ext: ["fcs"], name: "Flow Cytometry Standard", cat: "scientific", viewer: "fallback", sig: "46 43 53", desc: "Cell sorter data." },
  { ext: ["sra"], name: "NCBI Sequence Read", cat: "scientific", viewer: "fallback", desc: "Sequencing archive." },
  { ext: ["gfa"], name: "Graph Alignment Format", cat: "scientific", viewer: "text", desc: "Sequence assembly graph." },
  { ext: ["hic"], name: "Juicer Hi-C Map", cat: "scientific", viewer: "fallback", desc: "Chromatin contact matrix." },
  { ext: ["biom"], name: "BIOM Observation Matrix", cat: "scientific", viewer: "json", desc: "Microbiome data." },
  { ext: ["chain"], name: "LiftOver Chain", cat: "scientific", viewer: "text", desc: "Genome alignment blocks." },
  { ext: ["psl"], name: "BLAT PSL Alignment", cat: "scientific", viewer: "text", desc: "Genome alignments." },
  { ext: ["axt"], name: "AXT Alignment", cat: "scientific", viewer: "text", desc: "Pairwise genome alignment." },
  { ext: ["tbl"], name: "Artemis Feature Table", cat: "scientific", viewer: "text", desc: "NCBI annotation table." },
  { ext: ["lhe"], name: "Les Houches Event File", cat: "scientific", viewer: "text", desc: "Monte Carlo events." },
  { ext: ["segy", "sgy"], name: "SEG-Y Seismic Data", cat: "scientific", viewer: "fallback", desc: "Reflection seismology." },
  { ext: ["su"], name: "Seismic Unix Trace", cat: "scientific", viewer: "fallback", desc: "SU trace data." },
  { ext: ["lis", "dlis"], name: "Well Log (LIS/DLIS)", cat: "scientific", viewer: "fallback", desc: "Petrophysical logs." },
  { ext: ["gjf"], name: "Gaussian Input", cat: "scientific", viewer: "text", desc: "Quantum chemistry job." },
  { ext: ["cssr"], name: "CSSR Pore Structure", cat: "scientific", viewer: "text", desc: "Zeolite/COF structure." },
  { ext: ["jdx"], name: "JCAMP-DX Spectrum", cat: "scientific", viewer: "text", desc: "Chemical spectra exchange." },
  { ext: ["dx"], name: "OpenDX Data", cat: "scientific", viewer: "text", desc: "IBM Visualization Data Explorer." },
  { ext: ["tre"], name: "Newick Tree", cat: "scientific", viewer: "text", desc: "Phylogeny notation." },
  { ext: ["dm3", "dm4"], name: "DigitalMicrograph Image", cat: "scientific", viewer: "fallback", desc: "Gatan TEM data." },
  { ext: ["ser"], name: "TIA / NMR Image", cat: "scientific", viewer: "fallback", desc: "TEM imaging data." },
  { ext: ["xrdml"], name: "PANalytical XRDML", cat: "scientific", viewer: "xml", desc: "X-ray diffraction data." },
  { ext: ["fid"], name: "NMR Free Induction Decay", cat: "scientific", viewer: "fallback", desc: "Raw NMR signal." },
  { ext: ["unv"], name: "I-DEAS Universal File", cat: "scientific", viewer: "text", desc: "CAE neutral data." },
  { ext: ["cgns"], name: "CFD General Notation System", cat: "scientific", viewer: "fallback", desc: "CFD mesh and solution." },
  { ext: ["vtk"], name: "VTK Legacy Data", cat: "scientific", viewer: "text", desc: "Kitware visualization data." },
  { ext: ["vti", "vtr", "vts", "vtp", "vtu"], name: "VTK XML Data", cat: "scientific", viewer: "xml", desc: "Typed VTK dataset." },
  { ext: ["fld"], name: "AVS Field Data", cat: "scientific", viewer: "text", desc: "AVS coordinate data." },
  { ext: ["c3d"], name: "C3D Motion Capture", cat: "3d", viewer: "fallback", desc: "Biomechanics 3D data." },
  { ext: ["trc"], name: "TRC Motion Capture", cat: "3d", viewer: "text", desc: "Motion analysis text." },
  { ext: ["amc"], name: "AMC Motion Capture", cat: "3d", viewer: "text", desc: "Skeletal motion data." },
  { ext: ["bvh"], name: "BVH Motion Capture", cat: "3d", viewer: "three3d", desc: "Skeletal animation." },
  { ext: ["slx"], name: "Simulink Model", cat: "scientific", viewer: "fallback", desc: "Block diagram model." },
  { ext: ["mat"], name: "MATLAB Data File", cat: "scientific", viewer: "fallback", desc: "MAT-file array data." },
  { ext: ["nb"], name: "Mathematica Notebook", cat: "scientific", viewer: "text", desc: "Wolfram document." },
  { ext: ["mw", "mws"], name: "Maple Worksheet", cat: "scientific", viewer: "xml", desc: "Maple math document." },
  { ext: ["xmcd"], name: "Mathcad Worksheet", cat: "scientific", viewer: "xml", desc: "PTC Mathcad sheet." },
  { ext: ["opj", "opju"], name: "Origin Project", cat: "scientific", viewer: "fallback", desc: "Graphing project." },
  { ext: ["sp"], name: "SPICE Circuit Deck", cat: "other", viewer: "text", desc: "Circuit netlist." },
  { ext: ["qasm"], name: "OpenQASM", cat: "code", viewer: "code", desc: "Quantum assembly." },
  { ext: ["quil"], name: "Quil Quantum Program", cat: "code", viewer: "code", desc: "Rigetti quantum source." },

  // ---------- ML models & data science ----------
  { ext: ["arrow", "feather"], name: "Apache Arrow IPC File", cat: "data", viewer: "fallback", sig: "41 52 52 4F 57 31", desc: "Columnar memory format." },
  { ext: ["pdmodel", "pdparams", "pdopt", "pdiparams"], name: "PaddlePaddle Model", cat: "data", viewer: "fallback", desc: "Paddle program/weights." },
  { ext: ["arpa", "lm"], name: "ARPA Language Model", cat: "data", viewer: "text", desc: "N-gram backoff table." },
  { ext: ["vocab"], name: "Vocabulary File", cat: "data", viewer: "text", desc: "Token vocab listing." },
  { ext: ["spm"], name: "SentencePiece Model", cat: "data", viewer: "fallback", desc: "Subword tokenizer." },
  { ext: ["uff"], name: "UFF Model", cat: "data", viewer: "fallback", desc: "Universal framework format." },
  { ext: ["xmodel"], name: "Xilinx AI Model", cat: "data", viewer: "fallback", desc: "DPU graph model." },
  { ext: ["etlt"], name: "TensorRT Model", cat: "data", viewer: "fallback", desc: "NVIDIA transfer model." },
  { ext: ["smile"], name: "Jackson Smile Binary JSON", cat: "data", viewer: "fallback", sig: "3A 29 0A", desc: "Binary JSON variant." },
  { ext: ["jld2", "jld"], name: "Julia Data Format", cat: "data", viewer: "fallback", desc: "Julia HDF5 container." },
  { ext: ["nnef"], name: "NNEF Model", cat: "data", viewer: "fallback", desc: "Neural network exchange." },
  { ext: ["orc"], name: "ORC Columnar Data", cat: "data", viewer: "fallback", sig: "4F 52 43", desc: "Hive columnar storage." },
  { ext: ["edi", "x12"], name: "EDI Interchange", cat: "data", viewer: "text", desc: "EDIFACT/X12 business data." },
  { ext: ["ofx", "qfx"], name: "Open Financial Exchange", cat: "data", viewer: "text", desc: "Bank statement data." },
  { ext: ["qif"], name: "Quicken Interchange Format", cat: "data", viewer: "text", desc: "Personal finance data." },
  { ext: ["mt940"], name: "SWIFT MT940 Statement", cat: "data", viewer: "text", desc: "Bank account report." },
  { ext: ["qdf"], name: "Quicken Data File", cat: "data", viewer: "fallback", desc: "Quicken accounts DB." },
  { ext: ["gnucash"], name: "GnuCash Data", cat: "data", viewer: "xml", desc: "Accounting document." },
  { ext: ["ledger"], name: "Ledger Journal", cat: "data", viewer: "text", desc: "Plain-text accounting." },
  { ext: ["beancount"], name: "Beancount Ledger", cat: "data", viewer: "text", desc: "Plain-text accounting." },
  { ext: ["md5", "sfv", "sha1", "sha256", "sha512"], name: "Checksum File", cat: "data", viewer: "text", desc: "Digest manifest." },
  { ext: ["xsd"], name: "XML Schema Definition", cat: "data", viewer: "xml", desc: "XSD schema." },
  { ext: ["aff"], name: "Hunspell Affix File", cat: "data", viewer: "text", desc: "Spell-check affix rules." },
  { ext: ["sdp"], name: "Session Description Protocol", cat: "network", viewer: "text", desc: "RTP media description." },
  { ext: ["tde"], name: "Tableau Data Extract", cat: "data", viewer: "fallback", desc: "Columnar extract." },
  { ext: ["twb"], name: "Tableau Workbook", cat: "data", viewer: "xml", desc: "Visualization document." },
  { ext: ["twbx"], name: "Tableau Packaged Workbook", cat: "data", viewer: "fallback", desc: "Zipped workbook." },
  { ext: ["hyper"], name: "Tableau Extract (Hyper)", cat: "data", viewer: "fallback", desc: "Postgres-derived extract." },
  { ext: ["ktr", "kjb"], name: "Pentaho Transformation/Job", cat: "data", viewer: "xml", desc: "ETL definitions." },
  { ext: ["gcov"], name: "GCov Report", cat: "data", viewer: "text", desc: "Coverage annotated source." },
  { ext: ["gcda", "gcno"], name: "GCov Coverage Data", cat: "data", viewer: "fallback", desc: "Compiler counters." },
  { ext: ["lcov"], name: "LCOV Tracefile", cat: "data", viewer: "text", desc: "Coverage summary." },
  { ext: ["prof", "pprof"], name: "Profile Data", cat: "data", viewer: "fallback", desc: "Go/pprof samples." },
  { ext: ["tlog"], name: "MSBuild Tracking Log", cat: "data", viewer: "text", desc: "Build dependency log." },

  // ---------- CAD / EDA / 3D ----------
  { ext: ["gbr"], name: "Gerber Layout", cat: "other", viewer: "text", desc: "PCB photoplot data (RS-274X)." },
  { ext: ["mag"], name: "Magic VLSI Layout", cat: "other", viewer: "text", desc: "Berkeley IC layout." },
  { ext: ["sym"], name: "gEDA Symbol", cat: "other", viewer: "text", desc: "Schematic symbol." },
  { ext: ["skp", "skb"], name: "SketchUp Model", cat: "3d", viewer: "three3d", desc: "Trimble 3D model." },
  { ext: ["hip", "hipnc", "hiplc"], name: "Houdini Scene", cat: "3d", viewer: "fallback", desc: "SideFX scene file." },
  { ext: ["hda"], name: "Houdini Digital Asset", cat: "3d", viewer: "fallback", desc: "Node network asset." },
  { ext: ["bgeo"], name: "Houdini Geometry", cat: "3d", viewer: "fallback", desc: "Geometry cache." },
  { ext: ["geo"], name: "Houdini Geo File", cat: "3d", viewer: "fallback", desc: "Legacy Houdini geometry." },
  { ext: ["vdb"], name: "OpenVDB Volume", cat: "3d", viewer: "fallback", desc: "Sparse voxel grid." },
  { ext: ["ms3d"], name: "Milkshape 3D Model", cat: "3d", viewer: "fallback", desc: "Low-poly modeler." },
  { ext: ["nff"], name: "Neutral File Format", cat: "3d", viewer: "fallback", desc: "Renderman test geometry." },
  { ext: ["off"], name: "Object File Format", cat: "3d", viewer: "three3d", desc: "Polygon mesh." },
  { ext: ["iv"], name: "Open Inventor Scene", cat: "3d", viewer: "fallback", desc: "SGI 3D scene graph." },
  { ext: ["xsi"], name: "Softimage XSI", cat: "3d", viewer: "fallback", desc: "Softimage scene." },
  { ext: ["neu"], name: "PTC Neutral File", cat: "3d", viewer: "fallback", desc: "Creo exchange model." },
  { ext: ["x"], name: "DirectX Mesh", cat: "3d", viewer: "three3d", desc: "X file geometry." },
  { ext: ["mtl"], name: "Wavefront Material Library", cat: "3d", viewer: "text", desc: "OBJ materials." },
  { ext: ["b3d"], name: "Blitz3D Model", cat: "3d", viewer: "three3d", desc: "Game engine mesh." },
  { ext: ["vrm"], name: "VRM Humanoid Model", cat: "3d", viewer: "three3d", desc: "Avatar format on glTF." },
  { ext: ["babylon"], name: "Babylon.js Scene", cat: "3d", viewer: "three3d", desc: "WebGL scene JSON." },
  { ext: ["an8"], name: "Anim8or Model", cat: "3d", viewer: "fallback", desc: "Anim8or 3D data." },
  { ext: ["pz3"], name: "Poser Scene", cat: "3d", viewer: "fallback", desc: "Poser character scene." },
  { ext: ["rib"], name: "RenderMan Interface Bytestream", cat: "3d", viewer: "text", desc: "RenderMan scene." },
  { ext: ["sl"], name: "RenderMan Shading Language", cat: "code", viewer: "code", desc: "Shader source." },
  { ext: ["slo"], name: "Compiled RenderMan Shader", cat: "3d", viewer: "fallback", desc: "Compiled shader." },
  { ext: ["mi"], name: "mental ray Scene", cat: "3d", viewer: "text", desc: "NVIDIA renderer scene." },
  { ext: ["scad"], name: "OpenSCAD Source", cat: "code", viewer: "code", desc: "Constructive solid geometry." },
  { ext: ["sat"], name: "ACIS Solid Model (SAT)", cat: "3d", viewer: "text", desc: "3D modeling kernel text." },
  { ext: ["sab"], name: "ACIS Binary Model", cat: "3d", viewer: "fallback", desc: "3D kernel binary." },
  { ext: ["wings"], name: "Wings 3D Model", cat: "3d", viewer: "fallback", desc: "Subdivision modeler." },
  { ext: ["msh"], name: "Gmsh Mesh", cat: "3d", viewer: "three3d", desc: "Finite element mesh." },
  { ext: ["node", "ele"], name: "TetGen Mesh", cat: "3d", viewer: "fallback", desc: "Tetrahedralizer output." },
  { ext: ["tgd"], name: "Terragen Project", cat: "3d", viewer: "xml", desc: "Landscape scene." },
  { ext: ["ld", "lds"], name: "GNU Linker Script", cat: "code", viewer: "code", desc: "Section memory map." },

  // ---------- GIS / geo ----------
  { ext: ["mif"], name: "MapInfo Interchange (MIF)", cat: "geo", viewer: "map", desc: "MapInfo vector exchange." },
  { ext: ["qlr"], name: "QGIS Layer Definition", cat: "geo", viewer: "xml", desc: "QGIS layer XML." },
  { ext: ["lyrx"], name: "ArcGIS Pro Layer", cat: "geo", viewer: "json", desc: "Esri layer file." },
  { ext: ["ecw"], name: "ERDAS Compressed Wavelet", cat: "geo", viewer: "fallback", desc: "Compressed imagery." },
  { ext: ["bt"], name: "Binary Terrain", cat: "geo", viewer: "fallback", desc: "Elevation grid." },
  { ext: ["ddf"], name: "SDTS Data File", cat: "geo", viewer: "fallback", desc: "USGS spatial transfer." },
  { ext: ["igc"], name: "IGC Flight Log", cat: "geo", viewer: "text", desc: "GNSS gliding track." },
  { ext: ["itn"], name: "TomTom Itinerary", cat: "geo", viewer: "text", desc: "Route file." },
  { ext: ["bna"], name: "Atlas BNA Boundary", cat: "geo", viewer: "text", desc: "Boundary data." },
  { ext: ["pix"], name: "PCI Geomatics Database", cat: "geo", viewer: "fallback", desc: "Geomatica raster." },
  { ext: ["tfw", "jgw", "pgw", "bpw", "gfw", "blw", "wld"], name: "GIS World File", cat: "geo", viewer: "text", desc: "Raster georeference." },
  { ext: ["mvt"], name: "Mapbox Vector Tile", cat: "geo", viewer: "map", desc: "Protocol buffer tile." },
  { ext: ["fgb"], name: "FlatGeobuf", cat: "geo", viewer: "fallback", desc: "Flat encoded features." },
  { ext: ["wpt"], name: "OziExplorer Waypoint File", cat: "geo", viewer: "text", desc: "GPS track data." },
  { ext: ["grd"], name: "Surfer Grid", cat: "geo", viewer: "fallback", desc: "Golden Software grid." },

  // ---------- Programming languages & source ----------
  { ext: ["ll"], name: "LLVM IR (Text)", cat: "code", viewer: "code", desc: "Readable LLVM bitcode." },
  { ext: ["bc"], name: "LLVM Bitcode", cat: "code", viewer: "fallback", sig: "42 43 C0 DE", desc: "Compiler IR binary." },
  { ext: ["wat", "wast"], name: "WebAssembly Text Format", cat: "code", viewer: "code", desc: "WAT s-expression source." },
  { ext: ["vala"], name: "Vala Source", cat: "code", viewer: "code", desc: "GNOME C#-like language." },
  { ext: ["vapi"], name: "Vala API Definition", cat: "code", viewer: "code", desc: "GIR binding file." },
  { ext: ["gs"], name: "Genie Source", cat: "code", viewer: "code", desc: "Vala sibling language." },
  { ext: ["boo"], name: "Boo Source", cat: "code", viewer: "code", desc: ".NET Python-like language." },
  { ext: ["sml"], name: "Standard ML Source", cat: "code", viewer: "code", desc: "SML family source." },
  { ext: ["st"], name: "Smalltalk Source", cat: "code", viewer: "code", desc: "Smalltalk method/class file." },
  { ext: ["ls"], name: "LiveScript Source", cat: "code", viewer: "code", desc: "CoffeeScript successor." },
  { ext: ["moon"], name: "MoonScript Source", cat: "code", viewer: "code", desc: "Lua preprocessor language." },
  { ext: ["gd"], name: "GDScript", cat: "code", viewer: "code", desc: "Godot scripting language." },
  { ext: ["ceylon"], name: "Ceylon Source", cat: "code", viewer: "code", desc: "Red Hat JVM language." },
  { ext: ["fnl"], name: "Fennel Source", cat: "code", viewer: "code", desc: "Lua Lisp." },
  { ext: ["janet"], name: "Janet Source", cat: "code", viewer: "code", desc: "Lisp for Lua runtimes." },
  { ext: ["wren"], name: "Wren Source", cat: "code", viewer: "code", desc: "Embeddable script language." },
  { ext: ["gleam"], name: "Gleam Source", cat: "code", viewer: "code", desc: "Statically typed BEAM language." },
  { ext: ["hjson"], name: "Human JSON", cat: "data", viewer: "text", desc: "Relaxed JSON syntax." },
  { ext: ["factor"], name: "Factor Source", cat: "code", viewer: "code", desc: "Concatenative stack language." },
  { ext: ["ahk"], name: "AutoHotkey Script", cat: "code", viewer: "code", desc: "Windows automation." },
  { ext: ["au3"], name: "AutoIt Script", cat: "code", viewer: "code", desc: "Windows automation." },
  { ext: ["jcl"], name: "JCL Batch Script", cat: "code", viewer: "code", desc: "Mainframe job control." },
  { ext: ["idl", "odl"], name: "Interface Definition Language", cat: "code", viewer: "code", desc: "COM/CORBA IDL." },
  { ext: ["pli", "pl1"], name: "PL/I Source", cat: "code", viewer: "code", desc: "IBM enterprise language." },
  { ext: ["m3", "i3", "mg", "ig"], name: "Modula-3 Source", cat: "code", viewer: "code", desc: "DEC research language." },
  { ext: ["e"], name: "Eiffel Source", cat: "code", viewer: "code", desc: "Design-by-contract language." },
  { ext: ["exw"], name: "Euphoria Source", cat: "code", viewer: "code", desc: "Euphoria program." },
  { ext: ["nrx"], name: "NetRexx Source", cat: "code", viewer: "code", desc: "JVM Rexx dialect." },
  { ext: ["lpc"], name: "LPC Script", cat: "code", viewer: "code", desc: "MUD driver language." },
  { ext: ["pig"], name: "Pig Latin Script", cat: "code", viewer: "code", desc: "Hadoop dataflow language." },
  { ext: ["hql"], name: "HiveQL Script", cat: "code", viewer: "code", desc: "Hive query language." },
  { ext: ["pks", "pkb", "plb"], name: "PL/SQL Source", cat: "code", viewer: "code", desc: "Oracle database code." },
  { ext: ["abap"], name: "ABAP Source", cat: "code", viewer: "code", desc: "SAP application language." },
  { ext: ["rpg"], name: "RPG Source", cat: "code", viewer: "code", desc: "IBM report program generator." },
  { ext: ["4gl", "per"], name: "Informix 4GL Source", cat: "code", viewer: "code", desc: "4GL programs and forms." },
  { ext: ["oxy"], name: "Oxygene Source", cat: "code", viewer: "code", desc: "RemObjects Pascal." },
  { ext: ["tla"], name: "TLA+ Specification", cat: "code", viewer: "code", desc: "Formal specification language." },
  { ext: ["thy"], name: "Isabelle Theory", cat: "code", viewer: "code", desc: "Proof assistant source." },
  { ext: ["cfm", "cfc", "cfml"], name: "ColdFusion Source", cat: "code", viewer: "code", desc: "Adobe CFML files." },
  { ext: ["gsp"], name: "Groovy Server Page", cat: "code", viewer: "code", desc: "Grails view template." },
  { ext: ["as"], name: "ActionScript", cat: "code", viewer: "code", desc: "Flash/ECMAScript dialect." },
  { ext: ["mxml"], name: "Flex MXML", cat: "code", viewer: "xml", desc: "Flex UI markup." },
  { ext: ["razor"], name: "Blazor Razor Component", cat: "code", viewer: "code", desc: ".NET web component." },
  { ext: ["cshtml", "vbhtml"], name: "ASP.NET Razor Page", cat: "code", viewer: "code", desc: "Razor view file." },
  { ext: ["aspx", "ascx", "asmx", "ashx", "master"], name: "ASP.NET File", cat: "code", viewer: "code", desc: "WebForms page/control/handler." },
  { ext: ["asp"], name: "Classic ASP Page", cat: "code", viewer: "code", desc: "Legacy server scripting." },
  { ext: ["shtml", "shtm"], name: "SSI HTML", cat: "document", viewer: "text", desc: "Server-side includes." },
  { ext: ["cgi", "fcgi"], name: "CGI Script", cat: "code", viewer: "code", desc: "Common gateway interface." },
  { ext: ["hx"], name: "Haxe Source", cat: "code", viewer: "code", desc: "Multi-target language." },
  { ext: ["hxml"], name: "Haxe Build Config", cat: "config", viewer: "text", desc: "Compiler arguments." },
  { ext: ["vim"], name: "Vim Script", cat: "code", viewer: "code", desc: "Vim plugin source." },
  { ext: ["bb"], name: "BlitzBasic Source", cat: "code", viewer: "code", desc: "Blitz BASIC program." },
  { ext: ["ijs"], name: "J Source", cat: "code", viewer: "code", desc: "J array language script." },
  { ext: ["pyx", "pxd", "pxi"], name: "Cython Source", cat: "code", viewer: "code", desc: "Python-to-C compiler." },
  { ext: ["fish"], name: "Fish Shell Script", cat: "code", viewer: "code", desc: "Friendly interactive shell." },
  { ext: ["xsh"], name: "Xonsh Script", cat: "code", viewer: "code", desc: "Python-powered shell." },
  { ext: ["prg"], name: "xBase Program", cat: "code", viewer: "code", desc: "dBase/Clipper source." },
  { ext: ["sci", "sce"], name: "Scilab Source", cat: "code", viewer: "code", desc: "Scilab script." },
  { ext: ["sage", "sagews"], name: "Sage Source", cat: "code", viewer: "code", desc: "SageMath worksheet." },
  { ext: ["ck"], name: "ChucK Script", cat: "code", viewer: "code", desc: "Audio synthesis language." },
  { ext: ["hlsl"], name: "HLSL Shader", cat: "code", viewer: "code", desc: "DirectX high-level shader." },
  { ext: ["cg"], name: "NVIDIA Cg Shader", cat: "code", viewer: "code", desc: "C for graphics." },
  { ext: ["metal"], name: "Metal Shader", cat: "code", viewer: "code", desc: "Apple GPU language." },
  { ext: ["vert", "frag", "geom", "comp", "tesc", "tese", "glsl"], name: "GLSL Shader", cat: "code", viewer: "code", desc: "OpenGL shader stage." },
  { ext: ["cu", "cuh"], name: "CUDA Source", cat: "code", viewer: "code", desc: "NVIDIA GPU C/C++." },
  { ext: ["pde"], name: "Processing Sketch", cat: "code", viewer: "code", desc: "Java-based art sketch." },
  { ext: ["ctl"], name: "VB User Control", cat: "code", viewer: "code", desc: "Visual Basic control source." },
  { ext: ["y"], name: "Yacc Grammar", cat: "code", viewer: "code", desc: "Parser generator input." },
  { ext: ["g4"], name: "ANTLR Grammar", cat: "code", viewer: "code", desc: "ANTLR parser spec." },
  { ext: ["lark"], name: "Lark Grammar", cat: "code", viewer: "code", desc: "Python parser grammar." },
  { ext: ["pest"], name: "Pest Grammar", cat: "code", viewer: "code", desc: "Rust PEG grammar." },
  { ext: ["qc"], name: "QuakeC Source", cat: "code", viewer: "code", desc: "Quake game scripting." },
  { ext: ["sas"], name: "SAS Program", cat: "code", viewer: "code", desc: "SAS analytics source." },
  { ext: ["mako"], name: "Mako Template", cat: "code", viewer: "code", desc: "Python web template." },
  { ext: ["pug", "jade"], name: "Pug Template", cat: "code", viewer: "code", desc: "JS HTML preprocessor." },
  { ext: ["xaml"], name: "XAML UI", cat: "code", viewer: "xml", desc: "Microsoft UI markup." },
  { ext: ["cake"], name: "Cake Build Script", cat: "code", viewer: "code", desc: "C# build automation." },
  { ext: ["qbs"], name: "Qt Build Script", cat: "code", viewer: "code", desc: "Qbs project language." },
  { ext: ["qml"], name: "QML UI Source", cat: "code", viewer: "code", desc: "Qt modeling language." },
  { ext: ["qrc"], name: "Qt Resource Collection", cat: "code", viewer: "xml", desc: "Embedded asset index." },
  { ext: ["ui"], name: "Qt Designer Form", cat: "code", viewer: "xml", desc: "Widget layout XML." },
  { ext: ["qss"], name: "Qt Stylesheet", cat: "code", viewer: "code", desc: "CSS-like Qt skin." },
  { ext: ["xrc"], name: "wxWidgets XRC", cat: "code", viewer: "xml", desc: "wx UI resource XML." },
  { ext: ["glade"], name: "Glade UI Definition", cat: "code", viewer: "xml", desc: "GTK builder XML." },
  { ext: ["fxml"], name: "JavaFX UI", cat: "code", viewer: "xml", desc: "FXML layout markup." },
  { ext: ["jnlp"], name: "Java Web Start Descriptor", cat: "code", viewer: "xml", desc: "JNLP launcher." },
  { ext: ["jsp", "jspx"], name: "JavaServer Page", cat: "code", viewer: "code", desc: "JSP view source." },
  { ext: ["tag"], name: "JSP Tag File", cat: "code", viewer: "code", desc: "Custom JSP tag." },
  { ext: ["fasl", "fas"], name: "Compiled Lisp", cat: "code", viewer: "fallback", desc: "FASL fasload image." },
  { ext: ["asd"], name: "ASDF System Definition", cat: "code", viewer: "code", desc: "Common Lisp build file." },
  { ext: ["opam"], name: "OPAM File", cat: "config", viewer: "text", desc: "OCaml package spec." },
  { ext: ["dcu", "dcp"], name: "Delphi Compiled Unit", cat: "binary", viewer: "fallback", desc: "Pascal compiled code." },
  { ext: ["lpi", "lps", "lfm"], name: "Lazarus Project", cat: "config", viewer: "xml", desc: "Free Pascal IDE files." },
  { ext: ["cbp", "workspace"], name: "Code::Blocks Project", cat: "config", viewer: "xml", desc: "C::B build files." },
  { ext: ["wxi", "wxl"], name: "WiX Include/Localization", cat: "config", viewer: "xml", desc: "Installer fragments." },
  { ext: ["dsw", "opt"], name: "Visual Studio 6 Workspace", cat: "config", viewer: "text", desc: "Legacy IDE project." },
  { ext: ["ncb", "sbr", "ipch", "aps"], name: "MSVC Browse/Cache Data", cat: "binary", viewer: "fallback", desc: "IntelliSense databases." },
  { ext: ["pch"], name: "Precompiled Header", cat: "binary", viewer: "fallback", desc: "Compiler header cache." },
  { ext: ["ilk"], name: "MSVC Incremental Link DB", cat: "binary", viewer: "fallback", desc: "Linker state." },
  { ext: ["iobj", "ipdb"], name: "MSVC Incremental Object/PDB", cat: "binary", viewer: "fallback", desc: "LNK incremental data." },
  { ext: ["lib"], name: "Static Library", cat: "binary", viewer: "fallback", desc: "Linker object archive." },
  { ext: ["spec"], name: "RPM Spec File", cat: "config", viewer: "code", desc: "RPM build recipe." },
  { ext: ["am"], name: "Automake File", cat: "config", viewer: "text", desc: "Makefile.am source." },
  { ext: ["ac"], name: "Autoconf Macro", cat: "config", viewer: "text", desc: "M4 configure input." },
  { ext: ["m4"], name: "M4 Macro", cat: "code", viewer: "code", desc: "Macro processor source." },
  { ext: ["in"], name: "Autoconf Template", cat: "config", viewer: "text", desc: "configure input file." },
  { ext: ["pc"], name: "pkg-config Metadata", cat: "config", viewer: "text", desc: "Library compile flags." },
  { ext: ["cf"], name: "Configuration File", cat: "config", viewer: "text", desc: "Rules (cfengine, SA)." },
  { ext: ["ctags"], name: "Ctags Config", cat: "config", viewer: "text", desc: "Universal ctags options." },
  { ext: ["hgignore", "hgrc"], name: "Mercurial File", cat: "config", viewer: "text", desc: "Ignore/config settings." },
  { ext: ["cvsignore"], name: "CVS Ignore List", cat: "config", viewer: "text", desc: "Legacy VCS ignores." },
  { ext: ["vimrc", "gvimrc"], name: "Vim Config", cat: "config", viewer: "code", desc: "Editor startup script." },
  { ext: ["netrc"], name: "Netrc File", cat: "config", viewer: "text", desc: "FTP login defaults." },
  { ext: ["lock"], name: "Lockfile", cat: "config", viewer: "text", desc: "Package/app lock data." },
  { ext: ["htaccess", "htpasswd"], name: "Apache Config File", cat: "config", viewer: "text", desc: "Per-directory auth/rules." },
  { ext: ["sieve"], name: "Sieve Mail Filter", cat: "code", viewer: "code", desc: "RFC 5228 filters." },
  { ext: ["ebuild", "eclass"], name: "Gentoo Build Script", cat: "code", viewer: "code", desc: "Portage package recipe." },
  { ext: ["ql", "qll"], name: "CodeQL Query", cat: "code", viewer: "code", desc: "Semantic code query." },
  { ext: ["raml"], name: "RAML API Definition", cat: "config", viewer: "text", desc: "REST API modeling." },
  { ext: ["apib"], name: "API Blueprint", cat: "data", viewer: "markdown", desc: "Markdown API docs." },
  { ext: ["gp"], name: "Gnuplot Script", cat: "code", viewer: "code", desc: "Plot commands." },
  { ext: ["adm"], name: "Legacy Admin Template", cat: "config", viewer: "text", desc: "Classic policy file." },
  { ext: ["udl"], name: "Universal Data Link", cat: "config", viewer: "text", desc: "OLE DB connection." },

  // ---------- Documents / office / markup ----------
  { ext: ["dotx", "dotm"], name: "Word Template", cat: "document", viewer: "docx", desc: "OOXML document template." },
  { ext: ["thmx"], name: "Office Theme", cat: "document", viewer: "fallback", desc: "Shared OOXML theme." },
  { ext: ["xlam"], name: "Excel Add-in", cat: "spreadsheet", viewer: "xlsx", desc: "OOXML macro add-in." },
  { ext: ["ppam"], name: "PowerPoint Add-in", cat: "presentation", viewer: "pptx", desc: "OOXML macro add-in." },
  { ext: ["potm"], name: "PowerPoint Macro Template", cat: "presentation", viewer: "pptx", desc: "OOXML show template." },
  { ext: ["xlsb"], name: "Excel Binary Workbook", cat: "spreadsheet", viewer: "fallback", desc: "OOXML binary format." },
  { ext: ["slk", "sylk"], name: "SYLK Spreadsheet", cat: "spreadsheet", viewer: "text", desc: "Symbolic link interchange." },
  { ext: ["qpw"], name: "Quattro Pro Workbook", cat: "spreadsheet", viewer: "fallback", desc: "Corel spreadsheets." },
  { ext: ["wk1", "wks", "wk3", "wk4", "123"], name: "Lotus 1-2-3 Spreadsheet", cat: "spreadsheet", viewer: "fallback", desc: "Classic DOS/Windows sheets." },
  { ext: ["xlr"], name: "Works Spreadsheet", cat: "spreadsheet", viewer: "fallback", desc: "MS Works sheets." },
  { ext: ["sxc"], name: "OpenOffice 1.x Calc", cat: "spreadsheet", viewer: "fallback", desc: "XML spreadsheet." },
  { ext: ["sxw"], name: "OpenOffice 1.x Writer", cat: "document", viewer: "fallback", desc: "XML word processor." },
  { ext: ["sdd"], name: "StarOffice Impress", cat: "presentation", viewer: "fallback", desc: "Legacy presentation." },
  { ext: ["sdc"], name: "StarOffice Calc", cat: "spreadsheet", viewer: "fallback", desc: "Legacy spreadsheet." },
  { ext: ["sdw"], name: "StarOffice Writer", cat: "document", viewer: "fallback", desc: "Legacy word processor." },
  { ext: ["sda"], name: "StarOffice Draw", cat: "image", viewer: "fallback", desc: "Legacy drawing." },
  { ext: ["sxm"], name: "OpenOffice Math", cat: "document", viewer: "fallback", desc: "ODF formula document." },
  { ext: ["lwp"], name: "Lotus WordPro Document", cat: "document", viewer: "fallback", desc: "SmartSuite word processor." },
  { ext: ["pmd", "pmt"], name: "PageMaker Document", cat: "document", viewer: "fallback", desc: "Desktop publishing doc." },
  { ext: ["idml"], name: "InDesign Markup (IDML)", cat: "document", viewer: "fallback", desc: "Interchange package." },
  { ext: ["inx"], name: "InDesign Interchange", cat: "document", viewer: "xml", desc: "XML interchange doc." },
  { ext: ["zabw"], name: "Compressed AbiWord", cat: "document", viewer: "fallback", desc: "Gzipped AbiWord XML." },
  { ext: ["xps", "oxps"], name: "XML Paper Specification", cat: "document", viewer: "fallback", mime: "application/vnd.ms-xpsdocument", desc: "Fixed-layout document." },
  { ext: ["hxs", "hxi"], name: "MS Help 2 Collection", cat: "ebook", viewer: "fallback", desc: "Visual Studio help." },
  { ext: ["fb2"], name: "FictionBook", cat: "ebook", viewer: "xml", mime: "application/x-fictionbook+xml", desc: "XML e-book format." },
  { ext: ["xeb", "ceb"], name: "Apabi Ebook", cat: "ebook", viewer: "fallback", desc: "Chinese e-book format." },
  { ext: ["ibooks"], name: "Apple iBooks", cat: "ebook", viewer: "fallback", desc: "Multi-touch e-book." },
  { ext: ["kepub"], name: "Kobo EPUB", cat: "ebook", viewer: "epub", desc: "Kobo-flavored e-book." },
  { ext: ["cwk"], name: "AppleWorks/ClarisWorks Document", cat: "document", viewer: "fallback", desc: "Classic Mac suite." },
  { ext: ["uot", "uos", "uop"], name: "Unified Office Format", cat: "document", viewer: "fallback", desc: "Chinese GB standard." },
  { ext: ["one", "onetoc2", "onepkg"], name: "Microsoft OneNote", cat: "document", viewer: "fallback", desc: "Notebook data files." },
  { ext: ["xsn"], name: "InfoPath Form Template", cat: "document", viewer: "fallback", desc: "Cabinet form package." },
  { ext: ["mpt"], name: "Microsoft Project Template", cat: "document", viewer: "fallback", desc: "Project planning file." },
  { ext: ["vsd", "vsdm"], name: "Visio Binary Drawing", cat: "document", viewer: "fallback", desc: "Legacy VSD diagrams." },
  { ext: ["vsdx", "vssx", "vstx"], name: "Visio OOXML", cat: "document", viewer: "fallback", desc: "Drawing/stencil/template." },
  { ext: ["vss", "vst"], name: "Visio Binary Stencil/Template", cat: "document", viewer: "fallback", desc: "Legacy Visio parts." },
  { ext: ["vdx", "vsx", "vtx"], name: "Visio XML", cat: "document", viewer: "xml", desc: "XML drawing interchange." },
  { ext: ["xmind"], name: "XMind Mind Map", cat: "document", viewer: "fallback", desc: "Zipped mind map." },
  { ext: ["mmap"], name: "MindManager Map", cat: "document", viewer: "fallback", desc: "Mind map document." },
  { ext: ["dia"], name: "Dia Diagram", cat: "document", viewer: "fallback", desc: "Gnome diagram (zip)." },
  { ext: ["drawio"], name: "draw.io Diagram", cat: "document", viewer: "xml", desc: "Diagrams.net XML." },
  { ext: ["fdx"], name: "Final Draft Screenplay", cat: "document", viewer: "xml", desc: "Screenwriting format." },
  { ext: ["fountain"], name: "Fountain Screenplay", cat: "document", viewer: "text", desc: "Plain-text script markup." },
  { ext: ["celtx"], name: "Celtx Script", cat: "document", viewer: "fallback", desc: "Screenplay project." },
  { ext: ["dwt"], name: "Dreamweaver Template", cat: "document", viewer: "text", desc: "HTML site template." },
  { ext: ["ist"], name: "MakeIndex Style", cat: "document", viewer: "text", desc: "LaTeX index style." },
  { ext: ["ppd"], name: "PostScript Printer Description", cat: "config", viewer: "text", desc: "Printer capabilities." },
  { ext: ["gpd"], name: "Generic Printer Description", cat: "config", viewer: "text", desc: "Windows driver text." },
  { ext: ["pcl"], name: "PCL Print Stream", cat: "other", viewer: "fallback", desc: "Printer command data." },
  { ext: ["afp"], name: "Advanced Function Presentation", cat: "other", viewer: "fallback", desc: "IBM print datastream." },
  { ext: ["zpl"], name: "ZPL Label", cat: "other", viewer: "text", desc: "Zebra printer commands." },
  { ext: ["epl"], name: "EPL Label", cat: "other", viewer: "text", desc: "Eltron printer commands." },
  { ext: ["icm", "icc"], name: "ICC Color Profile", cat: "config", viewer: "fallback", desc: "Color management profile." },
  { ext: ["vi"], name: "LabVIEW Virtual Instrument", cat: "other", viewer: "fallback", desc: "G-dataflow program." },
  { ext: ["info"], name: "GNU Info Document", cat: "document", viewer: "text", desc: "Texinfo hypertext pages." },
  { ext: ["gmi"], name: "Gemtext", cat: "document", viewer: "text", desc: "Gemini protocol pages." },
  { ext: ["sgml", "sgm"], name: "SGML Document", cat: "document", viewer: "text", desc: "Standard generalized ML." },
  { ext: ["dbk"], name: "DocBook XML", cat: "document", viewer: "xml", desc: "Technical documentation." },
  { ext: ["dita", "ditamap"], name: "DITA Topic/Map", cat: "document", viewer: "xml", desc: "Structured authoring." },
  { ext: ["bib"], name: "BibTeX Bibliography", cat: "document", viewer: "text", desc: "LaTeX references." },
  { ext: ["bbl", "bst"], name: "BibTeX Output/Style", cat: "document", viewer: "text", desc: "Compiled bib and styles." },
  { ext: ["lyx"], name: "LyX Document", cat: "document", viewer: "text", desc: "LaTeX front-end file." },
  { ext: ["rss", "atom"], name: "Syndication Feed", cat: "data", viewer: "xml", desc: "RSS/Atom channel." },
  { ext: ["opml"], name: "OPML Outline", cat: "data", viewer: "xml", desc: "Subscription outlines." },
  { ext: ["jrxml"], name: "JasperReports Design", cat: "data", viewer: "xml", desc: "Report definition." },
  { ext: ["jasper"], name: "JasperReports Compiled", cat: "data", viewer: "fallback", desc: "Compiled report." },
  { ext: ["mrt"], name: "Stimulsoft Report", cat: "data", viewer: "xml", desc: "Report template." },
  { ext: ["xmi"], name: "XML Metadata Interchange", cat: "data", viewer: "xml", desc: "UML model exchange." },
  { ext: ["wsdl"], name: "WSDL Description", cat: "data", viewer: "xml", desc: "Web service contract." },
  { ext: ["xsl", "xslt"], name: "XSLT Stylesheet", cat: "code", viewer: "xml", desc: "XML transformation." },
  { ext: ["dtd"], name: "Document Type Definition", cat: "data", viewer: "xml", desc: "SGML/XML grammar." },
  { ext: ["rng"], name: "RELAX NG Grammar", cat: "data", viewer: "xml", desc: "XML schema language." },
  { ext: ["rdf", "owl"], name: "RDF / OWL Data", cat: "data", viewer: "xml", desc: "Semantic web triples." },
  { ext: ["ttl", "n3", "nt"], name: "Turtle / N3 / N-Triples", cat: "data", viewer: "text", desc: "RDF text serializations." },

  // ---------- Email ----------
  { ext: ["emlx"], name: "Apple Mail Message", cat: "email", viewer: "eml", desc: "Mail.app single message." },
  { ext: ["dbx"], name: "Outlook Express Store", cat: "email", viewer: "fallback", desc: "OE folder database." },
  { ext: ["pst", "ost"], name: "Outlook Data File", cat: "email", viewer: "fallback", sig: "21 42 44 4E", desc: "MAPI message store." },
  { ext: ["wab"], name: "Windows Address Book", cat: "email", viewer: "fallback", desc: "Contacts database." },
  { ext: ["pab"], name: "Personal Address Book", cat: "email", viewer: "fallback", desc: "Legacy address store." },
  { ext: ["mim"], name: "MIME Encoded Data", cat: "email", viewer: "text", desc: "Encoded attachment body." },

  // ---------- Databases ----------
  { ext: ["myd", "myi"], name: "MySQL Data/Index", cat: "database", viewer: "fallback", desc: "MyISAM table parts." },
  { ext: ["btr"], name: "Btrieve Data File", cat: "database", viewer: "fallback", desc: "Novell record manager." },
  { ext: ["ndx", "ntx"], name: "xBase Index", cat: "database", viewer: "fallback", desc: "dBase/Clipper indexes." },
  { ext: ["fpt"], name: "xBase Memo File", cat: "database", viewer: "fallback", desc: "dBase memo storage." },
  { ext: ["rec"], name: "GNU Recutils Database", cat: "database", viewer: "text", desc: "Plain-text records." },
  { ext: ["accde", "accdc"], name: "Access Executable", cat: "database", viewer: "fallback", desc: "Compiled database." },
  { ext: ["realm"], name: "Realm Database", cat: "database", viewer: "fallback", desc: "Mobile object database." },
  { ext: ["sst"], name: "LevelDB Table", cat: "database", viewer: "fallback", desc: "LSM key-value store." },
  { ext: ["couch"], name: "CouchDB Database", cat: "database", viewer: "fallback", desc: "Append-only document DB." },
  { ext: ["duckdb"], name: "DuckDB Database", cat: "database", viewer: "fallback", desc: "Analytical column store." },

  // ---------- Subtitles / chess / misc ----------
  { ext: ["pjs"], name: "Phoenix Subtitle File", cat: "subtitle", viewer: "subtitle", desc: "Japanimation subtitles." },
  { ext: ["ctg"], name: "ChessBase Opening Book", cat: "game", viewer: "chess", desc: "Tree of opening moves." },
  { ext: ["epd"], name: "Extended Position Description", cat: "game", viewer: "chess", desc: "FEN-like position text." },
  { ext: ["pqa"], name: "Palm Query Application", cat: "other", viewer: "fallback", desc: "Web clipping applet." },
  { ext: ["lck"], name: "Lock File", cat: "other", viewer: "fallback", desc: "Exclusive-use marker." },
  { ext: ["age"], name: "age Encrypted File", cat: "other", viewer: "fallback", desc: "Modern file encryption." },
  { ext: ["pea"], name: "PEA Archive", cat: "archive", viewer: "fallback", desc: "PeaZip archive format." },
  { ext: ["b1"], name: "B1 Archive", cat: "archive", viewer: "fallback", desc: "B1 packer format." },
  { ext: ["alz"], name: "ALZ Archive", cat: "archive", viewer: "fallback", desc: "ESTsoft compression." },
  { ext: ["pae"], name: "PowerArchiver Encrypted", cat: "archive", viewer: "fallback", desc: "PA encrypted archive." },
  { ext: ["pes", "pec"], name: "Brother Embroidery", cat: "other", viewer: "fallback", desc: "Home machine stitch file." },
  { ext: ["hus", "vip", "vp3"], name: "Husqvarna Embroidery", cat: "other", viewer: "fallback", desc: "Viking/Pfaff stitch file." },
  { ext: ["jef", "sew"], name: "Janome Embroidery", cat: "other", viewer: "fallback", desc: "Janome stitch file." },
  { ext: ["dst", "exp"], name: "Tajima Embroidery", cat: "other", viewer: "fallback", desc: "Commercial stitch formats." },
  { ext: ["mmf"], name: "SMAF Ringtone", cat: "audio", viewer: "fallback", desc: "Synthetic mobile audio." },
  { ext: ["sbc"], name: "SBC Audio", cat: "audio", viewer: "fallback", desc: "Bluetooth codec stream." },
  { ext: ["acm"], name: "Interplay ACM Audio", cat: "audio", viewer: "fallback", desc: "Game speech audio." },
  { ext: ["strm"], name: "Media Stream Shortcut", cat: "video", viewer: "text", desc: "URL playlist stub." },
  { ext: ["mlv"], name: "Magic Lantern Video", cat: "video", viewer: "fallback", desc: "Canon RAW video frame." },
  { ext: ["tim"], name: "PSX TIM Texture", cat: "image", viewer: "fallback", sig: "10 00 00 00", desc: "PlayStation texture." },
  { ext: ["tm2"], name: "PS2 TM2 Texture", cat: "image", viewer: "fallback", desc: "PlayStation 2 texture." },
  { ext: ["sk"], name: "Skencil Document", cat: "image", viewer: "fallback", desc: "Linux vector drawing." },
  { ext: ["wsq"], name: "WSQ Fingerprint Image", cat: "image", viewer: "fallback", desc: "FBI wavelet codec." },
  { ext: ["lsm"], name: "Zeiss LSM Image", cat: "scientific", viewer: "fallback", desc: "Confocal microscopy stack." },
  { ext: ["lif"], name: "Leica LIF Image", cat: "scientific", viewer: "fallback", desc: "Leica microscopy container." },
  { ext: ["czi"], name: "Zeiss CZI Image", cat: "scientific", viewer: "fallback", desc: "Microscopy image data." },
  { ext: ["oir"], name: "Olympus OIR Image", cat: "scientific", viewer: "fallback", desc: "Olympus microscopy file." },
  { ext: ["sac"], name: "SAC Seismic Data", cat: "scientific", viewer: "fallback", desc: "Seismic analysis code." },
  { ext: ["drs"], name: "Age of Empires Resources", cat: "game", viewer: "fallback", desc: "AoE sound/gfx bundle." },
  { ext: ["slp"], name: "AoE SLP Graphics", cat: "game", viewer: "fallback", desc: "Age of Empires art." },
  { ext: ["sh3d"], name: "Sweet Home 3D Design", cat: "3d", viewer: "fallback", desc: "Home layout plan (zip)." },
  { ext: ["lxo"], name: "Modo Scene", cat: "3d", viewer: "fallback", desc: "Foundry 3D scene." },
];

