import type { RawFormat } from "@/lib/types";

/**
 * AUTHORED EXPANSION A — media / system / game / scientific / geo / CAD / ML domains.
 * Extension list disjoint from database.ts. Same one-line style.
 */
export const EXTRA_FORMATS_A: RawFormat[] = [
  // ---------------- images ----------------
  { ext: ["ai"], name: "Adobe Illustrator Artwork", cat: "image", viewer: "image", mime: "application/illustrator", desc: "PDF/PGF-based vector artwork." },
  { ext: ["svgz"], name: "Compressed SVG", cat: "image", viewer: "svg", mime: "image/svg+xml", sig: "1F 8B 08", desc: "Gzip-compressed SVG vector graphics." },
  { ext: ["cgm"], name: "Computer Graphics Metafile", cat: "image", viewer: "fallback", mime: "image/cgm", sig: "43 47 4D 3A" },
  { ext: ["hpgl", "plt"], name: "HP Graphics Language Plotter File", cat: "image", viewer: "code", mime: "application/vnd.hp-HPGL", desc: "Pen-plotter vector commands." },
  { ext: ["pict", "pct"], name: "QuickDraw PICT", cat: "image", viewer: "image", mime: "image/x-pict", sig: "00 00 10 00" },
  { ext: ["iff", "lbm"], name: "Interchange File Format (ILBM)", cat: "image", viewer: "image", mime: "image/x-iff", sig: "46 4F 52 4D" },
  { ext: ["mac"], name: "MacPaint Image", cat: "image", viewer: "image", mime: "image/x-macpaint" },
  { ext: ["ras", "sun"], name: "Sun Raster Image", cat: "image", viewer: "image", mime: "image/x-cmu-raster", sig: "59 A6 6A 95" },
  { ext: ["xwd"], name: "X Window Dump", cat: "image", viewer: "image", mime: "image/x-xwindowdump" },
  { ext: ["psp", "pspimage"], name: "Paint Shop Pro Image", cat: "image", viewer: "image", mime: "image/x-psp" },
  { ext: ["mix"], name: "Microsoft Picture It", cat: "image", viewer: "fallback", mime: "image/vnd.mix" },
  { ext: ["fpx"], name: "FlashPix Image", cat: "image", viewer: "image", mime: "image/vnd.fpx" },
  { ext: ["jif", "jfi", "jfif-tbnl"], name: "JPEG Interchange Format", cat: "image", viewer: "image", mime: "image/jpeg", sig: "FF D8 FF" },
  { ext: ["cin"], name: "Kodak Cineon Image", cat: "image", viewer: "image", mime: "image/x-cineon" },
  { ext: ["dpx"], name: "SMPTE Digital Picture Exchange", cat: "image", viewer: "image", mime: "image/vnd.dpx", sig: "53 44 50 58" },
  { ext: ["pdn"], name: "Paint.NET Image", cat: "image", viewer: "image", mime: "image/x-pdn" },
  { ext: ["kra", "kraz"], name: "Krita Document", cat: "image", viewer: "image", mime: "application/x-krita", sig: "50 4B 03 04" },
  { ext: ["wbmp"], name: "Wireless Bitmap (WAP)", cat: "image", viewer: "image", mime: "image/vnd.wap.wbmp" },
  { ext: ["pal"], name: "Palette File", cat: "image", viewer: "text", mime: "image/x-palette", desc: "RGB palette (RIFF PAL / JASC)." },
  { ext: ["aco", "ase"], name: "Adobe Swatch File", cat: "image", viewer: "fallback", desc: "Photoshop swatch / swatch exchange." },
  { ext: ["ggr"], name: "GIMP Gradient", cat: "image", viewer: "text", mime: "application/x-gimp-gradient" },
  { ext: ["gih", "pat"], name: "GIMP Brush / Pattern", cat: "image", viewer: "image", desc: "GIMP data files (GBR brush, GIH image hose, PAT pattern)." },
  { ext: ["fh7", "fh8", "fh9", "fh10", "fh11"], name: "Macromedia FreeHand Drawing", cat: "image", viewer: "fallback", mime: "image/x-freehand" },
  { ext: ["indd", "indt", "indb"], name: "Adobe InDesign Document", cat: "document", viewer: "fallback", mime: "application/x-indesign", desc: "Layout documents (identified, pages listed)." },
  { ext: ["qxd", "qxt"], name: "QuarkXPress Document", cat: "document", viewer: "fallback", mime: "application/vnd.quark.quarkxpress" },
  { ext: ["pm3", "pm4", "pm5", "pm6", "p65"], name: "Adobe PageMaker Document", cat: "document", viewer: "fallback" },

  // ---------------- audio ----------------
  { ext: ["mpc", "mpp", "mp+"], name: "Musepack Audio", cat: "audio", viewer: "audio", mime: "audio/musepack", sig: "4D 50 2B" },
  { ext: ["ofr", "ofs"], name: "OptimFROG Audio", cat: "audio", viewer: "audio", mime: "audio/x-optimfrog" },
  { ext: ["la"], name: "La Lossless Audio", cat: "audio", viewer: "audio", mime: "audio/x-la" },
  { ext: ["shn"], name: "Shorten Audio", cat: "audio", viewer: "audio", mime: "audio/x-shorten", sig: "61 6A 6B 67" },
  { ext: ["aa", "aax"], name: "Audible Audiobook", cat: "ebook", viewer: "fallback", mime: "audio/vnd.audible" },
  { ext: ["ac3", "eac3"], name: "Dolby Digital Audio", cat: "audio", viewer: "audio", mime: "audio/ac3", sig: "0B 77" },
  { ext: ["dts", "dtshd"], name: "DTS Coherent Acoustics", cat: "audio", viewer: "audio", mime: "audio/vnd.dts", sig: "7F FE 80 01" },
  { ext: ["thd", "mlp"], name: "Dolby TrueHD / Meridian MLP", cat: "audio", viewer: "audio", mime: "audio/vnd.dolby.mlp" },
  { ext: ["spx"], name: "Speex Audio", cat: "audio", viewer: "audio", mime: "audio/speex", sig: "4F 67 67 53" },
  { ext: ["w64"], name: "Sony Wave64 Audio", cat: "audio", viewer: "audio", mime: "audio/vnd.wave", sig: "52 49 46 46" },
  { ext: ["u8", "s8", "u16", "s16", "u24", "s24", "u32", "s32", "f32", "f64"], name: "Raw PCM Audio", cat: "audio", viewer: "audio", mime: "audio/basic", desc: "Headerless raw samples; configure rate/channels manually." },
  { ext: ["sf2", "sf3"], name: "SoundFont Bank", cat: "audio", viewer: "midi", mime: "audio/sf2", sig: "52 49 46 46" },
  { ext: ["sfz"], name: "SFZ SoundFont Script", cat: "audio", viewer: "code", mime: "text/x-sfz" },
  { ext: ["gig"], name: "GigaStudio Instrument", cat: "audio", viewer: "fallback" },
  { ext: ["dls"], name: "Downloadable Sounds Bank", cat: "audio", viewer: "fallback", mime: "audio/dls", sig: "52 49 46 46" },
  { ext: ["669"], name: "Composer 669 Tracker Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["far"], name: "Farandole Tracker Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["gdm"], name: "General Digital Music Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["dmf"], name: "Delusion Digital Music Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["imf"], name: "Imago Orpheus Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["med"], name: "OctaMED Tracker Module", cat: "audio", viewer: "midi", mime: "audio/x-med" },
  { ext: ["okt"], name: "Oktalyzer Tracker Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["stm"], name: "Scream Tracker 2 Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["dsm"], name: "DSIK Internal Format Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["amf"], name: "DSM Advanced Module Format", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["ams"], name: "Extreme Tracker Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["psm"], name: "Protracker Studio Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["j2b"], name: "Gaming Music Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["dig"], name: "DIG Booster Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["dtm"], name: "DigiTrekker Module", cat: "audio", viewer: "midi", mime: "audio/x-mod" },
  { ext: ["umx"], name: "Unreal Music Package", cat: "audio", viewer: "fallback", sig: "C1 83 2A 9E" },
  { ext: ["mo3"], name: "MO3 Compressed Module", cat: "audio", viewer: "midi", mime: "audio/x-mod", sig: "4D 4F 33" },
  { ext: ["a2m"], name: "Titanics Tracker Module", cat: "audio", viewer: "midi" },
  { ext: ["mkm"], name: "PopMtracker Module", cat: "audio", viewer: "midi" },
  { ext: ["ptm"], name: "PolyTracker Module", cat: "audio", viewer: "midi" },
  { ext: ["gmc"], name: "Game Music Creator Module", cat: "audio", viewer: "midi" },
  { ext: ["sfx"], name: "SoundFX Module", cat: "audio", viewer: "midi" },
  { ext: ["mms"], name: "Music Maker Studio Module", cat: "audio", viewer: "midi" },
  { ext: ["mus"], name: "Music Module (Adlib/EA)", cat: "audio", viewer: "midi", sig: "00 03 00 00 00" },
  { ext: ["mpn"], name: "MakePhone Module", cat: "audio", viewer: "midi" },
  { ext: ["nsv2mod"], name: "NSV Mod Module", cat: "audio", viewer: "midi" },
  { ext: ["rtm"], name: "Real Tracker Module", cat: "audio", viewer: "midi" },
  { ext: ["symmod"], name: "Symphonie Module", cat: "audio", viewer: "midi" },
  { ext: ["s3i"], name: "Scream Tracker Sample", cat: "audio", viewer: "fallback" },
  { ext: ["at3", "oma"], name: "ATRAC3/ATRAC Advanced Audio", cat: "audio", viewer: "audio", mime: "audio/ATR3" },
  { ext: ["flp"], name: "FL Studio Project", cat: "audio", viewer: "fallback", desc: "Fruity Loops music project (structure info)." },
  { ext: ["rns", "xrns"], name: "Reason Song", cat: "audio", viewer: "fallback" },
  { ext: ["als", "alc", "alp", "amxd", "adv"], name: "Ableton Live Set", cat: "audio", viewer: "fallback", desc: "Ableton project/template/preset." },
  { ext: ["cpr", "csh"], name: "Cubase Project", cat: "audio", viewer: "fallback" },
  { ext: ["ptsd"], name: "Pro Tools Session", cat: "audio", viewer: "fallback" },
  { ext: ["reason"], name: "Reason Propellerhead", cat: "audio", viewer: "fallback" },
  { ext: ["mid2"], name: "MIDI (variant extension)", cat: "audio", viewer: "midi", sig: "4D 54 68 64" },
  { ext: ["kar"], name: "Karaoke MIDI", cat: "audio", viewer: "midi", mime: "audio/midi", sig: "4D 54 68 64", desc: "MIDI with .KAR lyrics meta events." },
  { ext: ["mxl", "musicxml"], name: "MusicXML (compressed)", cat: "audio", viewer: "code", mime: "application/vnd.recordare.musicxml", sig: "50 4B 03 04" },
  { ext: ["mml"], name: "Music Macro Language", cat: "audio", viewer: "code" },
  { ext: ["rmi2"], name: "RIFF MIDI", cat: "audio", viewer: "midi", sig: "52 49 46 46" },
  { ext: ["mus2"], name: "MUS Music (id Software)", cat: "audio", viewer: "midi", sig: "4D 55 53 1A" },

  // ---------------- video ----------------
  { ext: ["bik", "bink2", "bk2"], name: "RAD Game Tools Bink Video", cat: "video", viewer: "fallback", sig: "0A 42 49 47", desc: "Game cutscene codec (BINK signature)." },
  { ext: ["roq"], name: "RoQ Video (Quake)", cat: "video", viewer: "fallback", sig: "84 10" },
  { ext: ["nuv"], name: "NuppelVideo Recording", cat: "video", viewer: "fallback", sig: "52 4A 56 44" },
  { ext: ["ivf"], name: "IVF Raw VP8/VP9/AV1 Stream", cat: "video", viewer: "fallback", sig: "44 4B 49 46" },
  { ext: ["ogm"], name: "Ogg Media Video", cat: "video", viewer: "video", sig: "4F 67 67 53" },
  { ext: ["amv"], name: "MTV AMV Video", cat: "video", viewer: "fallback", sig: "41 4D 56" },
  { ext: ["mtv"], name: "MTV Video Format", cat: "video", viewer: "fallback" },
  { ext: ["264", "h264", "265", "h265", "hevc", "avc", "evo"], name: "Raw H.264/H.265 Elementary Stream", cat: "video", viewer: "fallback", desc: "Annex-B NAL units (00 00 01 start codes)." },
  { ext: ["dvr-ms"], name: "Microsoft DVR Recording", cat: "video", viewer: "fallback" },
  { ext: ["wtv"], name: "Windows Recorded TV Show", cat: "video", viewer: "fallback", sig: "B7 D8 00 20" },
  { ext: ["tod", "trp"], name: "JVC/Panasonic HD Camcorder MPEG-TS", cat: "video", viewer: "video" },
  { ext: ["dv"], name: "DV Video Stream", cat: "video", viewer: "fallback" },
  { ext: ["rm", "rmvb"], name: "RealMedia Video", cat: "video", viewer: "fallback", sig: "2E 52 4D 46" },
  { ext: ["ram"], name: "RealMedia Metadata", cat: "audio", viewer: "text", mime: "audio/x-pn-realaudio-meta" },
  { ext: ["wmx", "wvx", "asx"], name: "Windows Media Metafile", cat: "video", viewer: "code", mime: "video/x-ms-asx" },
  { ext: ["mp21", "m21"], name: "MPEG-21 Digital Item", cat: "video", viewer: "fallback", mime: "application/mp21" },
  { ext: ["mpv", "m4e"], name: "MPEG Elementary Video", cat: "video", viewer: "fallback" },
  { ext: ["f4f", "f4m"], name: "Adobe HTTP Dynamic Streaming", cat: "video", viewer: "fallback" },
  { ext: ["swi"], name: "Swish Animation", cat: "video", viewer: "fallback" },

  // ---------------- fonts ----------------
  { ext: ["afm"], name: "Adobe Font Metrics", cat: "font", viewer: "text", mime: "application/x-font-afm", sig: "53 74 61 72 74 46 6F 6E 74 4D 65 74 72 69 63 73" },
  { ext: ["dfont"], name: "Mac OS X Data-Font Resource", cat: "font", viewer: "font", sig: "00 01 00 00" },
  { ext: ["ttx"], name: "FontTools XML Dump", cat: "font", viewer: "xml" },
  { ext: ["ffi"], name: "FontForge Font Info", cat: "font", viewer: "fallback" },

  // ---------------- archives / compression ----------------
  { ext: ["lzma"], name: "LZMA Raw Stream", cat: "archive", viewer: "archive", sig: "5D 00 00" },
  { ext: ["lzo"], name: "LZO Compressed File", cat: "archive", viewer: "archive", sig: "89 4C 5A 4F 00 0D 0A 1A 0A" },
  { ext: ["zpaq"], name: "ZPAQ Archiver Archive", cat: "archive", viewer: "archive", sig: "7A 70 61 71" },
  { ext: ["par", "par2"], name: "Parchive Recovery Volume", cat: "archive", viewer: "fallback", sig: "50 41 52 32" },
  { ext: ["rev"], name: "RAR Recovery Volume", cat: "archive", viewer: "fallback", sig: "52 61 72 21" },
  { ext: ["ace"], name: "ACE Archive", cat: "archive", viewer: "fallback", sig: "C0 4A 43" },
  { ext: ["split"], name: "Split Archive Manifest", cat: "archive", viewer: "fallback", desc: "HJSplit/GSplit part index." },
  { ext: ["uha"], name: "UHARC Archive", cat: "archive", viewer: "fallback" },
  { ext: ["hki"], name: "HKI Archive", cat: "archive", viewer: "fallback" },
  { ext: ["yz1"], name: "YAY Archiver Archive", cat: "archive", viewer: "fallback" },
  { ext: ["dgc"], name: "DGCA Archive", cat: "archive", viewer: "fallback" },
  { ext: ["ice"], name: "ICE Archive", cat: "archive", viewer: "fallback" },
  { ext: ["pit"], name: "PackIt Archive", cat: "archive", viewer: "fallback" },
  { ext: ["sea"], name: "Self-Extracting Archive (Mac)", cat: "archive", viewer: "fallback" },
  { ext: ["uud"], name: "Ascii-Armored Encoding", cat: "code", viewer: "text", desc: "Base64/UUencoded/xxencoded binary text." },
  { ext: ["hfs"], name: "HFS Disk Image", cat: "disk", viewer: "fallback" },
  { ext: ["mdf", "mds"], name: "Alcohol 120% Disc Image", cat: "disk", viewer: "fallback", sig: "4D 45 44 3F" },
  { ext: ["ccd"], name: "CloneCD Disc Image", cat: "disk", viewer: "fallback" },
  { ext: ["nrg"], name: "Nero Disc Image", cat: "disk", viewer: "fallback", desc: "Nero image with trailer header (identifiable)." },
  { ext: ["daa"], name: "PowerISO Direct Access Archive", cat: "disk", viewer: "fallback" },
  { ext: ["isz"], name: "Compressed ISO Image", cat: "disk", viewer: "fallback" },
  { ext: ["uif"], name: "Universal Image Format", cat: "disk", viewer: "fallback" },
  { ext: ["pdi", "c2d", "b5i", "b6i", "gi"], name: "Legacy Disc Image Format", cat: "disk", viewer: "fallback", desc: "Instant Copy / Adaptec / BlindWrite / Prassi variants." },
  { ext: ["cdi"], name: "DiscJuggler Disc Image", cat: "disk", viewer: "fallback" },
  { ext: ["vcd"], name: "Virtual CD Image", cat: "disk", viewer: "fallback" },

  // ---------------- system / forensic ----------------
  { ext: ["blf"], name: "Windows Binary Log (CLFS)", cat: "system", viewer: "fallback" },
  { ext: ["etl"], name: "Event Trace Log", cat: "system", viewer: "fallback" },
  { ext: ["edb"], name: "Extensible Storage Engine Database", cat: "database", viewer: "fallback", sig: "FE ED FA CE" },
  { ext: ["pri"], name: "Windows Resource Index", cat: "system", viewer: "fallback" },
  { ext: ["mbn"], name: "Modem Firmware Blob", cat: "system", viewer: "fallback" },
  { ext: ["mib"], name: "SNMP Management Information Base", cat: "system", viewer: "code", mime: "text/plain" },
  { ext: ["fm", "fp5", "fp7", "fmp12", "4dd"], name: "FileMaker Pro Database", cat: "database", viewer: "fallback" },
  { ext: ["dta"], name: "Stata Dataset", cat: "data", viewer: "fallback" },
  { ext: ["sas7bdat", "xpt"], name: "SAS Dataset / Transport", cat: "data", viewer: "fallback" },
  { ext: ["dt0", "dt1", "dt2"], name: "DTED Elevation Data", cat: "geo", viewer: "fallback" },
  { ext: ["dfu"], name: "Device Firmware Update Image", cat: "system", viewer: "fallback" },

  // ---------------- game / emulation ----------------
  { ext: ["gen", "sg"], name: "Sega Mega Drive / Genesis ROM", cat: "game", viewer: "fallback" },
  { ext: ["gg"], name: "Sega Game Gear ROM", cat: "game", viewer: "fallback" },
  { ext: ["sms"], name: "Sega Master System ROM", cat: "game", viewer: "fallback" },
  { ext: ["32x"], name: "Sega 32X ROM", cat: "game", viewer: "fallback" },
  { ext: ["col"], name: "ColecoVision ROM", cat: "game", viewer: "fallback" },
  { ext: ["ws", "wsc"], name: "WonderSwan ROM", cat: "game", viewer: "fallback" },
  { ext: ["ngp"], name: "Neo Geo Pocket ROM", cat: "game", viewer: "fallback" },
  { ext: ["pce"], name: "PC Engine / TurboGrafx-16 ROM", cat: "game", viewer: "fallback" },
  { ext: ["fds"], name: "Famicom Disk System Image", cat: "game", viewer: "fallback" },
  { ext: ["qd"], name: "Famicom Quick Disk Image", cat: "game", viewer: "fallback" },
  { ext: ["sna", "csw", "pzx", "g64", "t64", "d64", "d71", "d81"], name: "Commodore/Sinclair Snapshot & Disk", cat: "game", viewer: "fallback", desc: "Emulator snapshots (Z80/SNA), compressed snapshots (CSW/PZX), C64 disk/cart images." },
  { ext: ["tzx"], name: "ZX Spectrum Tape Image", cat: "game", viewer: "fallback", sig: "5A 58 54 61 70 65 21" },
  { ext: ["nsp", "xci", "nsz", "xcz"], name: "Nintendo Switch Game Image", cat: "game", viewer: "fallback", desc: "NSP/XCI dumps and compressed homebrew variants." },
  { ext: ["dol"], name: "GameCube Executable", cat: "game", viewer: "fallback", sig: "D0 4F 4F 44" },
  { ext: ["jso"], name: "Compressed ISO (variants)", cat: "game", viewer: "fallback" },
  { ext: ["gdi"], name: "Dreamcast Disc Image Descriptor", cat: "game", viewer: "code" },
  { ext: ["psf", "psf2", "minipsf"], name: "PlayStation Sound Format", cat: "audio", viewer: "midi", sig: "50 53 46" },
  { ext: ["hes"], name: "PC Engine Sound rip", cat: "audio", viewer: "midi", sig: "48 45 53" },
  { ext: ["gym"], name: "Sega Mega Drive YM2612 Log", cat: "audio", viewer: "midi" },
  { ext: ["demo"], name: "Game Demo Recording", cat: "game", viewer: "fallback", desc: "Source engine demos begin HL2DEMO; Quake demos are message streams." },
  { ext: ["sc2replay"], name: "StarCraft II Replay", cat: "game", viewer: "fallback", sig: "4D 50 51 1A" },
  { ext: ["w3g", "w3m", "w3x", "w3n"], name: "Warcraft III Replay / Map", cat: "game", viewer: "fallback" },
  { ext: ["love"], name: "LÖVE 2D Game Package", cat: "game", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["yy", "yyp", "gmk", "gm81"], name: "GameMaker Project", cat: "game", viewer: "fallback" },
  { ext: ["rpa", "rpyc"], name: "Ren'Py Visual Novel Data", cat: "game", viewer: "fallback" },
  { ext: ["ldb", "lmu", "lsd", "rpgproject"], name: "RPG Maker Project Data", cat: "game", viewer: "fallback" },
  { ext: ["rgssad", "rgss2a", "rgss3a", "rvdata", "rvdata2"], name: "RPG Maker XP/VX/MV Archive", cat: "game", viewer: "fallback" },
  { ext: ["tscn", "tres", "escn", "gdc", "remap"], name: "Godot Engine Resource", cat: "game", viewer: "fallback" },
  { ext: ["md5camera"], name: "Doom 3 Model Data", cat: "3d", viewer: "three3d" },
  { ext: ["gcf"], name: "Steam Game Cache File", cat: "game", viewer: "fallback" },
  { ext: ["vox"], name: "MagicaVoxel Model", cat: "3d", viewer: "three3d", sig: "56 4F 58 20" },
  { ext: ["schematic", "mcstructure", "litematic"], name: "Minecraft Structure Schematic", cat: "game", viewer: "nbt" },
  { ext: ["adz", "dms", "msa", "ipf", "hfe", "scp", "dim"], name: "Retro Computer Disk Image", cat: "disk", viewer: "fallback", desc: "Amiga/Atari/flux-level floppy formats." },

  // ---------------- scientific ----------------
  { ext: ["embl"], name: "EMBL Nucleotide Database Flat File", cat: "scientific", viewer: "text", mime: "text/plain" },
  { ext: ["pir"], name: "PIR Protein Sequence Database", cat: "scientific", viewer: "text" },
  { ext: ["nex"], name: "NEXUS Multiple Alignment", cat: "scientific", viewer: "text" },
  { ext: ["nwk", "tree", "newick"], name: "Newick Phylogenetic Tree", cat: "scientific", viewer: "text" },
  { ext: ["phyloxml"], name: "PhyloXML Tree", cat: "scientific", viewer: "xml" },
  { ext: ["bcf"], name: "Variant Call Format", cat: "scientific", viewer: "text", mime: "text/x-vcard? no—genetics", desc: "Genomic variants (plain VCF or binary BCF)." },
  { ext: ["bed", "bedgraph", "bigwig", "bigbed", "wig", "2bit"], name: "UCSC Genome Browser Track", cat: "scientific", viewer: "text", desc: "Genomic interval/track formats." },
  { ext: ["gff", "gff2", "gff3", "gtf"], name: "GFF/GTF Annotation", cat: "scientific", viewer: "text" },
  { ext: ["sam", "cram"], name: "Sequence Alignment/Map", cat: "scientific", viewer: "text" },
  { ext: ["bam", "bai", "csi", "tbi"], name: "Binary Alignment Map & Index", cat: "scientific", viewer: "fallback", sig: "1F 8B 08", desc: "BGZF-compressed genomic alignments." },
  { ext: ["maf"], name: "Multiple Alignment Format", cat: "scientific", viewer: "text" },
  { ext: ["hhr"], name: "HHsearch Output", cat: "scientific", viewer: "text" },
  { ext: ["sto", "stockholm"], name: "Stockholm Alignment", cat: "scientific", viewer: "text" },
  { ext: ["a3m"], name: "A3M Alignment", cat: "scientific", viewer: "text" },
  { ext: ["sff"], name: "Roche 454 Flowgram", cat: "scientific", viewer: "fallback" },
  { ext: ["ab1", "scf"], name: "DNA Chromatogram", cat: "scientific", viewer: "fallback", desc: "Sanger trace reads." },
  { ext: ["qseq", "qual"], name: "FASTQ Companion Data", cat: "scientific", viewer: "text" },
  { ext: ["ped", "bim", "fam", "phe"], name: "PLINK Genetic Data", cat: "scientific", viewer: "text" },
  { ext: ["cdx", "cdxml"], name: "ChemDraw Document", cat: "scientific", viewer: "xml" },
  { ext: ["cml"], name: "Chemical Markup Language", cat: "scientific", viewer: "xml" },
  { ext: ["rxn"], name: "MDL Reaction File", cat: "scientific", viewer: "text" },
  { ext: ["pdbqt"], name: "AutoDock Ligand", cat: "scientific", viewer: "three3d" },
  { ext: ["hkl", "res"], name: "SHELX Reflection/Result File", cat: "scientific", viewer: "text" },
  { ext: ["mtz"], name: "CCP4 Crystallographic Data", cat: "scientific", viewer: "fallback" },
  { ext: ["grib", "grib2", "bufr"], name: "WMO Meteorological Data", cat: "scientific", viewer: "fallback", desc: "GRIB2 grids / BUFR observations." },
  { ext: ["vot"], name: "VOTable (Astronomy)", cat: "scientific", viewer: "xml" },
  { ext: ["pha", "arf", "rmf"], name: "X-ray Astronomy Response Files", cat: "scientific", viewer: "fallback" },
  { ext: ["fchk", "wfn", "molden", "xsf", "axsf", "cube"], name: "Quantum Chemistry Output", cat: "scientific", viewer: "text", desc: "Gaussian/ORBITAL/MOLDEN grids & wavefunctions." },
  { ext: ["rst7", "inpcrd", "prmtop", "mdcrd", "tng", "edr"], name: "AMBER / GROMACS Dynamics", cat: "scientific", viewer: "fallback" },
  { ext: ["edf"], name: "European Data Format Biosignal", cat: "scientific", viewer: "fallback", desc: "Polygraph recordings (EEG/ECG)." },
  { ext: ["vhdr", "vmrk", "fdt"], name: "BrainVision Recording", cat: "scientific", viewer: "text" },
  { ext: ["fif"], name: "MNE-Python FIFF Recording", cat: "scientific", viewer: "fallback" },
  { ext: ["snirf", "nirs"], name: "fNIRS Neuroimaging", cat: "scientific", viewer: "fallback" },
  { ext: ["trk", "tck"], name: "Tractography Streamlines", cat: "scientific", viewer: "three3d" },
  { ext: ["gii", "annot", "curv", "sulc", "mgh", "mgz", "mnc", "mnc2", "brik"], name: "Neuroimaging Surface/Volume Data", cat: "scientific", viewer: "fallback" },
  { ext: ["cel", "gct", "gmt", "sif", "cys", "gexf", "graphml", "xgmml", "gv"], name: "Genomics & Network Interchange", cat: "data", viewer: "text", desc: "Expression matrices, gene sets, Cytoscape/GraphML networks." },
  { ext: ["sbml", "sedml", "neuroml", "nml", "nml2", "bngl", "cellml"], name: "Systems Biology Model", cat: "scientific", viewer: "xml" },
  { ext: ["hl7"], name: "Healthcare Message / Document", cat: "scientific", viewer: "text", desc: "HL7 v2 messages and CDA documents." },
  { ext: ["imzml", "ibd"], name: "Imaging Mass Spectrometry", cat: "scientific", viewer: "fallback" },
  { ext: ["protxml", "pepxml"], name: "Proteomics Identifications", cat: "scientific", viewer: "xml" },
  { ext: ["hdfeos5"], name: "HDF-EOS5 Earth Observation", cat: "scientific", viewer: "fallback", sig: "89 48 44 46" },

  // ---------------- ML / AI ----------------
  { ext: ["onnx"], name: "Open Neural Network Exchange", cat: "data", viewer: "fallback", mime: "application/protobuf", desc: "Portable ML model graph." },
  { ext: ["tflite"], name: "TensorFlow Lite Model", cat: "data", viewer: "fallback", desc: "FlatBuffer-serialized mobile model." },
  { ext: ["tfrecord", "tfevents"], name: "TensorFlow Records / Event Log", cat: "data", viewer: "fallback" },
  { ext: ["ckpt", "meta", "pb", "index"], name: "TensorFlow Checkpoint & Graph", cat: "data", viewer: "fallback" },
  { ext: ["pt", "pth"], name: "PyTorch Model / Weights", cat: "data", viewer: "fallback", desc: "Pickle-based tensor archives." },
  { ext: ["pkl", "pickle", "joblib"], name: "Python Serialized Object", cat: "data", viewer: "fallback", sig: "80 ?? 95", desc: "Pickle / joblib blobs." },
  { ext: ["safetensors"], name: "Safetensors Model", cat: "data", viewer: "fallback", desc: "Zero-copy tensor format with JSON header." },
  { ext: ["gguf", "ggml"], name: "llama.cpp Model Quantization", cat: "data", viewer: "fallback", sig: "47 47 55 46" },
  { ext: ["npy", "npz"], name: "NumPy Array", cat: "data", viewer: "fallback", sig: "93 4E 55 4D 50 59" },
  { ext: ["keras"], name: "Keras Model Archive", cat: "data", viewer: "fallback", sig: "50 4B 03 04" },
  { ext: ["mlmodel", "mlpackage"], name: "Core ML Model", cat: "data", viewer: "fallback" },
  { ext: ["trt", "engine"], name: "TensorRT Compiled Engine", cat: "data", viewer: "fallback" },
  { ext: ["rknn", "mnn", "dlc"], name: "Edge/SoC ML Model", cat: "data", viewer: "fallback" },
  { ext: ["caffemodel"], name: "Caffe Model & Definition", cat: "data", viewer: "fallback" },
  { ext: ["pmml", "wts"], name: "Predictive Model Markup", cat: "data", viewer: "xml" },

  // ---------------- geo / GIS ----------------
  { ext: ["gpkg"], name: "OGC GeoPackage", cat: "geo", viewer: "sqlite", sig: "53 51 4C 69 74 65 20 66 6F 72 6D 61 74 20 33 00", desc: "SQLite-based geospatial container." },
  { ext: ["mbtiles"], name: "MBTiles Raster/Vector Tiles", cat: "geo", viewer: "sqlite", sig: "53 51 4C 69 74 65 20 66 6F 72 6D 61 74 20 33 00" },
  { ext: ["pmtiles"], name: "PMTiles Single-File Archive", cat: "geo", viewer: "fallback", sig: "50 4D 54 69 6C 65 73" },
  { ext: ["vrt"], name: "GDAL Virtual Dataset", cat: "geo", viewer: "xml" },
  { ext: ["e00", "sbn", "sbx", "prj", "cpg", "lyr", "mxd"], name: "ESRI Shape/Project Components", cat: "geo", viewer: "text" },
  { ext: ["qgs", "qgz", "qpj"], name: "QGIS Project", cat: "geo", viewer: "fallback" },
  { ext: ["wkt", "wkb"], name: "Well-Known Text/Binary Geometry", cat: "geo", viewer: "text" },
  { ext: ["bil", "bip", "bsq"], name: "Binary Raster Layout", cat: "geo", viewer: "fallback" },
  { ext: ["hgt", "ter"], name: "Elevation Grid (SRTM/Terragen)", cat: "geo", viewer: "fallback", desc: "Raw heightfields (SRTM .hgt, Terragen .ter)." },
  { ext: ["nmea", "nema"], name: "NMEA 0183 GPS Log", cat: "geo", viewer: "text", desc: "$GPGGA-style sentences." },
  { ext: ["rnx"], name: "RINEX GNSS Observation", cat: "geo", viewer: "text" },
  { ext: ["gpi"], name: "Garmin Point of Interest", cat: "geo", viewer: "fallback" },
  { ext: ["sbp", "ubx"], name: "GNSS Receiver Binary Log", cat: "geo", viewer: "fallback", sig: "B5 62" },
  { ext: ["las", "laz"], name: "LiDAR Point Cloud", cat: "geo", viewer: "three3d", sig: "4C 41 53 46" },
  { ext: ["e57", "pcd"], name: "3D Scan Point Cloud", cat: "3d", viewer: "three3d" },
  { ext: ["cityjson", "ifc", "ifcxml", "ifczip"], name: "BIM / City Model", cat: "3d", viewer: "json" },
  { ext: ["gbxml"], name: "Green Building XML", cat: "3d", viewer: "xml" },

  // ---------------- CAD / EDA ----------------
  { ext: ["gtl", "gbl", "gts", "gto", "gbo", "gbp", "gpb", "gtp", "pho"], name: "Gerber PCB Layer", cat: "code", viewer: "code", desc: "RS-274X copper/mask/silk layers." },
  { ext: ["drl", "drd"], name: "Excellon Drill File", cat: "code", viewer: "code" },
  { ext: ["kicad_pcb", "kicad_sch", "kicad_pro", "kicad_wks", "kicad_mod"], name: "KiCad Design File", cat: "code", viewer: "code" },
  { ext: ["brd", "sch", "lbr"], name: "EAGLE Circuit Design", cat: "code", viewer: "xml", sig: "3C 3F 78 6D 6C" },
  { ext: ["schdoc", "pcbdoc", "pcblib", "schlib", "prjpcb"], name: "Altium Designer Document", cat: "code", viewer: "fallback" },
  { ext: ["dsn"], name: "Specctra Design / OrCAD", cat: "code", viewer: "code" },
  { ext: ["fzz", "fzp"], name: "Fritzing Design", cat: "code", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["asy", "cir", "net", "spi"], name: "SPICE Circuit", cat: "code", viewer: "code" },
  { ext: ["sldprt", "sldasm", "slddrw"], name: "SolidWorks Part/Assembly", cat: "3d", viewer: "fallback" },
  { ext: ["ipt", "iam", "idw"], name: "Autodesk Inventor", cat: "3d", viewer: "fallback" },
  { ext: ["catpart", "catproduct", "cgr", "3dxml"], name: "CATIA / Dassault Model", cat: "3d", viewer: "fallback" },
  { ext: ["prt"], name: "CAD Part (Creo/NX)", cat: "3d", viewer: "fallback" },
  { ext: ["x_t", "x_b", "jt"], name: "Parasolid / JT Model", cat: "3d", viewer: "fallback" },
  { ext: ["f3d", "f3z", "fcstd"], name: "Fusion / FreeCAD Document", cat: "3d", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["3dm"], name: "Rhino 3D Model", cat: "3d", viewer: "fallback" },
  { ext: ["rvt", "rfa", "rte", "pla", "pln"], name: "Revit / ArchiCAD Project", cat: "3d", viewer: "fallback" },
  { ext: ["def", "lef", "gds", "gdsii", "oas", "spef"], name: "VLSI Layout & Timing", cat: "code", viewer: "fallback", desc: "Cadence LEF/DEF, GDSII masks, timing." },
  { ext: ["sla"], name: "Slic3r/Sla Printer Profile", cat: "code", viewer: "code" },

  // ---------------- more code / config ----------------
  { ext: ["purs"], name: "PureScript Source", cat: "code", viewer: "code" },
  { ext: ["idr", "lidr", "agda", "lagda"], name: "Idris / Agda Proof Source", cat: "code", viewer: "code" },
  { ext: ["lean", "hlean"], name: "Lean Theorem Prover", cat: "code", viewer: "code" },
  { ext: ["pro", "prolog"], name: "Prolog Source", cat: "code", viewer: "code", mime: "text/x-prolog" },
  { ext: ["4th", "fth", "forth"], name: "Forth Source", cat: "code", viewer: "code" },
  { ext: ["elm"], name: "Elm Source", cat: "code", viewer: "code" },
  { ext: ["cr"], name: "Crystal Source", cat: "code", viewer: "code" },
  { ext: ["lfe"], name: "Lisp Flavoured Erlang", cat: "code", viewer: "code" },
  { ext: ["bal"], name: "Ballerina Source", cat: "code", viewer: "code" },
  { ext: ["bsl", "os"], name: "1C:Enterprise Script", cat: "code", viewer: "code" },
  { ext: ["dhall", "jsonnet", "libsonnet"], name: "Structured Configuration Language", cat: "config", viewer: "code" },
  { ext: ["star"], name: "Starlark Build Script", cat: "code", viewer: "code" },
  { ext: ["rego"], name: "Rego Policy (OPA)", cat: "code", viewer: "code" },
  { ext: ["ly"], name: "LilyPond Music Notation", cat: "audio", viewer: "code" },
  { ext: ["abc"], name: "ABC Music Notation", cat: "audio", viewer: "code" },
  { ext: ["red", "reds", "rebol", "rexx"], name: "Rebol / Red / Rexx Source", cat: "code", viewer: "code" },
  { ext: ["nix"], name: "Nix Expression", cat: "config", viewer: "code", mime: "text/x-nix" },
  { ext: ["typ"], name: "Typst Document", cat: "document", viewer: "code" },
  { ext: ["sls"], name: "SaltStack State", cat: "config", viewer: "code" },
  { ext: ["tf", "tfvars", "hcl"], name: "Terraform / HCL", cat: "config", viewer: "code" },
  { ext: ["pony"], name: "Pony Source", cat: "code", viewer: "code" },
  { ext: ["applescript", "scpt"], name: "AppleScript", cat: "code", viewer: "code" },
  { ext: ["ino"], name: "Arduino Sketch", cat: "code", viewer: "code" },
  { ext: ["cl"], name: "Common Lisp Source", cat: "code", viewer: "code" },
  { ext: ["robot"], name: "Robot Framework Suite", cat: "code", viewer: "code" },
  { ext: ["feature"], name: "Cucumber Feature", cat: "code", viewer: "code" },
  { ext: ["cwl"], name: "Common Workflow Language", cat: "code", viewer: "code" },
  { ext: ["wdl", "nf"], name: "Pipeline Definition (Snakemake/WDL/Nextflow)", cat: "code", viewer: "code" },
  { ext: ["avdl", "thrift", "capnp", "fbs"], name: "Schema Definition Language", cat: "code", viewer: "code" },
  { ext: ["pike"], name: "Pike Source", cat: "code", viewer: "code" },
  { ext: ["q"], name: "q/kdb+ Database Script", cat: "code", viewer: "code" },
  { ext: ["ipynb"], name: "Jupyter Notebook", cat: "data", viewer: "json", mime: "application/x-ipynb+json", desc: "Cells of executable code + JSON output." },
  { ext: ["qmd"], name: "Quarto Document", cat: "document", viewer: "markdown" },
  { ext: ["dvc"], name: "DVC Stage Definition", cat: "config", viewer: "code" },
  { ext: ["xspf", "mpcpl", "b4s", "kpl", "jspf", "smil"], name: "XML/Shared Playlist", cat: "audio", viewer: "xml", mime: "application/xspf+xml" },
  { ext: ["nib", "storyboard", "xib", "entitlements", "mobileconfig"], name: "Apple Developer Resource", cat: "code", viewer: "xml" },
  { ext: ["wxs", "iss", "nsi", "nsh"], name: "Installer Script (WiX/Inno/NSIS)", cat: "config", viewer: "code" },
  { ext: ["service", "socket", "timer", "mount", "rules"], name: "systemd / udev Unit", cat: "system", viewer: "code", mime: "text/plain" },
  { ext: ["rockspec", "podspec", "cabal"], name: "Package Manifest", cat: "config", viewer: "code" },
  { ext: ["tool-versions", "python-version", "ruby-version", "node-version", "nvmrc", "rvmrc", "rspec", "gitmodules", "gitkeep", "mailmap"], name: "Development Dotfile", cat: "config", viewer: "text", desc: "Toolchain pinning & repo metadata conventions." },
  { ext: ["wl", "wls", "wri"], name: "Wolfram Language Files", cat: "code", viewer: "code" },

  // ---------------- misc ----------------
];
