import type { RawFormat } from "@/lib/types";

/** AUTHORED EXPANSION H — FPGA/EDA, instrument data, embroidery, cameras, DAW, retro disks, VFP/Paradox, tooling dotfiles. */
export const EXTRA_FORMATS_H: RawFormat[] = [
  { ext: ["xpr"], name: "Vivado Project", cat: "code", viewer: "xml", mime: "application/xml", desc: "Xilinx Vivado ISE project description (XML)." },
  { ext: ["xsa"], name: "Xilinx Software Archive", cat: "system", viewer: "archive", sig: "50 4B 03 04", desc: "Vivado hardware/software export (zip)." },
  { ext: ["ncd"], name: "Xilinx Native Circuit Description", cat: "system", viewer: "fallback", desc: "Post-place-and-route FPGA netlist." },
  { ext: ["ngc"], name: "Xilinx NGC Netlist", cat: "system", viewer: "fallback", desc: "Binary EDIF-like netlist for Xilinx tools." },
  { ext: ["ngd"], name: "Xilinx NGD Database", cat: "system", viewer: "fallback", desc: "Post-translate unified design database." },
  { ext: ["ise"], name: "Xilinx ISE Project", cat: "code", viewer: "xml", desc: "ISE Design Suite project file." },
  { ext: ["xpa"], name: "Xilinx Project Archive", cat: "archive", viewer: "archive", sig: "50 4B 03 04", desc: "ISE project archive bundle." },
  { ext: ["wcfg"], name: "ISE Wave Config", cat: "code", viewer: "xml", desc: "Xilinx simulator waveform configuration." },
  { ext: ["twr"], name: "Xilinx Timing Report", cat: "code", viewer: "text", desc: "Static timing analysis report." },
  { ext: ["drc"], name: "Xilinx DRC Report", cat: "code", viewer: "text", desc: "Design rule check report." },
  { ext: ["qpf"], name: "Quartus Project File", cat: "code", viewer: "text", desc: "Intel/Altera Quartus Prime project." },
  { ext: ["lpf"], name: "Lattice Preference File", cat: "code", viewer: "text", desc: "Lattice Diamond/ispLEVER constraints." },
  { ext: ["ddc"], name: "Synopsys DDC Database", cat: "system", viewer: "fallback", desc: "Design Compiler mapped netlist database." },
  { ext: ["vlg"], name: "Verilog Source (vlg)", cat: "code", viewer: "text", desc: "Alternate Verilog extension." },
  { ext: ["vho"], name: "VHDL Netlist", cat: "code", viewer: "text", desc: "Xilinx-generated structural VHDL." },
  { ext: ["vht"], name: "VHDL Testbench", cat: "code", viewer: "text", desc: "Xilinx-generated simulation testbench." },
  { ext: ["va"], name: "Verilog-A Source", cat: "code", viewer: "text", desc: "Analog Verilog language source." },
  { ext: ["rbt"], name: "Raw Bitstream Text", cat: "system", viewer: "text", desc: "ASCII rendering of FPGA bitstream." },
  { ext: ["syn"], name: "Synplify Project", cat: "code", viewer: "fallback", desc: "Synplify synthesis project settings." },
  { ext: ["cof"], name: "MPLAB COFF Object", cat: "system", viewer: "fallback", desc: "Microchip PIC object/executable." },
  { ext: ["mcw"], name: "MPLAB Workspace", cat: "code", viewer: "fallback", desc: "Microchip MPLAB IDE workspace." },
  { ext: ["sby"], name: "SymbiYosys Script", cat: "code", viewer: "text", desc: "Formal verification task file." },
  { ext: ["ilang"], name: "Yosys Internal Netlist", cat: "code", viewer: "text", desc: "Yosys RTLIL text netlist." },
  { ext: ["aig"], name: "AIGER Binary", cat: "scientific", viewer: "fallback", sig: "61 69 67", desc: "Binary AND-inverter graph." },
  { ext: ["aag"], name: "AIGER ASCII", cat: "scientific", viewer: "text", sig: "61 61 67", desc: "ASCII AND-inverter graph." },
  { ext: ["btor"], name: "BTOR2 Model", cat: "code", viewer: "text", desc: "Word-level model for SMT solvers." },
  { ext: ["smt2"], name: "SMT-LIB v2 Script", cat: "code", viewer: "text", desc: "Satisfiability modulo theories input." },
  { ext: ["smt"], name: "SMT-LIB Script", cat: "code", viewer: "text", desc: "SMT solver benchmark format." },
  { ext: ["dimacs"], name: "DIMACS CNF", cat: "scientific", viewer: "text", desc: "Boolean satisfiability instance." },
  { ext: ["ys"], name: "Yosys Script", cat: "code", viewer: "text", desc: "Yosys synthesis command script." },
  { ext: ["bsdl"], name: "BSDL Boundary Scan", cat: "code", viewer: "text", desc: "IEEE 1149.1 device description." },
  { ext: ["ibis", "ibs"], name: "IBIS Model", cat: "code", viewer: "text", desc: "I/O buffer behavioral model." },
  { ext: ["do"], name: "ModelSim Macro", cat: "code", viewer: "text", desc: "Tcl simulation command file." },
  { ext: ["drf"], name: "Cadence Display Resources", cat: "code", viewer: "fallback", desc: "Virtuoso layer display table." },
  { ext: ["wdf"], name: "Renishaw WDF Raman", cat: "scientific", viewer: "fallback", desc: "Raman spectroscopy dataset." },
  { ext: ["spa"], name: "Bruker OPUS Spectrum", cat: "scientific", viewer: "fallback", desc: "FT-IR/FT-NIR OPUS data file." },
  { ext: ["baf"], name: "Bruker BAF Data", cat: "scientific", viewer: "fallback", desc: "Bruker Daltonics flex mass spectra." },
  { ext: ["tdf"], name: "Bruker TIMS Data", cat: "scientific", viewer: "fallback", desc: "Trapped ion mobility data." },
  { ext: ["yep"], name: "Bruker YEP Data", cat: "scientific", viewer: "fallback", desc: "Bruker mass calibrant data." },
  { ext: ["brml"], name: "Bruker XRD ML", cat: "scientific", viewer: "archive", sig: "50 4B 03 04", desc: "Diffractogram raw data (zip)." },
  { ext: ["uxd"], name: "Bruker UXD Raw", cat: "scientific", viewer: "fallback", desc: "X-ray diffraction raw data." },
  { ext: ["ooi"], name: "Ocean Optics Spectrum", cat: "scientific", viewer: "fallback", desc: "OOIBase32 spectrometer data." },
  { ext: ["spe"], name: "Princeton Instruments SPE", cat: "scientific", viewer: "fallback", desc: "CCD detector frame data." },
  { ext: ["ims"], name: "Imaris Dataset", cat: "scientific", viewer: "fallback", desc: "Bitplane microscopy scene." },
  { ext: ["oib"], name: "Olympus OIB Image", cat: "scientific", viewer: "fallback", desc: "Fluoview confocal container." },
  { ext: ["lei"], name: "Leica Image", cat: "scientific", viewer: "fallback", desc: "LAS/SP legacy confocal image." },
  { ext: ["aim"], name: "Zeiss AIM Image", cat: "scientific", viewer: "fallback", desc: "LSM 510 confocal data." },
  { ext: ["mvd2"], name: "Volocity MVD2", cat: "scientific", viewer: "fallback", desc: "Volocity microscopy library." },
  { ext: ["mhd", "mha"], name: "MetaImage Header/Data", cat: "scientific", viewer: "text", desc: "ITK medical image pair." },
  { ext: ["acqus", "acqu"], name: "Bruker NMR Parameters", cat: "scientific", viewer: "text", desc: "Acquisition parameter file." },
  { ext: ["procs"], name: "Bruker Processing Parameters", cat: "scientific", viewer: "text", desc: "NMR processing parameters." },
  { ext: ["procpar"], name: "Varian Procpar", cat: "scientific", viewer: "text", desc: "Agilent/Varian NMR parameters." },
  { ext: ["ncl"], name: "NCAR Command Language", cat: "scientific", viewer: "text", desc: "NCL analysis script." },
  { ext: ["lp"], name: "LP Format", cat: "scientific", viewer: "text", desc: "CPLEX linear program model." },
  { ext: ["mps"], name: "MPS Mathematical Format", cat: "scientific", viewer: "text", desc: "Linear programming problem." },
  { ext: ["nl"], name: "AMPL NL", cat: "scientific", viewer: "fallback", desc: "Solver-independent optimization problem." },
  { ext: ["gms"], name: "GAMS Model", cat: "scientific", viewer: "text", desc: "General algebraic modeling source." },
  { ext: ["gdx"], name: "GAMS Data Exchange", cat: "scientific", viewer: "fallback", desc: "GAMS binary data container." },
  { ext: ["cdb"], name: "ANSYS Archive CDB", cat: "scientific", viewer: "text", desc: "FE model geometry/states (MAPDL CDWRITE)." },
  { ext: ["odb"], name: "Abaqus Output Database", cat: "scientific", viewer: "fallback", desc: "Simulia results database." },
  { ext: ["cae"], name: "Abaqus Model Database", cat: "scientific", viewer: "fallback", desc: "Simulia CAE model file." },
  { ext: ["fil"], name: "Abaqus Results File", cat: "scientific", viewer: "fallback", desc: "Binary analysis results." },
  { ext: ["sta"], name: "Abaqus Status File", cat: "scientific", viewer: "text", desc: "Increment/iteration status log." },
  { ext: ["f06"], name: "NASTRAN Output", cat: "scientific", viewer: "text", desc: "Analysis print output." },
  { ext: ["dball"], name: "NASTRAN Database", cat: "scientific", viewer: "fallback", desc: "Scratch/master database." },
  { ext: ["tr0"], name: "Spectre/HSPICE Transient", cat: "scientific", viewer: "fallback", desc: "Waveform analysis output." },
  { ext: ["ac0"], name: "Spectre AC Analysis", cat: "scientific", viewer: "fallback", desc: "AC sweep waveform data." },
  { ext: ["sw0"], name: "Spectre DC Sweep", cat: "scientific", viewer: "fallback", desc: "DC sweep waveform data." },
  { ext: ["dc0"], name: "Spectre DC Analysis", cat: "scientific", viewer: "fallback", desc: "DC operating point data." },
  { ext: ["st0"], name: "Spectre Status", cat: "scientific", viewer: "text", desc: "Simulation status output." },
  { ext: ["mt0", "me0"], name: "HSPICE Measurements", cat: "scientific", viewer: "text", desc: "Circuit measurement printout." },
  { ext: ["ic0"], name: "HSPICE Initial Conditions", cat: "scientific", viewer: "text", desc: "Node voltages at analysis start." },
  { ext: ["s1p"], name: "Touchstone 1-Port", cat: "scientific", viewer: "text", desc: "S-parameter network data." },
  { ext: ["s2p"], name: "Touchstone 2-Port", cat: "scientific", viewer: "text", desc: "Two-port S-parameters." },
  { ext: ["s3p"], name: "Touchstone 3-Port", cat: "scientific", viewer: "text", desc: "Three-port S-parameters." },
  { ext: ["s4p"], name: "Touchstone 4-Port", cat: "scientific", viewer: "text", desc: "Four-port S-parameters." },
  { ext: ["ies"], name: "IES Photometric", cat: "scientific", viewer: "text", desc: "Luminaire intensity distribution." },
  { ext: ["ldt"], name: "Eulumdat Photometric", cat: "scientific", viewer: "text", desc: "European luminaire data." },
  { ext: ["fmu"], name: "Functional Mock-up Unit", cat: "scientific", viewer: "archive", sig: "50 4B 03 04", desc: "Co-simulation model exchange package." },
  { ext: ["ksc"], name: "Korg Script", cat: "audio", viewer: "text", desc: "Triton/Trinity sample list script." },
  { ext: ["kmp"], name: "Korg Multisample", cat: "audio", viewer: "fallback", desc: "Korg multisample assignment." },
  { ext: ["ksf"], name: "Korg Sample File", cat: "audio", viewer: "fallback", desc: "Korg raw sample data." },
  { ext: ["pcg"], name: "Korg PCG Bank", cat: "audio", viewer: "fallback", desc: "Program/combination/global data." },
  { ext: ["akp"], name: "Akai Program", cat: "audio", viewer: "fallback", desc: "S1000/S3000 sampler program." },
  { ext: ["esx"], name: "Korg Electribe ESX", cat: "audio", viewer: "fallback", desc: "Electribe ESX pattern/song." },
  { ext: ["ens"], name: "Reaktor Ensemble", cat: "audio", viewer: "fallback", desc: "Native Instruments Reaktor instrument." },
  { ext: ["sd2"], name: "Sound Designer II", cat: "audio", viewer: "fallback", desc: "Digidesign SDII audio with resource fork." },
  { ext: ["m1v"], name: "MPEG-1 Video ES", cat: "video", viewer: "video", mime: "video/mpeg", desc: "Elementary video stream." },
  { ext: ["m2a"], name: "MPEG-2 Audio ES", cat: "audio", viewer: "audio", mime: "audio/mpeg", desc: "MPEG-2 audio elementary stream." },
  { ext: ["ssif"], name: "Blu-ray SSIF", cat: "video", viewer: "fallback", desc: "Stereoscopic interleaved stream." },
  { ext: ["rp"], name: "RealPix", cat: "video", viewer: "text", desc: "RealPlayer image markup." },
  { ext: ["nra"], name: "Nero Audio Compilation", cat: "other", viewer: "fallback", desc: "Nero Burning ROM CD project." },
  { ext: ["mks"], name: "Matroska Subtitles", cat: "subtitle", viewer: "fallback", desc: "Subtitle-only Matroska stream." },
  { ext: ["ac4"], name: "Dolby AC-4", cat: "audio", viewer: "audio", desc: "Broadcast object audio codec." },
  { ext: ["mhm"], name: "MPEG-H MHAS", cat: "audio", viewer: "fallback", desc: "3D audio bitstream segment." },
  { ext: ["imy"], name: "iMelody", cat: "audio", viewer: "text", desc: "Monophonic ringtone text format." },
  { ext: ["rtttl"], name: "RTTTL Ringtone", cat: "audio", viewer: "text", desc: "Ring Tone Text Transfer Language." },
  { ext: ["rtx"], name: "RTX Ringtone", cat: "audio", viewer: "fallback", desc: "Binary RTTTL variant." },
  { ext: ["qcp"], name: "Qualcomm QCP", cat: "audio", viewer: "audio", sig: "52 49 46 46", desc: "PureVoice EVRC audio." },
  { ext: ["amz"], name: "Amazon MP3 Download", cat: "audio", viewer: "fallback", desc: "Amazon music store container." },
  { ext: ["fsc"], name: "FL Studio Score", cat: "audio", viewer: "fallback", desc: "Piano roll score data." },
  { ext: ["tracktion"], name: "Tracktion Project", cat: "audio", viewer: "fallback", desc: "Tracktion DAW session." },
  { ext: ["ardour"], name: "Ardour Session", cat: "audio", viewer: "xml", desc: "Ardour DAW project XML." },
  { ext: ["h2song"], name: "Hydrogen Song", cat: "audio", viewer: "xml", desc: "Drum machine pattern project." },
  { ext: ["mmp"], name: "LMMS Project", cat: "audio", viewer: "xml", desc: "LMMS uncompressed project." },
  { ext: ["qtr"], name: "Qtractor Session", cat: "audio", viewer: "xml", desc: "Qtractor DAW session file." },
  { ext: ["zpj"], name: "Zrythm Project", cat: "audio", viewer: "json", desc: "Zrythm project JSON." },
  { ext: ["plg"], name: "Sibelius Plug-in", cat: "audio", viewer: "fallback", desc: "Sibelius Manuscript plug-in." },
  { ext: ["fti"], name: "FamiTracker Instrument", cat: "audio", viewer: "fallback", desc: "NES instrument definition." },
  { ext: ["0cc"], name: "0CC-FamiTracker Module", cat: "audio", viewer: "fallback", desc: "FamiTracker fork module." },
  { ext: ["xiz"], name: "Renoise Instrument", cat: "audio", viewer: "fallback", desc: "XRNI-style instrument." },
  { ext: ["dspreset"], name: "Decent Sampler Preset", cat: "audio", viewer: "xml", desc: "Sample library mapping." },
  { ext: ["dslibrary"], name: "Decent Sampler Library", cat: "audio", viewer: "xml", desc: "Instrument library manifest." },
  { ext: ["aimppl"], name: "AIMP Playlist", cat: "audio", viewer: "text", desc: "AIMP player playlist." },
  { ext: ["ins"], name: "LaTeX DocStrip Installer", cat: "document", viewer: "text", desc: "Package installer input for .dtx." },
  { ext: ["aux"], name: "LaTeX Auxiliary", cat: "document", viewer: "text", desc: "Cross-reference memory of a LaTeX run." },
  { ext: ["lof"], name: "LaTeX List of Figures", cat: "document", viewer: "text", desc: "Figures list generated data." },
  { ext: ["lot"], name: "LaTeX List of Tables", cat: "document", viewer: "text", desc: "Tables list generated data." },
  { ext: ["ind"], name: "MakeIndex Index", cat: "document", viewer: "text", desc: "Sorted index entries." },
  { ext: ["ilg"], name: "MakeIndex Log", cat: "document", viewer: "text", desc: "MakeIndex run log." },
  { ext: ["blg"], name: "BibTeX Log", cat: "document", viewer: "text", desc: "Bibliography build log." },
  { ext: ["glo"], name: "LaTeX Glossary", cat: "document", viewer: "text", desc: "Glossary entries data." },
  { ext: ["xdv"], name: "XeTeX DVI", cat: "document", viewer: "fallback", desc: "XeTeX device-independent output." },
  { ext: ["fmt"], name: "TeX Format Dump", cat: "font", viewer: "fallback", desc: "Preloaded TeX engine format." },
  { ext: ["rrd"], name: "ERDAS Pyramid Layer", cat: "geo", viewer: "fallback", desc: "Reduced-resolution overviews." },
  { ext: ["ige"], name: "ERDAS Large Image", cat: "geo", viewer: "fallback", desc: "IMG raster over 2GB split." },
  { ext: ["avl"], name: "ArcView Legend", cat: "geo", viewer: "text", desc: "ArcView 3 symbology file." },
  { ext: ["apr"], name: "ArcView Project", cat: "geo", viewer: "text", desc: "ArcView 3 project document." },
  { ext: ["qix"], name: "Shapefile Quadtree Index", cat: "geo", viewer: "fallback", desc: "shapelib spatial index." },
  { ext: ["ers"], name: "ER Mapper Header", cat: "geo", viewer: "text", desc: "ER Mapper raster header." },
  { ext: ["sgrd"], name: "SAGA Grid", cat: "geo", viewer: "fallback", desc: "SAGA GIS raster format." },
  { ext: ["sdat"], name: "SAGA Data", cat: "geo", viewer: "fallback", desc: "SAGA binary grid values." },
  { ext: ["gri"], name: "DivaGIS Grid", cat: "geo", viewer: "fallback", desc: "DivaGIS raster grid." },
  { ext: ["mdr"], name: "Garmin Map Data", cat: "geo", viewer: "fallback", desc: "Garmin map subfile." },
  { ext: ["tdb"], name: "Garmin Terrain Database", cat: "geo", viewer: "fallback", desc: "Map overview index." },
  { ext: ["lbl"], name: "Garbin Label Data", cat: "geo", viewer: "fallback", desc: "Garmin map label subfile." },
  { ext: ["jnx"], name: "Garmin BirdsEye Imagery", cat: "geo", viewer: "fallback", desc: "Satellite raster map." },
  { ext: ["gemf"], name: "GEMF Offline Map", cat: "geo", viewer: "fallback", desc: "OSMDroid tile archive." },
  { ext: ["kap"], name: "BSB Nautical Chart", cat: "geo", viewer: "text", desc: "Raster chart with text header." },
  { ext: ["000"], name: "S-57 Electronic Chart", cat: "geo", viewer: "fallback", desc: "IHO ENC dataset cell." },
  { ext: ["ain", "aih"], name: "ESRI Coverage Index", cat: "geo", viewer: "fallback", desc: "ArcInfo coverage attribute index." },
  { ext: ["pbf"], name: "OSM Protocol Buffer", cat: "geo", viewer: "fallback", desc: "Compressed OpenStreetMap planet extract." },
  { ext: ["dsb"], name: "Barudan Embroidery", cat: "other", viewer: "fallback", desc: "Barudan binary stitch format." },
  { ext: ["phc"], name: "Brother Embroidery", cat: "other", viewer: "fallback", desc: "Brother stitch pattern." },
  { ext: ["shv"], name: "Husqvarna Viking Design", cat: "other", viewer: "fallback", desc: "Viking/Pfaff stitch file." },
  { ext: ["ksm"], name: "Pfaff Embroidery", cat: "other", viewer: "fallback", desc: "Pfaff KSM stitch data." },
  { ext: ["zsk"], name: "ZSK Embroidery", cat: "other", viewer: "fallback", desc: "ZSK stitch format." },
  { ext: ["emb"], name: "Wilcom Embroidery Design", cat: "other", viewer: "fallback", desc: "ES Designer native format." },
  { ext: ["u01"], name: "Barudan FDR Tape", cat: "other", viewer: "fallback", desc: "Barudan native stitch data." },
  { ext: ["bro"], name: "Brother Stitch (bro)", cat: "other", viewer: "fallback", desc: "Brother/Babylock older format." },
  { ext: ["dpl"], name: "Datamax Printer Language", cat: "other", viewer: "text", desc: "Datamax label script." },
  { ext: ["pjl"], name: "HP Printer Job Language", cat: "other", viewer: "text", desc: "Printer job control stream." },
  { ext: ["rml"], name: "Roland Machine Language", cat: "code", viewer: "text", desc: "Roland miller/printer control." },
  { ext: ["cb"], name: "CamBam CAD", cat: "code", viewer: "xml", desc: "CamBam CAD/CAM document." },
  { ext: ["crv"], name: "Vectric VCarve", cat: "code", viewer: "fallback", desc: "VCarve/Pro cut file." },
  { ext: ["crv3d"], name: "Vectric Aspire 3D", cat: "code", viewer: "fallback", desc: "Aspire 3D relief file." },
  { ext: ["k3d"], name: "K-3D Document", cat: "3d", viewer: "xml", desc: "K-3D modeling document." },
  { ext: ["unity"], name: "Unity Scene", cat: "game", viewer: "text", desc: "Unity serialized YAML scene." },
  { ext: ["prefab"], name: "Unity Prefab", cat: "game", viewer: "text", desc: "Reusable GameObject asset." },
  { ext: ["asmdef"], name: "Unity Assembly Definition", cat: "game", viewer: "json", desc: "C# compilation scope." },
  { ext: ["asmref"], name: "Unity Assembly Reference", cat: "game", viewer: "json", desc: "Reference to an asmdef." },
  { ext: ["controller"], name: "Unity Animator Controller", cat: "game", viewer: "text", desc: "State machine asset." },
  { ext: ["cginc"], name: "Unity Shader Include", cat: "code", viewer: "text", desc: "Cg/HLSL include chunk." },
  { ext: ["uxml"], name: "Unity UI Markup", cat: "game", viewer: "xml", desc: "UI Toolkit layout." },
  { ext: ["uss"], name: "Unity UI Stylesheet", cat: "game", viewer: "text", desc: "UI Toolkit styling." },
  { ext: ["unitypackage"], name: "Unity Package", cat: "game", viewer: "archive", sig: "1F 8B 08", desc: "Gzipped asset bundle." },
  { ext: ["vta"], name: "Valve Flex Animation", cat: "3d", viewer: "text", desc: "Source engine vertex animation." },
  { ext: ["dmx"], name: "Valve DMX Data", cat: "3d", viewer: "fallback", desc: "SF2/Source serialized data." },
  { ext: ["wmo"], name: "WoW World Map Object", cat: "game", viewer: "fallback", desc: "Blizzard geometry set." },
  { ext: ["zpr"], name: "ZBrush Project", cat: "3d", viewer: "fallback", desc: "Pixologic scene state." },
  { ext: ["ztl"], name: "ZBrush Tool", cat: "3d", viewer: "fallback", desc: "Pixologic sculpting tool." },
  { ext: ["rvm"], name: "AVEVA RVM Model", cat: "3d", viewer: "fallback", desc: "PDMS plant model export." },
  { ext: ["dft"], name: "Solid Edge Draft", cat: "3d", viewer: "fallback", desc: "Siemens drawing document." },
  { ext: ["slddrt"], name: "SolidWorks Drawing Template", cat: "3d", viewer: "fallback", desc: "Sheet format template." },
  { ext: ["sldlfp"], name: "SolidWorks Library Feature", cat: "3d", viewer: "fallback", desc: "Reusable feature element." },
  { ext: ["vda"], name: "VDA-FS Surface", cat: "3d", viewer: "fallback", desc: "German automotive geometry exchange." },
  { ext: ["xgl"], name: "XGL 3D Scene", cat: "3d", viewer: "three3d", desc: "XML 3D scene format." },
  { ext: ["zgl"], name: "ZGL Binary 3D", cat: "3d", viewer: "fallback", desc: "Binary XGL variant." },
  { ext: ["vwx"], name: "Vectorworks Document", cat: "3d", viewer: "fallback", desc: "Nemetschek CAD file." },
  { ext: ["mcd"], name: "MiniCAD Document", cat: "3d", viewer: "fallback", desc: "Vectorworks legacy format." },
  { ext: ["rvb"], name: "RhinoScript", cat: "code", viewer: "text", desc: "Rhinoceros VBScript macro." },
  { ext: ["feb"], name: "FEBio Model", cat: "scientific", viewer: "xml", desc: "Finite element biomechanics XML." },
  { ext: ["fcmacro"], name: "FreeCAD Macro", cat: "code", viewer: "text", desc: "Python automation script." },
  { ext: ["fcbak"], name: "FreeCAD Backup", cat: "code", viewer: "archive", sig: "50 4B 03 04", desc: "Autosaved FreeCAD document." },
  { ext: ["bphys"], name: "Blender Physics Cache", cat: "3d", viewer: "fallback", desc: "Baked point cache data." },
  { ext: ["mdd"], name: "Motion Designer Cache", cat: "3d", viewer: "fallback", desc: "Point oven mesh animation." },
  { ext: ["pc2"], name: "PointCache2", cat: "3d", viewer: "fallback", desc: "Per-vertex animation cache." },
  { ext: ["vrmesh"], name: "V-Ray Proxy Mesh", cat: "3d", viewer: "fallback", desc: "Chaos Group tetra-mesh cache." },
  { ext: ["vrimg"], name: "V-Ray Image", cat: "image", viewer: "fallback", desc: "Chaos render channel data." },
  { ext: ["vrscene"], name: "V-Ray Scene Export", cat: "3d", viewer: "text", desc: "Renderable scene description." },
  { ext: ["pp2"], name: "Poser Prop", cat: "3d", viewer: "fallback", desc: "Poser prop definition." },
  { ext: ["pz2"], name: "Poser Pose", cat: "3d", viewer: "fallback", desc: "Poser pose preset." },
  { ext: ["rsr"], name: "Poser Thumbnail", cat: "image", viewer: "fallback", desc: "Poser legacy preview image." },
  { ext: ["mpo"], name: "Multi-Picture Object", cat: "image", viewer: "image", sig: "FF D8 FF", desc: "Stereo multi-frame JPEG." },
  { ext: ["jps"], name: "Stereoscopic JPEG", cat: "image", viewer: "image", sig: "FF D8 FF", desc: "Side-by-side JPEG pair." },
  { ext: ["pns"], name: "Stereoscopic PNG", cat: "image", viewer: "image", sig: "89 50 4E 47", desc: "Side-by-side PNG pair." },
  { ext: ["hif"], name: "Canon HEIF", cat: "image", viewer: "fallback", desc: "Camera HEIF photo variant." },
  { ext: ["jxl"], name: "JPEG XL", cat: "image", viewer: "image", sig: "FF 0A", desc: "Next-gen ISO/IEC image codec." },
  { ext: ["jxs"], name: "JPEG XS", cat: "image", viewer: "fallback", sig: "FF 0B", desc: "Low-latency mezzanine codec." },
  { ext: ["bpg"], name: "Better Portable Graphics", cat: "image", viewer: "fallback", sig: "42 50 47 FB", desc: "HEVC-based image format." },
  { ext: ["mic"], name: "MS Image Composer", cat: "image", viewer: "fallback", desc: "Image Composer sprite document." },
  { ext: ["icb"], name: "Targa ICB", cat: "image", viewer: "image", desc: "Targa ICB industry variant." },
  { ext: ["procreate"], name: "Procreate Artwork", cat: "image", viewer: "archive", sig: "50 4B 03 04", desc: "Savage Interactive painting." },
  { ext: ["brush"], name: "Procreate Brush", cat: "image", viewer: "archive", sig: "50 4B 03 04", desc: "Procreate brush asset." },
  { ext: ["swatches"], name: "Procreate Swatches", cat: "image", viewer: "fallback", desc: "Color palette export." },
  { ext: ["clip"], name: "Clip Studio File", cat: "image", viewer: "fallback", desc: "Celsys layered artwork." },
  { ext: ["lip"], name: "Clip Studio Data", cat: "image", viewer: "fallback", desc: "Celsys material/settings." },
  { ext: ["sai"], name: "PaintTool SAI Image", cat: "image", viewer: "fallback", desc: "SYSTEMAX layered artwork." },
  { ext: ["sai2"], name: "PaintTool SAI v2 Image", cat: "image", viewer: "fallback", desc: "SYSTEMAX second-gen artwork." },
  { ext: ["afdesign"], name: "Affinity Designer Doc", cat: "image", viewer: "fallback", desc: "Serif vector document." },
  { ext: ["afphoto"], name: "Affinity Photo Doc", cat: "image", viewer: "fallback", desc: "Serif raster document." },
  { ext: ["afpub"], name: "Affinity Publisher Doc", cat: "document", viewer: "fallback", desc: "Serif layout document." },
  { ext: ["afassets"], name: "Affinity Assets", cat: "image", viewer: "fallback", desc: "Serif asset collection." },
  { ext: ["g3"], name: "G3 Fax Image", cat: "image", viewer: "fallback", desc: "CCITT Group 3 fax raster." },
  { ext: ["logicdata"], name: "Saleae Logic Capture", cat: "scientific", viewer: "fallback", desc: "Logic analyzer recording." },
  { ext: ["mof"], name: "WMI Managed Object Format", cat: "code", viewer: "text", desc: "CIM class definition source." },
  { ext: ["pp3"], name: "RawTherapee Sidecar", cat: "image", viewer: "text", desc: "Processing profile parameters." },
  { ext: ["dcs"], name: "Kodak DCS Image", cat: "image", viewer: "fallback", desc: "Digital camera system raw." },
  { ext: ["insp"], name: "Insta360 Photo", cat: "image", viewer: "fallback", sig: "FF D8 FF", desc: "360-degree still image." },
  { ext: ["insv"], name: "Insta360 Video", cat: "video", viewer: "video", desc: "360-degree camera footage." },
  { ext: ["lfp"], name: "Lytro Light Field Photo", cat: "image", viewer: "fallback", desc: "Living Picture raw stack." },
  { ext: ["lfr"], name: "Lytro Illum Raw", cat: "image", viewer: "fallback", desc: "Lytro Illum sensor data." },
  { ext: ["xmp"], name: "Extensible Metadata Platform", cat: "other", viewer: "xml", mime: "application/rdf+xml", desc: "Adobe sidecar metadata (RDF/XML)." },
  { ext: ["psqlrc"], name: "psql RC", cat: "config", viewer: "text", desc: "PostgreSQL client startup script." },
  { ext: ["gemrc"], name: "RubyGems RC", cat: "config", viewer: "code", desc: "Gem command configuration." },
  { ext: ["sbclrc"], name: "SBCL Init", cat: "config", viewer: "text", desc: "Steel Bank Common Lisp startup." },
  { ext: ["abclrc"], name: "ABCL Init", cat: "config", viewer: "text", desc: "Armed Bear Lisp startup." },
  { ext: ["eclrc"], name: "ECL Init", cat: "config", viewer: "text", desc: "Embeddable CL startup file." },
  { ext: ["guile"], name: "Guile Init", cat: "config", viewer: "text", desc: "GNU Guile startup script." },
  { ext: ["ghci"], name: "GHCi RC", cat: "config", viewer: "text", desc: "Haskell REPL startup commands." },
  { ext: ["tigrc"], name: "Tig RC", cat: "config", viewer: "text", desc: "Git text-mode UI config." },
  { ext: ["gitk"], name: "gitk Config", cat: "config", viewer: "text", desc: "gitk repository settings." },
  { ext: ["sassrc"], name: "Sass JS RC", cat: "config", viewer: "text", desc: "Dart/JS Sass options." },
  { ext: ["clang-format"], name: "Clang-Format Config", cat: "config", viewer: "code", desc: "C/C++ style rules." },
  { ext: ["clang-tidy"], name: "Clang-Tidy Config", cat: "config", viewer: "code", desc: "Static analyzer checks." },
  { ext: ["clangd"], name: "clangd Config", cat: "config", viewer: "code", desc: "clangd language server options." },
  { ext: ["dvcignore"], name: "DVC Ignore", cat: "config", viewer: "text", desc: "Data version control excludes." },
  { ext: ["mmd"], name: "Mermaid Diagram", cat: "code", viewer: "text", desc: "Flowchart/sequence diagram source." },
  { ext: ["http"], name: "HTTP Request File", cat: "code", viewer: "text", desc: "IntelliJ/VS Code REST client script." },
  { ext: ["pa"], name: "PowerArchiver Archive", cat: "archive", viewer: "fallback", desc: "PowerArchiver native format." },
  { ext: ["gca"], name: "GCA Archive", cat: "archive", viewer: "fallback", desc: "Turbo/GCA compressed archive." },
  { ext: ["jpa"], name: "JoomlaPA Archive", cat: "archive", viewer: "fallback", desc: "Joomla installer bundle." },
  { ext: ["cpgz"], name: "Compressed CPIO", cat: "archive", viewer: "fallback", sig: "1F 8B 08", desc: "macOS cpio.gz archive." },
  { ext: ["pbzx"], name: "PBZX Payload", cat: "system", viewer: "fallback", sig: "70 62 78 78", desc: "Chunked XZ OS X payload." },
  { ext: ["z01"], name: "Zip Split Part", cat: "archive", viewer: "fallback", desc: "Multi-volume zip segment." },
  { ext: ["r00"], name: "RAR Old Volume", cat: "archive", viewer: "fallback", desc: "Pre-.part RAR split piece." },
  { ext: ["001"], name: "Split Archive Part", cat: "archive", viewer: "fallback", desc: "HJSplit/7z numbered chunk." },
  { ext: ["xtm"], name: "Xtremsplit Part", cat: "archive", viewer: "fallback", desc: "Splitter join container." },
  { ext: ["ccf"], name: "CryptLoad Container", cat: "other", viewer: "fallback", desc: "Download link container." },
  { ext: ["metalink", "meta4"], name: "Metalink", cat: "other", viewer: "xml", desc: "Multi-source download descriptor." },
  { ext: ["repo"], name: "Yum Repository Config", cat: "config", viewer: "text", desc: "DNF/yum package repo." },
  { ext: ["dsc"], name: "Debian Source Control", cat: "system", viewer: "text", desc: "Package source metadata." },
  { ext: ["udeb"], name: "Debian Micro Package", cat: "system", viewer: "archive", sig: "21 3C 61 72 63 68 3E", desc: "Installer minimal .deb." },
  { ext: ["ddeb"], name: "Ubuntu Debug Package", cat: "system", viewer: "archive", sig: "21 3C 61 72 63 68 3E", desc: "Debug symbol .deb." },
  { ext: ["buildinfo"], name: "Debian Build Info", cat: "system", viewer: "text", desc: "Reproducible build manifest." },
  { ext: ["sources"], name: "APT Sources Entry", cat: "config", viewer: "text", desc: "Deb822 repository stanza." },
  { ext: ["asoundrc"], name: "ALSA RC", cat: "config", viewer: "text", desc: "Advanced Linux sound config." },
  { ext: ["xbindkeysrc"], name: "xbindkeys RC", cat: "config", viewer: "text", desc: "X hotkey binding config." },
  { ext: ["tinrc"], name: "tin RC", cat: "config", viewer: "text", desc: "Usenet reader settings." },
  { ext: ["library-ms"], name: "Windows Library", cat: "system", viewer: "xml", desc: "Explorer search scope." },
  { ext: ["localized"], name: "Mac Localized Marker", cat: "system", viewer: "text", desc: "Locale folder marker." },
  { ext: ["ann"], name: "Windows Help Annotation", cat: "system", viewer: "fallback", desc: "Annotated help bookmarks." },
  { ext: ["vbx"], name: "VBX Custom Control", cat: "system", viewer: "exe", desc: "16-bit Visual Basic control." },
  { ext: ["bdsproj"], name: "BDS Project", cat: "code", viewer: "xml", desc: "Delphi 2006 project." },
  { ext: ["groupproj"], name: "Delphi Group Project", cat: "code", viewer: "xml", desc: "RAD Studio project group." },
  { ext: ["lpk"], name: "Lazarus Package", cat: "code", viewer: "xml", desc: "Free Pascal IDE package." },
  { ext: ["lrs"], name: "Lazarus Resource", cat: "code", viewer: "text", desc: "Pascal resource form data." },
  { ext: ["epf"], name: "Eagle Project", cat: "code", viewer: "text", desc: "CadSoft EAGLE project params." },
  { ext: ["outjob"], name: "Altium Output Job", cat: "code", viewer: "fallback", desc: "Altium batch output setup." },
  { ext: ["intlib"], name: "Altium Integrated Library", cat: "code", viewer: "fallback", desc: "Compiled schematic+PCB library." },
  { ext: ["dblib"], name: "Altium Database Library", cat: "code", viewer: "fallback", desc: "DB-linked component library." },
  { ext: ["idf"], name: "Mentor IDF Board", cat: "3d", viewer: "text", desc: "Intermediate data format board." },
  { ext: ["emn", "emp"], name: "IDF Board/Mechanical", cat: "3d", viewer: "text", desc: "IDF .emn/.emp exchange files." },
  { ext: ["iqy"], name: "Excel Web Query", cat: "spreadsheet", viewer: "text", desc: "Web query definition." },
  { ext: ["dqy"], name: "Excel Database Query", cat: "spreadsheet", viewer: "text", desc: "ODBC query definition." },
  { ext: ["oqy"], name: "Excel OLAP Query", cat: "spreadsheet", viewer: "text", desc: "OLAP query definition." },
  { ext: ["rqy"], name: "Excel ODBC Query", cat: "spreadsheet", viewer: "text", desc: "Raw ODBC query file." },
  { ext: ["cub"], name: "OLAP Local Cube", cat: "data", viewer: "fallback", desc: "Offline analytical cube." },
  { ext: ["oft"], name: "Outlook Template", cat: "email", viewer: "eml", sig: "D0 CF 11 E0", desc: "Reusable message form." },
  { ext: ["nk2"], name: "Outlook AutoComplete", cat: "email", viewer: "fallback", desc: "Nickname cache stream." },
  { ext: ["rwz"], name: "Outlook Rules Wizard", cat: "email", viewer: "fallback", desc: "Exported rule set." },
  { ext: ["hol"], name: "Outlook Holidays", cat: "email", viewer: "text", desc: "Calendar holiday import." },
  { ext: ["oab"], name: "Offline Address Book", cat: "email", viewer: "fallback", desc: "Exchange GAL data." },
  { ext: ["acl"], name: "Office AutoCorrect List", cat: "system", viewer: "fallback", desc: "MS Office correction entries." },
  { ext: ["exd"], name: "Office Control Cache", cat: "system", viewer: "fallback", desc: "ActiveX form cache." },
  { ext: ["pip"], name: "Office Personalized Menu", cat: "system", viewer: "fallback", desc: "Menu usage statistics." },
  { ext: ["xll"], name: "Excel Add-in", cat: "system", viewer: "exe", desc: "Compiled Excel extension." },
  { ext: ["wll"], name: "Word Add-in", cat: "system", viewer: "exe", desc: "Compiled Word extension." },
  { ext: ["wiz"], name: "Office Wizard", cat: "system", viewer: "exe", desc: "Wizard executable template." },
  { ext: ["pwz"], name: "PowerPoint Wizard", cat: "system", viewer: "exe", desc: "Presentation wizard program." },
  { ext: ["xlc"], name: "Excel Chart", cat: "spreadsheet", viewer: "fallback", desc: "Legacy chart document." },
  { ext: ["ops"], name: "Office Profile Settings", cat: "system", viewer: "fallback", desc: "Office saved state." },
  { ext: ["pjx"], name: "VFP Project Table", cat: "database", viewer: "dbf", desc: "Visual FoxPro project." },
  { ext: ["pjt"], name: "VFP Project Memo", cat: "database", viewer: "fallback", desc: "Project memo companion." },
  { ext: ["frx", "frt"], name: "VFP Report", cat: "database", viewer: "fallback", desc: "FoxPro report + memo pair." },
  { ext: ["vcx"], name: "VFP Class Library", cat: "database", viewer: "fallback", desc: "FoxPro class table." },
  { ext: ["mnx", "mnt"], name: "VFP Menu", cat: "database", viewer: "fallback", desc: "FoxPro menu + memo." },
  { ext: ["lbt"], name: "VFP Label Memo", cat: "database", viewer: "fallback", desc: "FoxPro label memo companion." },
  { ext: ["x00", "x01", "y00", "y01"], name: "Paradox Secondary Index", cat: "database", viewer: "fallback", desc: "Indexed field file." },
  { ext: ["mdw"], name: "Access Workgroup File", cat: "database", viewer: "fallback", desc: "User-level security DB." },
  { ext: ["kexi", "kexic", "kexis"], name: "Kexi Database Objects", cat: "database", viewer: "fallback", desc: "KDE database project files." },
  { ext: ["dci"], name: "VMU Image", cat: "game", viewer: "fallback", desc: "Nexus VMU dump." },
  { ext: ["vmi"], name: "VMU Info", cat: "game", viewer: "fallback", desc: "VMU save descriptor." },
  { ext: ["jag"], name: "Atari Jaguar ROM", cat: "game", viewer: "fallback", desc: "Jaguar cartridge image." },
  { ext: ["xfd"], name: "Atari XFD Image", cat: "disk", viewer: "fallback", desc: "Raw 8-bit disk sector image." },
  { ext: ["obx"], name: "Atari Executable", cat: "system", viewer: "fallback", desc: "8-bit Atari binary load format." },
  { ext: ["cms"], name: "Atari CMS Music", cat: "audio", viewer: "fallback", desc: "Compact Music Score module." },
  { ext: ["rmt"], name: "Raster Music Tracker", cat: "audio", viewer: "fallback", desc: "Atari POKEY chiptune." },
  { ext: ["szx"], name: "ZX Spectrum Snapshot", cat: "game", viewer: "fallback", sig: "5A 58 33", desc: "Spectaculator snapshot." },
  { ext: ["p00"], name: "C64 PC64 File", cat: "game", viewer: "fallback", desc: "PRG with name header." },
  { ext: ["cvt"], name: "C64 Cartridge Image", cat: "game", viewer: "fallback", desc: "VICE cartridge dump." },
  { ext: ["sdk"], name: "ShrinkIt Disk Image", cat: "archive", viewer: "fallback", desc: "Compressed Apple II disk." },
  { ext: ["shk"], name: "ShrinkIt Archive", cat: "archive", viewer: "fallback", desc: "Apple II archive format." },
  { ext: ["bxy"], name: "BinScii Archive", cat: "archive", viewer: "fallback", desc: "ShrinkIt+uuencoded data." },
  { ext: ["hdv"], name: "Apple IIgs Hard Disk Image", cat: "disk", viewer: "fallback", desc: "Block device image." },
  { ext: ["hfv"], name: "HFV Floppy Image", cat: "disk", viewer: "fallback", desc: "Mac HFS volume image." },
  { ext: ["nkit"], name: "NKit Disc Image", cat: "game", viewer: "fallback", desc: "Recoverable GC/Wii compression." },
  { ext: ["bwt"], name: "Blindwrite Control", cat: "disk", viewer: "fallback", desc: "Blindwrite metadata." },
  { ext: ["csg"], name: "OpenSCAD CSG", cat: "code", viewer: "text", desc: "Flattened CSG products." },
  { ext: ["wp"], name: "WordPerfect Document", cat: "document", viewer: "fallback", desc: "Early WordPerfect word processor." },
  { ext: ["ws2"], name: "WordStar 2000 Document", cat: "document", viewer: "fallback", desc: "MicroPro WordStar 2000." },
  { ext: ["xy"], name: "XyWrite Document", cat: "document", viewer: "text", desc: "XyQuest notation-based writer." },
  { ext: ["xy3"], name: "XyWrite III Document", cat: "document", viewer: "text", desc: "XyWrite III+ text." },
  { ext: ["xyn"], name: "XyWrite Nota File", cat: "document", viewer: "text", desc: "XyWrite environment file." },
  { ext: ["cnm"], name: "Pegasus Mail Message", cat: "email", viewer: "eml", desc: "Pegasus mail folder message." },
  { ext: ["luau"], name: "Luau Script", cat: "code", viewer: "text", desc: "Roblox Lua dialect." },
  { ext: ["wlua"], name: "Windowless Lua", cat: "code", viewer: "text", desc: "Lua script without console." },
  { ext: ["bmx"], name: "BlitzMax Source", cat: "code", viewer: "text", desc: "BlitzMax module source." },
  { ext: ["monkey", "monkey2"], name: "Monkey Source", cat: "code", viewer: "text", desc: "Monkey X/2 cross-platform source." },
  { ext: ["odin"], name: "Odin Source", cat: "code", viewer: "text", desc: "Odin programming language." },
  { ext: ["bqn"], name: "BQN Source", cat: "code", viewer: "text", desc: "Array programming language." },
  { ext: ["civet"], name: "Civet Source", cat: "code", viewer: "text", desc: "CoffeeScript-family language." },
  { ext: ["dylan"], name: "Dylan Source", cat: "code", viewer: "text", desc: "Functional Dylan language." },
  { ext: ["chpl"], name: "Chapel Source", cat: "code", viewer: "text", desc: "Cray parallel language." },
  { ext: ["spin"], name: "Propeller SPIN Source", cat: "code", viewer: "text", desc: "Parallax P8X32A language." },
  { ext: ["spin2"], name: "Propeller 2 SPIN", cat: "code", viewer: "text", desc: "Parallax P2 language." },
  { ext: ["kix"], name: "KiXtart Script", cat: "code", viewer: "text", desc: "Windows logon scripting." },
  { ext: ["ah2"], name: "AutoHotkey v2 Script", cat: "code", viewer: "text", desc: "AHK v2 automation script." },
  { ext: ["livecode"], name: "LiveCode Stack", cat: "code", viewer: "fallback", desc: "LiveCode saved stack." },
  { ext: ["lc"], name: "LiveCode Script", cat: "code", viewer: "text", desc: "LiveCode source script." },
  { ext: ["agc"], name: "Apollo AGC Source", cat: "code", viewer: "text", desc: "Apollo Guidance Computer assembly." },
  { ext: ["acd"], name: "Alan Adventure", cat: "game", viewer: "fallback", desc: "Alan interactive fiction compiled." },
  { ext: ["age3scn"], name: "AoE3 Scenario", cat: "game", viewer: "fallback", desc: "Age of Empires III scenario." },
  { ext: ["age3sav"], name: "AoE3 Save", cat: "game", viewer: "fallback", desc: "Age of Empires III saved game." },
  { ext: ["umod"], name: "Unreal Tournament Mod", cat: "game", viewer: "fallback", desc: "UT installer archive." },
  { ext: ["osz"], name: "osu! Beatmap Archive", cat: "game", viewer: "archive", sig: "50 4B 03 04", desc: "osu! song bundle." },
  { ext: ["cht"], name: "Cheat Database", cat: "game", viewer: "fallback", desc: "Emulator cheat codes." },
  { ext: ["pnach"], name: "PCSX2 Cheat", cat: "game", viewer: "text", desc: "PS2 emulator patch file." },
];
