import type { RawFormat } from "@/lib/types";

/** AUTHORED EXPANSION G — MATLAB/NI, git internals, Mac suitcase, RAW variants, config conventions. */
export const EXTRA_FORMATS_G: RawFormat[] = [
  { ext: ["mexa64", "mexw32", "mexw64", "mexmaci64", "mexglx", "mexa32"], name: "MATLAB MEX Binary", cat: "system", viewer: "exe" },
  { ext: ["mlapp", "mltbx"], name: "MATLAB App/Toolbox", cat: "data", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["slxp", "sldd", "mdl3", "mldatx"], name: "Simulink Model", cat: "data", viewer: "archive", sig: "50 4B 03 04" },
  { ext: ["mlinstall", "mltbx2"], name: "MATLAB Installer", cat: "system", viewer: "fallback" },
  { ext: ["mx", "mx3"], name: "MATLAB Array (old)", cat: "data", viewer: "fallback" },
  { ext: ["spo"], name: "SPSS Output", cat: "data", viewer: "fallback" },
  { ext: ["sas7bcat", "smcl", "ster", "gph", "sthlp"], name: "SAS/Stata Companion Data", cat: "data", viewer: "fallback" },
  { ext: ["lvproj", "lvlib", "llb"], name: "LabVIEW Project Resource", cat: "code", viewer: "fallback" },
  { ext: ["lvm"], name: "LabVIEW Measurement", cat: "scientific", viewer: "text" },
  { ext: ["tdms"], name: "NI TDMS Stream", cat: "scientific", viewer: "fallback" },
  { ext: ["wfm"], name: "Tektronix Waveform", cat: "scientific", viewer: "fallback" },
  { ext: ["isf"], name: "Tektronix ISF Waveform", cat: "scientific", viewer: "fallback" },
  { ext: ["daq"], name: "NI DAQ Data", cat: "scientific", viewer: "fallback" },
  { ext: ["pack"], name: "Git Pack File", cat: "code", viewer: "fallback", sig: "50 41 43 4B" },
  { ext: ["keep"], name: "Git Keep Marker", cat: "other", viewer: "text" },
  { ext: ["mcmeta"], name: "Minecraft Resource Meta", cat: "game", viewer: "json" },
  { ext: ["pack.mcmeta"], name: "Resource Pack Manifest", cat: "game", viewer: "json" },
  { ext: ["compositefont"], name: "Apple Composite Font", cat: "font", viewer: "xml" },
  { ext: ["tcw", "tct", "stc"], name: "TurboCAD Drawing", cat: "3d", viewer: "fallback" },
  { ext: ["qtz"], name: "Quartz Composer Patch", cat: "code", viewer: "fallback" },
  { ext: ["qtindex"], name: "QuickTime Index", cat: "video", viewer: "fallback" },
  { ext: ["mesh"], name: "Mesh File (MeshLab)", cat: "3d", viewer: "three3d" },
  { ext: ["pmi"], name: "ISIS Drawing", cat: "code", viewer: "text" },
  { ext: ["cxf"], name: "Cross Exchange Format", cat: "image", viewer: "text" },
  { ext: ["maxpat", "maxhelp", "maxproj"], name: "Max Patch", cat: "audio", viewer: "json" },
  { ext: ["scworld"], name: "Scraft World", cat: "game", viewer: "fallback" },
  { ext: ["texpack"], name: "Texture Pack", cat: "game", viewer: "archive" },
  { ext: ["iml"], name: "IntelliJ Module", cat: "code", viewer: "xml" },
  { ext: ["ipr"], name: "IntelliJ Project", cat: "code", viewer: "xml" },
  { ext: ["iws"], name: "IntelliJ Workspace", cat: "code", viewer: "xml" },
  { ext: ["em"], name: "Emacs Macro (old)", cat: "code", viewer: "text" },
  { ext: ["fun"], name: "SML Functor", cat: "code", viewer: "code" },
  { ext: ["dlg"], name: "Dialog Resource", cat: "code", viewer: "text" },
  { ext: ["msk"], name: "Mask Image", cat: "image", viewer: "image" },
  { ext: ["ct0", "ct1", "ct2", "ct3"], name: "CT Data (medical)", cat: "scientific", viewer: "fallback" },
  { ext: ["sbt"], name: "Scala Build", cat: "code", viewer: "code" },
  { ext: ["narinfo"], name: "NAR Info (Nix)", cat: "system", viewer: "text" },
  { ext: ["bcmap", "bc1", "bc2", "bc3"], name: "Binary Cache (Apple)", cat: "system", viewer: "fallback" },
  { ext: ["cxt"], name: "Director External Cast", cat: "game", viewer: "fallback" },
];
