import type { RawFormat } from "@/lib/types";

/**
 * AUTHORED EXPANSION F — final wave: forensic images, FPGA, packages, ROMs,
 * 3D engine meshes, pocket/mobile docs, email variants, backups, web archives,
 * misc applications. Verified disjoint from earlier files after authoring.
 */
export const EXTRA_FORMATS_F: RawFormat[] = [
  // ---------------- forensic images ----------------
  { ext: ["afd", "af2"], name: "AFF Forensic Format", cat: "system", viewer: "fallback" },
  { ext: ["vib"], name: "Veeam Backup Archive", cat: "archive", viewer: "fallback" },

  // ---------------- FPGA / embedded ----------------
  { ext: ["xsvf"], name: "FPGA JTAG Vector", cat: "code", viewer: "text" },
  { ext: ["rbf2"], name: "FPGA Program Image", cat: "system", viewer: "fallback" },
  { ext: ["mcs2"], name: "PROM Image (Intel MCS)", cat: "system", viewer: "text" },
  { ext: ["elf2"], name: "ELF alias", cat: "other", viewer: "fallback" },
  { ext: ["mot2"], name: "SREC alias", cat: "other", viewer: "fallback" },
  { ext: ["cof2"], name: "COF alias", cat: "other", viewer: "fallback" },
  { ext: ["i90", "i96"], name: "Intel Object (PL/M)", cat: "system", viewer: "fallback" },
  { ext: ["a43", "a53", "a73"], name: "TI TMS430 Object", cat: "system", viewer: "fallback" },
  { ext: ["a90", "d90"], name: "IAR Object", cat: "system", viewer: "fallback" },
  { ext: ["lsl"], name: "Tasking Linker Script", cat: "config", viewer: "code" },
  { ext: ["map2"], name: "Linker map alias", cat: "other", viewer: "fallback" },
  { ext: ["inc2"], name: "Include alias", cat: "other", viewer: "fallback" },
  { ext: ["questa", "vsim"], name: "ModelSim Data", cat: "system", viewer: "fallback" },
  { ext: ["ucdb"], name: "Coverage Database", cat: "data", viewer: "fallback" },
  { ext: ["evcd"], name: "Value Change Dump", cat: "code", viewer: "text", desc: "Waveform simulation dumps." },
  { ext: ["awf"], name: "Active-HDL Waveform", cat: "code", viewer: "fallback" },
  { ext: ["awx"], name: "Aldec Workspace", cat: "code", viewer: "fallback" },
  { ext: ["bde", "ade"], name: "Block Diagram Editor", cat: "code", viewer: "xml" },

  // ---------------- 3D engine meshes ----------------
  { ext: ["psk", "psa"], name: "Unreal Static Mesh/Anim", cat: "3d", viewer: "three3d" },
  { ext: ["hkx"], name: "Havok Physics Data", cat: "3d", viewer: "fallback" },
  { ext: ["nif"], name: "Gamebryo Model", cat: "3d", viewer: "fallback" },
  { ext: ["kf2"], name: "Gamebryo anim alias", cat: "other", viewer: "fallback" },
  { ext: ["tri"], name: "Stunt GP / SMD tri", cat: "3d", viewer: "three3d" },
  { ext: ["ask"], name: "3ds Max ASCII Export", cat: "3d", viewer: "code" },
  { ext: ["chr"], name: "Character Rig (Game)", cat: "3d", viewer: "fallback" },
  { ext: ["vxp"], name: "Voxel Pixel Model", cat: "3d", viewer: "fallback" },
  { ext: ["hmp"], name: "Heightmap (3D GameStudio)", cat: "3d", viewer: "fallback" },
  { ext: ["mdl2"], name: "Gamestudio Model alias", cat: "other", viewer: "fallback" },
  { ext: ["wmp"], name: "3D GameStudio Level", cat: "3d", viewer: "fallback" },

  // ---------------- audio (game/nintendo) ----------------
  { ext: ["rstm"], name: "Wii/Revolution Stream", cat: "audio", viewer: "fallback" },
  { ext: ["rwav"], name: "Revolution WAV", cat: "audio", viewer: "fallback" },
  { ext: ["rsar"], name: "Revolution Sound Archive", cat: "audio", viewer: "fallback" },
  { ext: ["ft"], name: "FM Tracker Project", cat: "audio", viewer: "midi" },
  { ext: ["dwc"], name: "Deepwav Compressed", cat: "audio", viewer: "fallback" },
  { ext: ["bo"], name: "BO Sound", cat: "audio", viewer: "fallback" },
  { ext: ["pw"], name: "Phantom Waltz Module", cat: "audio", viewer: "midi" },

  // ---------------- pocket / mobile docs ----------------
  { ext: ["pwi"], name: "Pocket Word Document", cat: "document", viewer: "docx" },
  { ext: ["psw"], name: "Pocket Word Document (new)", cat: "document", viewer: "docx" },
  { ext: ["pxl", "pxt"], name: "Pocket Excel Workbook", cat: "spreadsheet", viewer: "xlsx" },
  { ext: ["jtd"], name: "Ichitaro Document", cat: "document", viewer: "fallback" },
  { ext: ["jtt"], name: "Ichitaro Template", cat: "document", viewer: "fallback" },
  { ext: ["wpx"], name: "WordPerfect Express", cat: "document", viewer: "fallback" },
  { ext: ["dox"], name: "Multimate Document", cat: "document", viewer: "fallback" },
  { ext: ["dof"], name: "DOS Text/Doc", cat: "document", viewer: "text" },
  { ext: ["emlxpart"], name: "Apple Mail Part", cat: "email", viewer: "fallback" },
  { ext: ["partial.emlx"], name: "Apple Mail Partial", cat: "email", viewer: "eml" },

  // ---------------- packages / distro ----------------
  { ext: ["nar"], name: "NPM Archive", cat: "archive", viewer: "archive" },
  { ext: ["btp"], name: "Bintec Package", cat: "system", viewer: "fallback" },
  { ext: ["ipkg"], name: "Itsy Package (Opkg)", cat: "archive", viewer: "archive" },
  { ext: ["opk"], name: "OpenMoko Package", cat: "archive", viewer: "archive" },

  // ---------------- web archives ----------------
  { ext: ["warc", "warc.gz"], name: "Web ARChive", cat: "archive", viewer: "text", desc: "W/1.0 HTTP archive records." },
  { ext: ["cdxj"], name: "CDXJ Index", cat: "data", viewer: "text" },

  // ---------------- misc applications ----------------
  { ext: ["shb"], name: "Doc Shortcut", cat: "system", viewer: "fallback" },
  { ext: ["xnk"], name: "Exchange Public Shortcut", cat: "system", viewer: "fallback" },
  { ext: ["fot"], name: "Font Installer Stub", cat: "font", viewer: "fallback" },
  { ext: ["aex"], name: "After Effects Plugin", cat: "system", viewer: "fallback" },
  { ext: ["aepx"], name: "After Effects Project", cat: "video", viewer: "fallback" },
  { ext: ["aet", "aetx"], name: "After Effects Template", cat: "video", viewer: "fallback" },
  { ext: ["imoviemobile", "imovietrailer"], name: "iMovie Project", cat: "video", viewer: "archive" },
  { ext: ["wflow"], name: "Shade Workflow", cat: "image", viewer: "json" },
  { ext: ["webarchive"], name: "Safari Web Archive", cat: "archive", viewer: "fallback" },
  { ext: ["xcdatamodeld", "xcdatamodel", "xcmappingmodel"], name: "Xcode Data Model", cat: "code", viewer: "fallback" },
  { ext: ["xcodeproj"], name: "Xcode Project", cat: "code", viewer: "text" },
  { ext: ["pbxuser"], name: "Xcode User Data", cat: "code", viewer: "text" },
  { ext: ["nus3bank", "nus3audio"], name: "Namco Sound Bank", cat: "audio", viewer: "fallback" },
  { ext: ["bw64", "rf64"], name: "Broadcast WAV 64", cat: "audio", viewer: "audio" },
  { ext: ["xml.z"], name: "Compressed XML", cat: "data", viewer: "text" },
  { ext: ["mtf"], name: "Minetest Mod Texture", cat: "image", viewer: "image" },
  { ext: ["umt"], name: "Unity Mesh Transfer", cat: "3d", viewer: "fallback" },
  { ext: ["mcf"], name: "Metashape Camera File", cat: "data", viewer: "text" },
  { ext: ["room"], name: "Room Definition (Adventure)", cat: "game", viewer: "fallback" },
  { ext: ["vassal"], name: "VASSAL Module", cat: "game", viewer: "archive" },
  { ext: ["vmod"], name: "VASSAL Module (new)", cat: "game", viewer: "archive" },
  { ext: ["vext"], name: "VASSAL Extension", cat: "game", viewer: "archive" },
  { ext: ["frog"], name: "Frogger Level", cat: "game", viewer: "fallback" },
  { ext: ["bos"], name: "BOS Object", cat: "game", viewer: "fallback" },
  { ext: ["dam"], name: "DAM Level", cat: "game", viewer: "fallback" },
  { ext: ["emc"], name: "EMC Script", cat: "code", viewer: "text" },
  { ext: ["mappa"], name: "Map File (Italian tools)", cat: "data", viewer: "fallback" },
  { ext: ["lgp"], name: "LG Game Archive", cat: "game", viewer: "fallback" },
  { ext: ["fmv"], name: "FMV Video", cat: "video", viewer: "fallback" },
  { ext: ["lbx"], name: "LBX Archive (Master of Orion)", cat: "game", viewer: "fallback" },
  { ext: ["pbiviz"], name: "PowerBI Visual", cat: "data", viewer: "archive" },
  { ext: ["pbix", "pbit"], name: "PowerBI File", cat: "data", viewer: "fallback" },
  { ext: ["tds", "tdsx"], name: "Tableau Datasource", cat: "data", viewer: "xml" },
  { ext: ["tlf"], name: "Tableau Workbook (old)", cat: "data", viewer: "xml" },
  { ext: ["sps"], name: "SPSS Syntax", cat: "data", viewer: "code" },
  { ext: ["spj"], name: "SPSS Production Job", cat: "data", viewer: "fallback" },
  { ext: ["dbt"], name: "dBase Memo", cat: "database", viewer: "text" },
  { ext: ["mtd"], name: "Anno Game Data", cat: "game", viewer: "fallback" },
  { ext: ["bcr"], name: "BCR Card Backup", cat: "system", viewer: "fallback" },
  { ext: ["a2w"], name: "Alice World", cat: "3d", viewer: "fallback" },
  { ext: ["a3c"], name: "Alice Class", cat: "code", viewer: "fallback" },
  { ext: ["mit"], name: "MIT Scratch Project (old)", cat: "game", viewer: "fallback" },
  { ext: ["sprite3"], name: "Scratch Sprite", cat: "game", viewer: "archive" },
  { ext: ["scratch"], name: "Scratch Project", cat: "game", viewer: "archive" },
  { ext: ["c3p"], name: "Construct 3 Project", cat: "game", viewer: "json" },
  { ext: ["bbmodel"], name: "Blockbench Model", cat: "3d", viewer: "json" },
  { ext: ["bbproject"], name: "Blockbench Project", cat: "code", viewer: "json" },
  { ext: ["csm"], name: "Cast Single Model", cat: "3d", viewer: "fallback" },
  { ext: ["tgo"], name: "Turbocad Object", cat: "3d", viewer: "fallback" },
  { ext: ["ckd"], name: "CADKEY CAD File", cat: "3d", viewer: "fallback" },
  { ext: ["p3d"], name: "Panda3D Model", cat: "3d", viewer: "fallback" },
  { ext: ["mrg"], name: "Marching Cubes Mesh", cat: "3d", viewer: "three3d" },
  { ext: ["v3d"], name: "Vertice 3D", cat: "3d", viewer: "three3d" },
  { ext: ["awd"], name: "Away3D Model", cat: "3d", viewer: "three3d" },
  { ext: ["b3dzi"], name: "Blitz 3D Zipped Model", cat: "3d", viewer: "archive" },
];
