import type { RawFormat } from "@/lib/types";

/**
 * AUTHORED EXPANSION D — OS/application formats (Windows/macOS/Linux), installer
 * and update packages, developer tooling convention files, IDE/project formats,
 * shader binaries, EDA/HDL, color/timeline interchange, game platform containers,
 * emulation, scientific instruments, CAD/robotics, databases, legacy office,
 * fonts, and misc real formats not present in CORE/A/B/C.
 */
export const EXTRA_FORMATS_D: RawFormat[] = [
  // ---------------- Windows system / installer / update ----------------
  { ext: ["msu"], name: "Windows Update Package", cat: "system", viewer: "fallback", mime: "application/x-ms-update", desc: "Microsoft Update Standalone Package bundle of cabinets." },
  { ext: ["gadget"], name: "Windows Sidebar Gadget", cat: "system", viewer: "archive", desc: "ZIP-packaged Sidebar gadget with HTML/JS." },
  { ext: ["theme"], name: "Windows Theme Settings", cat: "system", viewer: "text", desc: "INI-style desktop theme definition." },
  { ext: ["themepack"], name: "Windows Theme Pack", cat: "system", viewer: "archive", desc: "Packaged desktop theme (ZIP with visuals and sounds)." },
  { ext: ["deskthemepack"], name: "Windows Desktop Theme Pack", cat: "system", viewer: "archive", desc: "Aero desktop theme package." },
  { ext: ["msstyles"], name: "Windows Visual Style", cat: "system", viewer: "fallback", desc: "Pe-file skin resource for Windows visual styles." },
  { ext: ["rct"], name: "Visual C++ Resource Template", cat: "code", viewer: "text", desc: "Resource editor template file." },
  { ext: ["winmd"], name: "Windows Metadata", cat: "system", viewer: "exe", sig: "4D 5A", desc: "ECMA-335 metadata for WinRT APIs." },
  { ext: ["hiv"], name: "Windows Registry Hive", cat: "system", viewer: "fallback", sig: "72 65 67 66", desc: "Registry database hive (regf header)." },
  { ext: ["regtrans-ms"], name: "Windows Registry Transaction Log", cat: "system", viewer: "fallback", desc: "Registry transaction log created alongside hives." },
  { ext: ["diagpkg"], name: "Windows Diagnostic Package", cat: "system", viewer: "archive", desc: "Troubleshooting pack for support diagnostics." },
  { ext: ["diagcfg"], name: "Windows Diagnostic Config", cat: "system", viewer: "text", desc: "Diagnostic settings text file." },
  { ext: ["dl_"], name: "MSCompressed DLL", cat: "system", viewer: "archive", desc: "Setup-compressed DLL distribution file." },
  { ext: ["ex_"], name: "MSCompressed EXE", cat: "system", viewer: "archive", desc: "Setup-compressed executable distribution file." },
  { ext: ["sy_"], name: "MSCompressed SYS", cat: "system", viewer: "archive", desc: "Setup-compressed driver distribution file." },
  { ext: ["in_"], name: "MSCompressed INF", cat: "system", viewer: "archive", desc: "Setup-compressed INF information file." },
  { ext: ["chi"], name: "Compiled HTML Help Index", cat: "system", viewer: "fallback", desc: "CHM keyword index companion file." },
  { ext: ["chw"], name: "CHM Full-Text Index", cat: "system", viewer: "fallback", desc: "Compiled help workspace index." },
  { ext: ["gid"], name: "WinHelp Index", cat: "system", viewer: "fallback", desc: "Generated WinHelp keyword index." },
  { ext: ["hpj"], name: "WinHelp Project", cat: "system", viewer: "text", desc: "Help compiler project (RTF sources, options)." },
  { ext: ["cpi"], name: "DOS Codepage Info", cat: "system", viewer: "fallback", desc: "Codepage font/translate data for DOS." },
  { ext: ["appref-ms"], name: "ClickOnce Reference", cat: "system", viewer: "text", desc: "ClickOnce application shortcut target." },
  { ext: ["application"], name: "ClickOnce Manifest", cat: "system", viewer: "xml", desc: "ClickOnce deployment manifest." },
  { ext: ["mig"], name: "Windows Migration Store", cat: "system", viewer: "fallback", desc: "Windows Easy Transfer data store." },
  { ext: ["zap"], name: "Group Policy ZAP", cat: "system", viewer: "text", desc: "Software installation descriptor for MSI-less apps." },
  { ext: ["wer"], name: "Windows Error Report", cat: "system", viewer: "text", desc: "Crash report text collected by WER." },
  { ext: ["clg"], name: "Windows Image Catalog", cat: "system", viewer: "xml", desc: "WSIM answer-file catalog for install WIMs." },
  { ext: ["pnf"], name: "Precompiled INF", cat: "system", viewer: "fallback", desc: "Preprocessed driver INF cache." },
  { ext: ["prf"], name: "Outlook Profile", cat: "system", viewer: "text", desc: "MAPI service profile definition." },
  { ext: ["wsh"], name: "Windows Script Host Settings", cat: "system", viewer: "text", desc: "Script execution property file." },
  { ext: ["wsf"], name: "Windows Script File", cat: "code", viewer: "xml", desc: "Multi-language XML script container." },
  { ext: ["vbe"], name: "Encoded VBScript", cat: "code", viewer: "text", desc: "Screnc-obfuscated VBScript." },
  { ext: ["jse"], name: "Encoded JScript", cat: "code", viewer: "text", desc: "Screnc-obfuscated JScript." },
  { ext: ["pbk"], name: "Windows Phonebook", cat: "system", viewer: "text", desc: "RAS dial-up entries in INI form." },
  { ext: ["ctt"], name: "Messenger Contacts", cat: "other", viewer: "xml", desc: "MSN Messenger contact list exchange." },
  { ext: ["clp"], name: "Windows Clipboard", cat: "other", viewer: "fallback", desc: "Saved clipboard dump from Clipboard Viewer." },
  { ext: ["sed"], name: "SED Script", cat: "code", viewer: "text", desc: "GNU sed command script." },
  { ext: ["isl"], name: "Inno Setup Language", cat: "code", viewer: "xml", desc: "Localization file for Inno Setup installers." },
  { ext: ["xnb"], name: "XNA Content Binary", cat: "game", viewer: "fallback", sig: "58 4E 42", desc: "Compiled XNA content pipeline asset." },

  // ---------------- Apple platforms ----------------
  { ext: ["stringsdict"], name: "Apple Strings Dictionary", cat: "code", viewer: "xml", desc: "Plural-aware localizations (variation of plist)." },
  { ext: ["xcworkspacedata"], name: "Xcode Workspace", cat: "code", viewer: "xml", desc: "Workspace membership definition." },
  { ext: ["xcent"], name: "Xcode Entitlements (old)", cat: "code", viewer: "xml", desc: "Legacy entitlements plist format." },
  { ext: ["playground"], name: "Swift Playground", cat: "code", viewer: "fallback", desc: "Xcode interactive Swift learning bundle." },
  { ext: ["playgroundbook"], name: "Swift Playgrounds Book", cat: "code", viewer: "fallback", desc: "iPad Swift Playgrounds lesson bundle." },
  { ext: ["dmgpart"], name: "Apple Disk Image Part", cat: "disk", viewer: "fallback", desc: "Segmented Apple disk image part." },
  { ext: ["mpkg"], name: "macOS Meta Package", cat: "system", viewer: "archive", desc: "Installer package containing sub-packages." },
  { ext: ["xip"], name: "Xcode Signed Archive", cat: "system", viewer: "archive", desc: "Xcode release archive with signature." },
  { ext: ["swiftdoc"], name: "Swift Module Docs", cat: "code", viewer: "fallback", desc: "Compiled interface documentation for modules." },
  { ext: ["pkpass"], name: "Apple Wallet Pass", cat: "other", viewer: "archive", desc: "Signed pass bundle with manifest and logo." },
  { ext: ["provisionprofile"], name: "Apple Provisioning Profile", cat: "system", viewer: "fallback", sig: "30 82", desc: "Developer signing profile for macOS." },
  { ext: ["mobileprovision"], name: "iOS Provisioning Profile", cat: "system", viewer: "fallback", sig: "30 82", desc: "CMS-signed deployment entitlements for iOS." },
  { ext: ["xctest"], name: "XCTest Bundle", cat: "system", viewer: "fallback", desc: "Unit test bundle for Apple platforms." },
  { ext: ["band"], name: "GarageBand Project", cat: "audio", viewer: "fallback", desc: "GarageBand song bundle (macOS) or archive (iOS)." },
  { ext: ["fcp"], name: "Final Cut Pro Project", cat: "video", viewer: "fallback", desc: "Legacy FCP 7 editing project." },
  { ext: ["aupreset"], name: "Audio Unit Preset", cat: "audio", viewer: "fallback", desc: "Saved parameter state for an AU plugin." },
  { ext: ["vstpreset"], name: "VST3 Preset", cat: "audio", viewer: "fallback", desc: "Steinberg VST3 plugin preset chunk file." },
  { ext: ["component"], name: "Audio Unit Component", cat: "audio", viewer: "fallback", desc: "macOS Audio Unit plugin bundle." },
  { ext: ["dpm"], name: "Pro Tools Plugin", cat: "audio", viewer: "fallback", desc: "Avid/RTAS plugin binary used by Pro Tools." },

  // ---------------- mobile / RIM ----------------
  { ext: ["odex"], name: "Optimized DEX", cat: "system", viewer: "fallback", sig: "64 65 79 0A", desc: "Ahead-of-time extracted app code for Android." },
  { ext: ["oat"], name: "Android OAT Image", cat: "system", viewer: "fallback", desc: "ART ahead-of-time compiled runtime image." },
  { ext: ["idsig"], name: "APK Signing Block Info", cat: "system", viewer: "fallback", desc: "apksigner signature metadata sidecar." },
  { ext: ["cod"], name: "BlackBerry Compiled Code", cat: "system", viewer: "fallback", desc: "Compiled Java bytecode for BlackBerry." },
  { ext: ["alx"], name: "BlackBerry App Descriptor", cat: "code", viewer: "xml", desc: "Application loader descriptor XML." },
  { ext: ["ipd"], name: "BlackBerry Backup", cat: "data", viewer: "fallback", desc: "Device backup database from BlackBerry Desktop." },
  { ext: ["f4b"], name: "Adobe F4B Audio Book", cat: "audio", viewer: "fallback", desc: "HTTP-streaming audio container variant of F4V." },

  // ---------------- Unix packaging / filesystems ----------------
  { ext: ["xbps"], name: "XBPS Package", cat: "archive", viewer: "archive", desc: "Void Linux binary package archive." },
  { ext: ["click"], name: "Ubuntu Click Package", cat: "archive", viewer: "archive", desc: "Ubuntu Touch framework package." },
  { ext: ["run"], name: "Makeself Installer", cat: "archive", viewer: "archive", desc: "Self-extracting shell archive installer." },
  { ext: ["pisi"], name: "PISI Package", cat: "archive", viewer: "archive", desc: "Pardus Linux package archive." },
  { ext: ["bff"], name: "AIX Installp Archive", cat: "archive", viewer: "archive", desc: "IBM AIX backup file format package." },
  { ext: ["depot"], name: "HP-UX SD-UX Depot", cat: "archive", viewer: "fallback", desc: "Hewlett-Packard software depot distribution." },
  { ext: ["wpi"], name: "WarpIN Installer", cat: "archive", viewer: "archive", desc: "OS/2 WarpIN package archive." },
  { ext: ["wgt"], name: "Tizen Widget", cat: "system", viewer: "archive", desc: "Tizen web application widget package." },
  { ext: ["vbox-extpack"], name: "VirtualBox Extension Pack", cat: "system", viewer: "archive", desc: "Signed Oracle VirtualBox add-on package." },
  { ext: ["qed"], name: "QEMU Enhanced Disk", cat: "disk", viewer: "fallback", desc: "Copy-on-write sparse disk image." },
  { ext: ["pvs"], name: "Parallels VM Config", cat: "system", viewer: "text", desc: "Parallels Desktop virtual machine settings." },
  { ext: ["ext2"], name: "ext2 Filesystem Image", cat: "disk", viewer: "fallback", desc: "Second extended filesystem dump." },
  { ext: ["ext3"], name: "ext3 Filesystem Image", cat: "disk", viewer: "fallback", desc: "Journaled second extended filesystem dump." },
  { ext: ["ext4"], name: "ext4 Filesystem Image", cat: "disk", viewer: "fallback", desc: "Fourth extended filesystem dump." },
  { ext: ["jffs2"], name: "JFFS2 Image", cat: "disk", viewer: "fallback", sig: "19 85", desc: "Raw NOR-flash journaling filesystem image." },
  { ext: ["ubi"], name: "UBI Image", cat: "disk", viewer: "fallback", desc: "Unsorted Block Image volume for NAND." },
  { ext: ["ubifs"], name: "UBIFS Image", cat: "disk", viewer: "fallback", desc: "UBI filesystem image for raw NAND." },
  { ext: ["cramfs"], name: "CramFS Image", cat: "disk", viewer: "fallback", sig: "45 3D CD 28", desc: "Compressed read-only ROM filesystem." },
  { ext: ["f2fs"], name: "F2FS Image", cat: "disk", viewer: "fallback", desc: "Flash-Friendly File System image." },
  { ext: ["xmit"], name: "TSO XMIT Dataset", cat: "data", viewer: "fallback", desc: "IBM z/OS transmitted dataset container." },
  { ext: ["terse"], name: "IBM TERSE Archive", cat: "archive", viewer: "fallback", desc: "Mainframe terse-compressed dataset." },
  { ext: ["aws"], name: "IBM AWS Tape Image", cat: "archive", viewer: "fallback", desc: "Automatic Workstation mainframe tape file." },

  // ---------------- web / JS tooling convention files ----------------
  { ext: ["browserslistrc"], name: "Browserslist Config", cat: "config", viewer: "text", desc: "Shared browser targets config for build tools." },
  { ext: ["browserslist"], name: "Browserslist Config (alt)", cat: "config", viewer: "text", desc: "Alternative Browserslist config file." },
  { ext: ["npmignore"], name: "npm Ignore File", cat: "config", viewer: "text", desc: "Exclusion patterns for published npm packages." },
  { ext: ["yarnignore"], name: "Yarn Ignore File", cat: "config", viewer: "text", desc: "Yarn pack ignore rules." },
  { ext: ["commitlintrc"], name: "Commitlint Config", cat: "config", viewer: "text", desc: "Commit message lint rules." },
  { ext: ["lintstagedrc"], name: "lint-staged Config", cat: "config", viewer: "json", desc: "Pre-commit staged-task definitions." },
  { ext: ["czrc"], name: "Commitizen Config", cat: "config", viewer: "json", desc: "Commitizen adapter selection." },
  { ext: ["versionrc"], name: "standard-version Config", cat: "config", viewer: "json", desc: "Conventional changelog/release options." },
  { ext: ["releaserc"], name: "semantic-release Config", cat: "config", viewer: "json", desc: "Automated release pipeline definition." },
  { ext: ["mocharc"], name: "Mocha Config", cat: "config", viewer: "json", desc: "Mocha test runner options." },
  { ext: ["taprc"], name: "TAP Runner Config", cat: "config", viewer: "json", desc: "node-tap run control file." },
  { ext: ["nycrc"], name: "nyc Config", cat: "config", viewer: "json", desc: "Istanbul/nyc coverage configuration." },
  { ext: ["c8rc"], name: "c8 Config", cat: "config", viewer: "json", desc: "V8-coverage runner configuration." },
  { ext: ["stylelintrc"], name: "Stylelint Config", cat: "config", viewer: "json", desc: "CSS linting rules." },
  { ext: ["stylelintignore"], name: "Stylelint Ignore", cat: "config", viewer: "text", desc: "Files excluded from stylelint." },
  { ext: ["eslintignore"], name: "ESLint Ignore", cat: "config", viewer: "text", desc: "Paths excluded from ESLint." },
  { ext: ["prettierignore"], name: "Prettier Ignore", cat: "config", viewer: "text", desc: "Paths excluded from Prettier formatting." },
  { ext: ["htmlhintrc"], name: "HTMLHint Config", cat: "config", viewer: "json", desc: "HTML linting options." },
  { ext: ["jscsrc"], name: "JSCS Config", cat: "config", viewer: "json", desc: "JavaScript style checker rules (legacy)." },
  { ext: ["jshintrc"], name: "JSHint Config", cat: "config", viewer: "json", desc: "JSHint linting options." },
  { ext: ["jsbeautifyrc"], name: "JS Beautifier Config", cat: "config", viewer: "json", desc: "Formatting options for JS Beautify." },
  { ext: ["csslintrc"], name: "CSSLint Config", cat: "config", viewer: "json", desc: "CSSLint rule configuration." },
  { ext: ["postcssrc"], name: "PostCSS Config", cat: "config", viewer: "json", desc: "PostCSS plugin pipeline config." },
  { ext: ["codespellrc"], name: "Codespell Config", cat: "config", viewer: "text", desc: "Typo-dictionary settings for codespell." },
  { ext: ["snyk"], name: "Snyk Policy File", cat: "config", viewer: "text", desc: "Vulnerability ignore and patch policy." },
  { ext: ["all-contributorsrc"], name: "All Contributors Config", cat: "config", viewer: "json", desc: "Contribor bot roster and options." },
  { ext: ["lighthouserc"], name: "Lighthouse CI Config", cat: "config", viewer: "json", desc: "Lighthouse assertions and CI settings." },
  { ext: ["yamllint"], name: "yamllint Config", cat: "config", viewer: "text", desc: "YAML linting rules." },
  { ext: ["parcelrc"], name: "Parcel Config", cat: "config", viewer: "json", desc: "Parcel 2 bundler configuration." },
  { ext: ["windsurfrules"], name: "Windsurf Rules", cat: "config", viewer: "text", desc: "AI assistant behavior rules for Windsurf." },
  { ext: ["cursorrules"], name: "Cursor Rules", cat: "config", viewer: "text", desc: "AI editor project rules for Cursor." },
  { ext: ["clinerules"], name: "Cline Rules", cat: "config", viewer: "text", desc: "Cline AI agent workspace rules." },
  { ext: ["tern-project"], name: "Tern Project Config", cat: "config", viewer: "json", desc: "Tern.js JavaScript inference settings." },
  { ext: ["ackrc"], name: "ack Config", cat: "config", viewer: "text", desc: "ack grep tool defaults." },
  { ext: ["srcinfo"], name: "AUR SRCINFO", cat: "config", viewer: "text", desc: "Parsed metadata for Arch PKGBUILDs." },

  // ---------------- shell / unix rc files ----------------
  { ext: ["zprofile"], name: "Zsh Profile", cat: "config", viewer: "text", desc: "Login-shell startup script for zsh." },
  { ext: ["zshenv"], name: "Zsh Environment", cat: "config", viewer: "text", desc: "Per-invocation zsh environment file." },
  { ext: ["zlogin"], name: "Zsh Login Script", cat: "config", viewer: "text", desc: "Zsh login initialization." },
  { ext: ["zlogout"], name: "Zsh Logout Script", cat: "config", viewer: "text", desc: "Zsh login teardown script." },
  { ext: ["zsh-theme"], name: "Oh My Zsh Theme", cat: "code", viewer: "text", desc: "Prompt/theme shell script for Oh My Zsh." },
  { ext: ["cshrc"], name: "C Shell RC", cat: "config", viewer: "text", desc: "csh interactive startup file." },
  { ext: ["tcshrc"], name: "TC Shell RC", cat: "config", viewer: "text", desc: "tcsh interactive startup file." },
  { ext: ["kshrc"], name: "Korn Shell RC", cat: "config", viewer: "text", desc: "ksh interactive startup file." },
  { ext: ["login"], name: "Unix Login Script", cat: "config", viewer: "text", desc: "csh-family login startup file." },
  { ext: ["logout"], name: "Unix Logout Script", cat: "config", viewer: "text", desc: "csh-family logout cleanup file." },
  { ext: ["inputrc"], name: "Readline Config", cat: "config", viewer: "text", desc: "GNU readline key bindings and settings." },
  { ext: ["screenrc"], name: "GNU Screen Config", cat: "config", viewer: "text", desc: "Screen terminal multiplexer startup." },
  { ext: ["curlrc"], name: "curl Config", cat: "config", viewer: "text", desc: "Default curl command-line options." },
  { ext: ["wgetrc"], name: "Wget Config", cat: "config", viewer: "text", desc: "Wget startup settings." },
  { ext: ["muttrc"], name: "Mutt Config", cat: "config", viewer: "text", desc: "Mutt mail user agent configuration." },
  { ext: ["mailcap"], name: "Mailcap File", cat: "config", viewer: "text", desc: "MIME type to viewer mapping." },
  { ext: ["procmailrc"], name: "Procmail Config", cat: "config", viewer: "text", desc: "Mail delivery filtering recipe." },
  { ext: ["pinerc"], name: "Alpine Config", cat: "config", viewer: "text", desc: "Alpine/Pine mail reader settings." },
  { ext: ["newsrc"], name: "News Reader State", cat: "config", viewer: "text", desc: "Subscribed newsgroup ranges file." },
  { ext: ["cvsrc"], name: "CVS Config", cat: "config", viewer: "text", desc: "Default cvs command options." },
  { ext: ["rpmmacros"], name: "RPM Macros", cat: "config", viewer: "text", desc: "rpmbuild macro definitions." },
  { ext: ["gdbinit"], name: "GDB Init Script", cat: "config", viewer: "text", desc: "GDB debugger startup commands." },
  { ext: ["lldbinit"], name: "LLDB Init Script", cat: "config", viewer: "text", desc: "LLDB debugger startup commands." },
  { ext: ["valgrindrc"], name: "Valgrind Config", cat: "config", viewer: "text", desc: "Default suppression/options for valgrind." },
  { ext: ["emacs"], name: "Emacs Init", cat: "code", viewer: "text", desc: "Emacs Lisp startup file." },
  { ext: ["spacemacs"], name: "Spacemacs Config", cat: "code", viewer: "text", desc: "Spacemacs distribution init file." },
  { ext: ["irbrc"], name: "IRB Config", cat: "code", viewer: "text", desc: "Interactive Ruby session customization." },
  { ext: ["pryrc"], name: "Pry Config", cat: "code", viewer: "text", desc: "Pry REPL customization." },
  { ext: ["thor"], name: "Thor Tasks", cat: "code", viewer: "text", desc: "Ruby Thor task library file." },
  { ext: ["pypirc"], name: "PyPI Config", cat: "config", viewer: "text", desc: "Package index credentials and repositories." },
  { ext: ["pep8"], name: "pep8 Config", cat: "config", viewer: "text", desc: "Legacy pep8 tool style config." },
  { ext: ["reek"], name: "Reek Config", cat: "config", viewer: "text", desc: "Ruby code smell detector options." },
  { ext: ["simplecov"], name: "SimpleCov Profile", cat: "config", viewer: "text", desc: "Ruby coverage startup profile." },

  // ---------------- X11 / desktop Linux ----------------
  { ext: ["xinitrc"], name: "xinit Startup", cat: "config", viewer: "text", desc: "X session program launched by startx." },
  { ext: ["xsession"], name: "X Session Script", cat: "config", viewer: "text", desc: "Display-manager session startup script." },
  { ext: ["xprofile"], name: "X Profile", cat: "config", viewer: "text", desc: "Session environment setup script." },
  { ext: ["xmodmap"], name: "X Modmap", cat: "config", viewer: "text", desc: "Keyboard modifier/key mapping file." },
  { ext: ["xresources"], name: "X Resources", cat: "config", viewer: "text", desc: "Xrdb application resource database." },
  { ext: ["xdefaults"], name: "X Defaults", cat: "config", viewer: "text", desc: "Legacy per-host X resource defaults." },
  { ext: ["xauthority"], name: "X Authority", cat: "system", viewer: "fallback", desc: "X11 MIT-MAGIC-COOKIE session keys." },
  { ext: ["gtkrc"], name: "GTK RC", cat: "config", viewer: "text", desc: "GTK theme/style definition." },
  { ext: ["kdelnk"], name: "KDE Shortcut", cat: "config", viewer: "text", desc: "KDE1/2 application link file." },
  { ext: ["kdeglobals"], name: "KDE Globals", cat: "config", viewer: "text", desc: "KDE global application settings (INI)." },
  { ext: ["zone"], name: "BIND Zone File", cat: "config", viewer: "text", desc: "DNS zone resource records." },
  { ext: ["godot"], name: "Godot Project", cat: "game", viewer: "text", desc: "Godot engine project settings (INI-like)." },

  // ---------------- compilers / IDE / project files ----------------
  { ext: ["i"], name: "Preprocessed C Source", cat: "code", viewer: "text", desc: "cpp output single translation unit." },
  { ext: ["ii"], name: "Preprocessed C++ Source", cat: "code", viewer: "text", desc: "cpp output for C++ translation unit." },
  { ext: ["td"], name: "TableGen Source", cat: "code", viewer: "text", desc: "LLVM TableGen domain description." },
  { ext: ["lo"], name: "Libtool Object", cat: "code", viewer: "fallback", desc: "PIC object wrapped by libtool." },
  { ext: ["rsp"], name: "Compiler Response File", cat: "code", viewer: "text", desc: "Tool argument list for command limits." },
  { ext: ["proj"], name: "MSBuild Project", cat: "code", viewer: "xml", desc: "Build script in MSBuild XML." },
  { ext: ["build"], name: "NAnt/Phing Build Script", cat: "code", viewer: "xml", desc: "XML build script for NAnt or Phing." },
  { ext: ["filters"], name: "VS Filter File", cat: "code", viewer: "xml", desc: "Solution explorer grouping for a vcxproj." },
  { ext: ["shproj"], name: "VS Shared Project", cat: "code", viewer: "xml", desc: "Shared code project definition." },
  { ext: ["user"], name: "VS User Settings", cat: "code", viewer: "xml", desc: "Per-user debugger options for a project." },
  { ext: ["pkgdef"], name: "VS Package Definition", cat: "code", viewer: "text", desc: "Registry-fragment for VS extension loading." },
  { ext: ["vssettings"], name: "VS Settings", cat: "code", viewer: "xml", desc: "Importable Visual Studio options." },
  { ext: ["slnf"], name: "VS Solution Filter", cat: "code", viewer: "json", desc: "Subset of projects loaded from a solution." },
  { ext: ["classpath"], name: "Eclipse Classpath", cat: "code", viewer: "xml", desc: "Java build path for an Eclipse project." },
  { ext: ["project"], name: "Eclipse Project", cat: "code", viewer: "xml", desc: "Project nature and builder description." },
  { ext: ["prefs"], name: "Eclipse Prefs", cat: "code", viewer: "text", desc: "Java-properties settings fragment." },
  { ext: ["checkstyle"], name: "Eclipse Checkstyle Config", cat: "code", viewer: "xml", desc: "Checkstyle profile for Eclipse projects." },
  { ext: ["factorypath"], name: "Eclipse Factory Path", cat: "code", viewer: "xml", desc: "Annotation processor path settings." },
  { ext: ["launch"], name: "Eclipse/ROS Launch", cat: "code", viewer: "xml", desc: "Run configuration or ROS node graph." },
  { ext: ["uvprojx"], name: "Keil uVision Project", cat: "code", viewer: "xml", desc: "ARM MDK project file." },
  { ext: ["uvoptx"], name: "Keil uVision Options", cat: "code", viewer: "xml", desc: "Per-user uVision debug options." },
  { ext: ["ewp"], name: "IAR Project", cat: "code", viewer: "xml", desc: "IAR Embedded Workbench project." },
  { ext: ["ewd"], name: "IAR Debugger Options", cat: "code", viewer: "xml", desc: "IAR debug settings file." },
  { ext: ["eww"], name: "IAR Workspace", cat: "code", viewer: "xml", desc: "IAR multi-project workspace." },
  { ext: ["icf"], name: "IAR Linker Config", cat: "code", viewer: "text", desc: "IAR XLINK placement syntax." },
  { ext: ["a51"], name: "Keil A51 Assembler", cat: "code", viewer: "text", desc: "8051 assembly source for Keil A51." },
  { ext: ["il"], name: "ILAsm Source", cat: "code", viewer: "text", desc: ".NET Common Intermediate Language text." },
  { ext: ["hsc"], name: "hsc2hs Source", cat: "code", viewer: "text", desc: "Haskell C-binding preprocessor input." },
  { ext: ["crate"], name: "Rust Crate Package", cat: "archive", viewer: "archive", desc: "Published cargo package tarball." },
  { ext: ["sum"], name: "Go Checksums", cat: "code", viewer: "text", desc: "Module dependency hashes for Go." },
  { ext: ["code-workspace"], name: "VS Code Workspace", cat: "code", viewer: "json", desc: "Multi-folder VS Code workspace." },
  { ext: ["rproj"], name: "RStudio Project", cat: "code", viewer: "text", desc: "R session and build options." },
  { ext: ["rprofile"], name: "R Profile", cat: "code", viewer: "text", desc: "R startup code (.Rprofile)." },
  { ext: ["rhistory"], name: "R History", cat: "data", viewer: "text", desc: "Saved R console history." },
  { ext: ["renviron"], name: "R Environment", cat: "config", viewer: "text", desc: "R startup environment variables." },
  { ext: ["rbuildignore"], name: "R Build Ignore", cat: "config", viewer: "text", desc: "Package build exclusion patterns." },
  { ext: ["lintr"], name: "lintr Config", cat: "config", viewer: "text", desc: "R static analysis options." },

  // ---------------- TextMate / Sublime ----------------
  { ext: ["tmLanguage"], name: "TextMate Grammar", cat: "code", viewer: "xml", desc: "Language syntax grammar plist." },
  { ext: ["tmTheme"], name: "TextMate Theme", cat: "config", viewer: "xml", desc: "Editor color theme plist." },
  { ext: ["tmPreferences"], name: "TextMate Preferences", cat: "code", viewer: "xml", desc: "Language typing and comment settings." },
  { ext: ["tmSnippet"], name: "TextMate Snippet", cat: "code", viewer: "xml", desc: "Tab-trigger expansion template." },
  { ext: ["tmCommand"], name: "TextMate Command", cat: "code", viewer: "xml", desc: "Shell command bundle item." },
  { ext: ["tmMacro"], name: "TextMate Macro", cat: "code", viewer: "xml", desc: "Recorded keystroke macro." },
  { ext: ["tm_properties"], name: "TextMate Properties", cat: "config", viewer: "text", desc: "TextMate 2 project preferences." },
  { ext: ["sublime-syntax"], name: "Sublime Syntax", cat: "code", viewer: "text", desc: "YAML syntax definition for Sublime Text." },
  { ext: ["sublime-settings"], name: "Sublime Settings", cat: "config", viewer: "json", desc: "Editor settings JSON." },
  { ext: ["sublime-project"], name: "Sublime Project", cat: "config", viewer: "json", desc: "Project folders and options." },
  { ext: ["sublime-workspace"], name: "Sublime Workspace", cat: "config", viewer: "json", desc: "Open files and UI state." },
  { ext: ["sublime-theme"], name: "Sublime Theme", cat: "config", viewer: "json", desc: "UI theme layout definition." },
  { ext: ["sublime-color-scheme"], name: "Sublime Color Scheme", cat: "config", viewer: "json", desc: "Syntax color assignments." },
  { ext: ["sublime-build"], name: "Sublime Build System", cat: "config", viewer: "json", desc: "Build command configuration." },
  { ext: ["sublime-commands"], name: "Sublime Commands", cat: "config", viewer: "json", desc: "Command palette entries." },
  { ext: ["sublime-completions"], name: "Sublime Completions", cat: "config", viewer: "json", desc: "Auto-completion list." },
  { ext: ["sublime-keymap"], name: "Sublime Keymap", cat: "config", viewer: "json", desc: "Keyboard bindings." },
  { ext: ["sublime-macro"], name: "Sublime Macro", cat: "config", viewer: "json", desc: "Recorded command sequence." },
  { ext: ["sublime-menu"], name: "Sublime Menu", cat: "config", viewer: "json", desc: "Menu structure definition." },
  { ext: ["sublime-mousemap"], name: "Sublime Mousemap", cat: "config", viewer: "json", desc: "Mouse binding definitions." },
  { ext: ["sublime-session"], name: "Sublime Session", cat: "config", viewer: "json", desc: "Persisted editor session state." },

  // ---------------- shaders / GPU ----------------
  { ext: ["fxh"], name: "DirectX Effect Header", cat: "code", viewer: "text", desc: "HLSL shared header for effect includes." },
  { ext: ["spirv"], name: "SPIR-V Binary", cat: "code", viewer: "fallback", sig: "03 02 23 07", desc: "Khronos intermediate shader binary." },
  { ext: ["cgfx"], name: "NVIDIA CgFX Effect", cat: "code", viewer: "xml", desc: "Cg shader effect with techniques and passes." },

  // ---------------- EDA / HDL / FPGA ----------------
  { ext: ["ttcn"], name: "TTCN-3 Source", cat: "code", viewer: "text", desc: "Testing language for conformance suites." },
  { ext: ["ucf"], name: "Xilinx UCF Constraints", cat: "code", viewer: "text", desc: "Legacy ISE placement/timing constraints." },
  { ext: ["xdc"], name: "Vivado Constraints", cat: "code", viewer: "text", desc: "Xilinx Design Constraints TCL." },
  { ext: ["qsys"], name: "Quartus Qsys System", cat: "code", viewer: "xml", desc: "Platform designer system description." },
  { ext: ["qip"], name: "Quartus IP File", cat: "config", viewer: "text", desc: "Source list for an IP variation." },
  { ext: ["qar"], name: "Quartus Archive", cat: "archive", viewer: "archive", desc: "Project archive export from Quartus." },
  { ext: ["saif"], name: "SAIF Activity", cat: "code", viewer: "text", desc: "Switching activity for power analysis." },
  { ext: ["upf"], name: "UPF Power Intent", cat: "code", viewer: "text", desc: "IEEE 1801 power domain description." },
  { ext: ["atp"], name: "TetraMAX Patterns", cat: "code", viewer: "text", desc: "ATPG test pattern file." },
  { ext: ["wlf"], name: "ModelSim Wave Log", cat: "scientific", viewer: "fallback", desc: "Questa/ModelSim simulation waveform." },
  { ext: ["fsdb"], name: "Verdi FSDB Waveform", cat: "scientific", viewer: "fallback", desc: "Synopsys Fast Signal Database." },
  { ext: ["blif"], name: "BLIF Netlist", cat: "code", viewer: "text", desc: "Berkeley logic interchange format." },
  { ext: ["eqn"], name: "EQN Logic Equation", cat: "code", viewer: "text", desc: "Berkeley boolean equation format." },
  { ext: ["vqm"], name: "Verilog Quartus Netlist", cat: "code", viewer: "text", desc: "Technology-mapped netlist text." },
  { ext: ["edif"], name: "EDIF Netlist", cat: "code", viewer: "text", desc: "Electronic Design Interchange Format s-expression." },
  { ext: ["scs"], name: "Spectre Netlist", cat: "code", viewer: "text", desc: "Cadence Spectre circuit description." },
  { ext: ["cdl"], name: "CDL Netlist", cat: "code", viewer: "text", desc: "Cadence circuit description language." },
  { ext: ["ckt"], name: "SPICE Circuit", cat: "code", viewer: "text", desc: "Circuit simulator deck." },
  { ext: ["sof"], name: "Altera SRAM Object", cat: "system", viewer: "fallback", desc: "FPGA bitstream for SRAM programming." },
  { ext: ["pof"], name: "Altera Programmer Object", cat: "system", viewer: "fallback", desc: "FPGA bitstream for flash programming." },
  { ext: ["jam"], name: "Jam STAPL Program", cat: "system", viewer: "text", desc: "ASCII device programming algorithm." },
  { ext: ["jbc"], name: "Jam Bytecode", cat: "system", viewer: "fallback", desc: "Compiled STAPL bytecode image." },
  { ext: ["jic"], name: "Intel FPGA Image", cat: "system", viewer: "fallback", desc: "JTAG-indirect config flash image." },

  // ---------------- color / timeline / editorial ----------------
  { ext: ["3dl"], name: "3D LUT Table", cat: "image", viewer: "text", desc: "Autodesk/Lustre cube color lookup table." },
  { ext: ["lut"], name: "LUT File", cat: "image", viewer: "text", desc: "Generic color lookup table text." },
  { ext: ["look"], name: "SpeedGrade Look", cat: "image", viewer: "fallback", desc: "IRIDAS/SpeedGrade color grade preset." },
  { ext: ["otio"], name: "OpenTimelineIO", cat: "video", viewer: "json", desc: "Editorial timeline interchange JSON." },
  { ext: ["otiod"], name: "OpenTimelineIO Bundle", cat: "video", viewer: "fallback", desc: "Directory bundle of OTIO media references." },
  { ext: ["otioz"], name: "OpenTimelineIO Archive", cat: "video", viewer: "archive", desc: "Zipped OTIO timeline with media." },

  // ---------------- video codecs / game AV ----------------
  { ext: ["fli"], name: "Autodesk FLIC Animation", cat: "video", viewer: "fallback", sig: "AF 12", desc: "Animator FLI frame animation." },
  { ext: ["flc"], name: "Autodesk FLC Animation", cat: "video", viewer: "fallback", sig: "AF 11", desc: "FLC Super VGA animation variant." },
  { ext: ["ipu"], name: "Sony IPU Video", cat: "video", viewer: "fallback", desc: "PS2 MPEG-2 in-house stream." },
  { ext: ["pss"], name: "Sony PSS Movie", cat: "video", viewer: "fallback", desc: "PS2 SSS audio/video mux." },
  { ext: ["pmf"], name: "PlayStation Movie Format", cat: "video", viewer: "fallback", desc: "PSP UMD video container." },
  { ext: ["cvm"], name: "CRI Middleware Video", cat: "video", viewer: "fallback", desc: "CRI RW video volume container." },
  { ext: ["xa"], name: "PS1 CD-XA Audio", cat: "audio", viewer: "fallback", desc: "CD-ROM XA ADPCM sector stream." },
  { ext: ["xma"], name: "Xbox XMA Audio", cat: "audio", viewer: "fallback", desc: "Xbox 360 XMA-compressed audio." },
  { ext: ["xwma"], name: "Xbox XWMA Audio", cat: "audio", viewer: "fallback", desc: "XMA-in-WMA container for Xbox." },
  { ext: ["h263"], name: "H.263 Bitstream", cat: "video", viewer: "fallback", desc: "Raw ITU H.263 elementary video." },
  { ext: ["h261"], name: "H.261 Bitstream", cat: "video", viewer: "fallback", desc: "Raw ISDN videoconferencing bitstream." },
  { ext: ["266"], name: "H.266 Bitstream", cat: "video", viewer: "fallback", desc: "Raw VVC elementary stream." },
  { ext: ["vvc"], name: "VVC Bitstream", cat: "video", viewer: "fallback", desc: "Versatile Video Coding raw stream." },
  { ext: ["xvid"], name: "Xvid Video", cat: "video", viewer: "fallback", desc: "Xvid MPEG-4 Part 2 AVI variant." },
  { ext: ["crm"], name: "Canon RAW Movie", cat: "video", viewer: "fallback", desc: "Cinema RAW Light/Full movie clip." },
  { ext: ["avb"], name: "Avid Bin", cat: "video", viewer: "fallback", desc: "Avid editing bin database." },
  { ext: ["wpl"], name: "Windows Media Playlist", cat: "audio", viewer: "xml", desc: "WMP SMIL-like playlist." },
  { ext: ["rmp"], name: "RealMedia Playlist", cat: "audio", viewer: "text", desc: "RealJukebox/Rhapsody playlist." },

  // ---------------- audio plugins / DAW ----------------
  { ext: ["aup"], name: "Audacity Project", cat: "audio", viewer: "fallback", desc: "Audacity 2 XML project with data folder." },
  { ext: ["aup3"], name: "Audacity Project 3", cat: "audio", viewer: "fallback", sig: "53 51 4C 69 74 65", desc: "Audacity 3 single-file SQLite project." },
  { ext: ["ses"], name: "Cool Edit Session", cat: "audio", viewer: "text", desc: "Adobe Audition/Cool Edit session." },
  { ext: ["sesx"], name: "Audition Session XML", cat: "audio", viewer: "xml", desc: "Modern Audition multitrack session." },
  { ext: ["cwp"], name: "Cakewalk Project", cat: "audio", viewer: "fallback", desc: "SONAR/Cakewalk project bundle." },
  { ext: ["rx2"], name: "Recycle 2 Loop", cat: "audio", viewer: "fallback", desc: "Propellerhead sliced REX loop." },
  { ext: ["rcy"], name: "Recycle 1 Loop", cat: "audio", viewer: "fallback", desc: "Legacy ReCycle slice library." },
  { ext: ["mt2"], name: "MadTracker 2 Module", cat: "audio", viewer: "midi", desc: "MadTracker 2 tracker song." },
  { ext: ["dbm"], name: "DigiBooster Pro Module", cat: "audio", viewer: "midi", desc: "Amiga DigiBooster Pro tracker." },
  { ext: ["fnk"], name: "Funktracker Module", cat: "audio", viewer: "midi", desc: "FunktrackerGold module format." },
  { ext: ["skm"], name: "Skale Module", cat: "audio", viewer: "midi", desc: "Skale Tracker module." },
  { ext: ["emd"], name: "ABT Extended Module", cat: "audio", viewer: "midi", desc: "Extended MB-klinik tracker module." },
  { ext: ["miz"], name: "Zipped Module", cat: "audio", viewer: "archive", desc: "Module wrapped in ZIP for M1 archives." },
  { ext: ["bank"], name: "FMOD Sound Bank", cat: "audio", viewer: "fallback", desc: "FMOD Studio audio bank with events." },
  { ext: ["csb"], name: "CRI Cue Sheet Binary", cat: "audio", viewer: "fallback", desc: "CRIWARE sound layout data." },
  { ext: ["awc"], name: "RAGE Audio Container", cat: "audio", viewer: "fallback", desc: "Rockstar advanced game engine audio." },
  { ext: ["sbk"], name: "Creative Sound Bank", cat: "audio", viewer: "fallback", desc: "Sound Blaster/E-mu bank patch data." },
  { ext: ["psflib"], name: "PSF Library", cat: "audio", viewer: "midi", desc: "Shared code bank for PSF rips." },
  { ext: ["gsflib"], name: "GSF Library", cat: "audio", viewer: "midi", desc: "Shared code bank for GBA GSF rips." },
  { ext: ["minipsf2"], name: "MiniPSF2", cat: "audio", viewer: "midi", desc: "PSF2 with external library refs." },
  { ext: ["usf"], name: "Nintendo 64 USF Audio", cat: "audio", viewer: "archive", desc: "Ultra64 Sound Format rip in zip." },
  { ext: ["omg"], name: "Sony OpenMG Audio", cat: "audio", viewer: "fallback", desc: "ATRAC in OpenMG DRM wrapper." },

  // ---------------- game data / platform containers ----------------
  { ext: ["blob"], name: "Steam ClientRegistry Blob", cat: "game", viewer: "fallback", desc: "Valve binary key/value registry." },
  { ext: ["ncf"], name: "Steam No-Cache File", cat: "game", viewer: "fallback", desc: "Steam content description file." },
  { ext: ["vdf"], name: "Valve Data File", cat: "config", viewer: "text", desc: "Steam key-value data (app manifests, scripts)." },
  { ext: ["wotreplay"], name: "World of Tanks Replay", cat: "game", viewer: "fallback", desc: "Recorded battle data blocks." },
  { ext: ["sga"], name: "Relic SGA Archive", cat: "game", viewer: "fallback", desc: "Company of Heroes/Dawn of War assets." },
  { ext: ["rgd"], name: "Relic Game Data", cat: "game", viewer: "fallback", desc: "Relic attribute data file." },
  { ext: ["h4r"], name: "Heroes IV Resource", cat: "game", viewer: "fallback", desc: "Might and Magic IV archive." },
  { ext: ["lod"], name: "NWC LOD Archive", cat: "game", viewer: "fallback", desc: "Might and Magic resource container." },
  { ext: ["msbt"], name: "Nintendo MSBT Message", cat: "game", viewer: "fallback", desc: "Localized message strings." },
  { ext: ["bmg"], name: "GameCube BMG Text", cat: "game", viewer: "fallback", desc: "GameCube/Wii message pack." },
  { ext: ["sarc"], name: "Nintendo SARC Archive", cat: "game", viewer: "fallback", sig: "53 41 52 43", desc: "Hash-based resource container." },
  { ext: ["bntx"], name: "Switch Texture Container", cat: "game", viewer: "fallback", desc: "NX GPU binary textures." },
  { ext: ["bfres"], name: "Wii U Resource Container", cat: "game", viewer: "fallback", desc: "Cafe model/texture archive." },
  { ext: ["bflim"], name: "Wii U Texture", cat: "game", viewer: "fallback", desc: "Cafe GPU texture layout." },
  { ext: ["tik"], name: "Switch Title Ticket", cat: "game", viewer: "fallback", desc: "Console rights/ticket blob." },
  { ext: ["cert"], name: "Switch Certificate", cat: "game", viewer: "fallback", desc: "Console signed certificate chain." },
  { ext: ["nca"], name: "Switch Content Archive", cat: "game", viewer: "fallback", desc: "NX game content distribution container." },
  { ext: ["qvm"], name: "Quake Virtual Machine", cat: "game", viewer: "fallback", desc: "Q3 compiled bytecode module." },
  { ext: ["puz"], name: "Across Lite Crossword", cat: "game", viewer: "fallback", desc: "Crossword grid/clue puzzle." },
  { ext: ["blz"], name: "N-Gage Installer", cat: "game", viewer: "fallback", desc: "Blz-packed N-Gage game image." },
  { ext: ["n-gage"], name: "N-Gage Game Package", cat: "game", viewer: "fallback", desc: "N-Gage 2.0 distribution game file." },
  { ext: ["nth"], name: "Nokia S40 Theme", cat: "system", viewer: "archive", desc: "Series 40 packaged theme zip." },
  { ext: ["utz"], name: "Sony Ericsson Theme", cat: "system", viewer: "archive", desc: "SE phone packaged theme." },

  // ---------------- emulation / disk images ----------------
  { ext: ["mfi"], name: "MAME Floppy Image", cat: "disk", viewer: "fallback", desc: "MAME flux-level disk representation." },
  { ext: ["d77"], name: "PC-8801 Disk Image", cat: "disk", viewer: "fallback", desc: "NEC 2D sector disk capture." },
  { ext: ["d82"], name: "CBM 8250 Disk Image", cat: "disk", viewer: "fallback", desc: "Commodore dual-density 1571/8250." },
  { ext: ["x64"], name: "C64 X64 Image", cat: "disk", viewer: "fallback", desc: "VICE sector disk image." },
  { ext: ["seq"], name: "C64 SEQ File", cat: "data", viewer: "fallback", desc: "Commodore sequential data file." },
  { ext: ["usr"], name: "C64 USR File", cat: "data", viewer: "fallback", desc: "Commodore user storage area file." },
  { ext: ["mgt"], name: "SAM Coupé MGT Disk", cat: "disk", viewer: "fallback", desc: "SAM/Gordon disk image." },
  { ext: ["tig"], name: "TI Group Archive", cat: "archive", viewer: "archive", desc: "TI Connect calculator file bundle." },
];
